.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH B::CC 3 "perl 5.005, patch 53" "5/Nov/98" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
B::CC \- Perl compiler's optimized C translation backend
.SH "SYNOPSIS"
.PP
.Vb 1
\&        perl -MO=CC[,OPTIONS] foo.pl
.Ve
.SH "DESCRIPTION"
This compiler backend takes Perl source and generates C source code
corresponding to the flow of your program. In other words, this
backend is somewhat a \*(L"real\*(R" compiler in the sense that many people
think about compilers. Note however that, currently, it is a very
poor compiler in that although it generates (mostly, or at least
sometimes) correct code, it performs relatively few optimisations.
This will change as the compiler develops. The result is that
running an executable compiled with this backend may start up more
quickly than running the original Perl program (a feature shared
by the \fBC\fR compiler backend\*(--see \fIB::C\fR) and may also execute
slightly faster. This is by no means a good optimising compiler\*(--yet.
.SH "OPTIONS"
If there are any non-option arguments, they are taken to be
names of objects to be saved (probably doesn't work properly yet).
Without extra arguments, it saves the main program.
.Ip "\fB\-ofilename\fR" 4
Output to filename instead of \s-1STDOUT\s0
.Ip "\fB\-v\fR" 4
Verbose compilation (currently gives a few compilation statistics).
.Ip "\fB--\fR" 4
Force end of options
.Ip "\fB\-uPackname\fR" 4
Force apparently unused subs from package Packname to be compiled.
This allows programs to use eval \*(L"\fIfoo()\fR\*(R" even when sub foo is never
seen to be used at compile time. The down side is that any subs which
really are never used also have code generated. This option is
necessary, for example, if you have a signal handler foo which you
initialise with \f(CW$SIG{BAR} = "foo"\fR.  A better fix, though, is just
to change it to \f(CW$SIG{BAR} = \e&foo\fR. You can have multiple \fB\-u\fR
options. The compiler tries to figure out which packages may possibly
have subs in which need compiling but the current version doesn't do
it very well. In particular, it is confused by nested packages (i.e.
of the form \f(CWA::B\fR) where package \f(CWA\fR does not contain any subs.
.Ip "\fB\-mModulename\fR" 4
Instead of generating source for a runnable executable, generate
source for an \s-1XSUB\s0 module. The boot_Modulename function (which
DynaLoader can look for) does the appropriate initialisation and runs
the main part of the Perl source that is being compiled.
.Ip "\fB\-D\fR" 4
Debug options (concatenated or separate flags like \f(CWperl -D\fR).
.Ip "\fB\-Dr\fR" 4
Writes debugging output to \s-1STDERR\s0 just as it's about to write to the
program's runtime (otherwise writes debugging info as comments in
its C output).
.Ip "\fB\-\s-1DO\s0\fR" 4
Outputs each \s-1OP\s0 as it's compiled
.Ip "\fB\-Ds\fR" 4
Outputs the contents of the shadow stack at each \s-1OP\s0
.Ip "\fB\-Dp\fR" 4
Outputs the contents of the shadow pad of lexicals as it's loaded for
each sub or the main program.
.Ip "\fB\-Dq\fR" 4
Outputs the name of each fake \s-1PP\s0 function in the queue as it's about
to process it.
.Ip "\fB\-Dl\fR" 4
Output the filename and line number of each original line of Perl
code as it's processed (\f(CWpp_nextstate\fR).
.Ip "\fB\-Dt\fR" 4
Outputs timing information of compilation stages.
.Ip "\fB\-f\fR" 4
Force optimisations on or off one at a time.
.Ip "\fB\-ffreetmps-each-bblock\fR" 4
Delays \s-1FREETMPS\s0 from the end of each statement to the end of the each
basic block.
.Ip "\fB\-ffreetmps-each-loop\fR" 4
Delays \s-1FREETMPS\s0 from the end of each statement to the end of the group
of basic blocks forming a loop. At most one of the freetmps-each-*
options can be used.
.Ip "\fB\-fomit-taint\fR" 4
Omits generating code for handling perl's tainting mechanism.
.Ip "\fB\-On\fR" 4
Optimisation level (n = 0, 1, 2, ...). \fB\-O\fR means \fB\-O1\fR.
Currently, \fB\-O1\fR sets \fB\-ffreetmps-each-bblock\fR and \fB\-O2\fR
sets \fB\-ffreetmps-each-loop\fR.
.SH "EXAMPLES"
.PP
.Vb 2
\&        perl -MO=CC,-O2,-ofoo.c foo.pl
\&        perl cc_harness -o foo foo.c
.Ve
Note that \f(CWcc_harness\fR lives in the \f(CWB\fR subdirectory of your perl
library directory. The utility called \f(CWperlcc\fR may also be used to
help make use of this compiler.
.PP
.Vb 2
\&        perl -MO=CC,-mFoo,-oFoo.c Foo.pm
\&        perl cc_harness -shared -c -o Foo.so Foo.c
.Ve
.SH "BUGS"
Plenty. Current status: experimental.
.SH "DIFFERENCES"
These aren't really bugs but they are constructs which are heavily
tied to perl's compile-and-go implementation and with which this
compiler backend cannot cope.
.Sh "Loops"
Standard perl calculates the target of \*(L"next\*(R", \*(L"last\*(R", and \*(L"redo\*(R"
at run-time. The compiler calculates the targets at compile-time.
For example, the program
.PP
.Vb 5
\&    sub skip_on_odd { next NUMBER if $_[0] % 2 }
\&    NUMBER: for ($i = 0; $i < 5; $i++) {
\&        skip_on_odd($i);
\&        print $i;
\&    }
.Ve
produces the output
.PP
.Vb 1
\&    024
.Ve
with standard perl but gives a compile-time error with the compiler.
.Sh "Context of \*(M"..\*(S""
The context (scalar or array) of the \*(L"..\*(R" operator determines whether
it behaves as a range or a flip/flop. Standard perl delays until
runtime the decision of which context it is in but the compiler needs
to know the context at compile-time. For example,
.PP
.Vb 4
\&    @a = (4,6,1,0,0,1);
\&    sub range { (shift @a)..(shift @a) }
\&    print range();
\&    while (@a) { print scalar(range()) }
.Ve
generates the output
.PP
.Vb 1
\&    456123E0
.Ve
with standard Perl but gives a compile-time error with compiled Perl.
.Sh "Arithmetic"
Compiled Perl programs use native C arithemtic much more frequently
than standard perl. Operations on large numbers or on boundary
cases may produce different behaviour.
.Sh "Deprecated features"
Features of standard perl such as \f(CW$[\fR which have been deprecated
in standard perl since Perl5 was released have not been implemented
in the compiler.
.SH "AUTHOR"
Malcolm Beattie, \f(CWmbeattie@sable.ox.ac.uk\fR

.rn }` ''
.IX Title "B::CC 3"
.IX Name "B::CC - Perl compiler's optimized C translation backend"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\fB\-ofilename\fR"

.IX Item "\fB\-v\fR"

.IX Item "\fB--\fR"

.IX Item "\fB\-uPackname\fR"

.IX Item "\fB\-mModulename\fR"

.IX Item "\fB\-D\fR"

.IX Item "\fB\-Dr\fR"

.IX Item "\fB\-\s-1DO\s0\fR"

.IX Item "\fB\-Ds\fR"

.IX Item "\fB\-Dp\fR"

.IX Item "\fB\-Dq\fR"

.IX Item "\fB\-Dl\fR"

.IX Item "\fB\-Dt\fR"

.IX Item "\fB\-f\fR"

.IX Item "\fB\-ffreetmps-each-bblock\fR"

.IX Item "\fB\-ffreetmps-each-loop\fR"

.IX Item "\fB\-fomit-taint\fR"

.IX Item "\fB\-On\fR"

.IX Header "EXAMPLES"

.IX Header "BUGS"

.IX Header "DIFFERENCES"

.IX Subsection "Loops"

.IX Subsection "Context of \*(M"..\*(S""

.IX Subsection "Arithmetic"

.IX Subsection "Deprecated features"

.IX Header "AUTHOR"

