.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH CGI::Cookie 3 "perl 5.005, patch 53" "28/Jun/98" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
CGI::Cookie \- Interface to Netscape Cookies
.SH "SYNOPSIS"
.PP
.Vb 2
\&    use CGI qw/:standard/;
\&    use CGI::Cookie;
.Ve
.Vb 7
\&    # Create new cookies and send them
\&    $cookie1 = new CGI::Cookie(-name=>'ID',-value=>123456);
\&    $cookie2 = new CGI::Cookie(-name=>'preferences',
\&                               -value=>{ font => Helvetica,
\&                                         size => 12 } 
\&                               );
\&    print header(-cookie=>[$cookie1,$cookie2]);
.Ve
.Vb 3
\&    # fetch existing cookies
\&    %cookies = fetch CGI::Cookie;
\&    $id = $cookies{'ID'}->value;
.Ve
.Vb 2
\&    # create cookies returned from an external source
\&    %cookies = parse CGI::Cookie($ENV{COOKIE});
.Ve
.SH "DESCRIPTION"
CGI::Cookie is an interface to Netscape (HTTP/1.1) cookies, an
innovation that allows Web servers to store persistent information on
the browser's side of the connection.  Although CGI::Cookie is
intended to be used in conjunction with CGI.pm (and is in fact used by
it internally), you can use this module independently.
.PP
For full information on cookies see 
.PP
.Vb 1
\&        http://www.ics.uci.edu/pub/ietf/http/rfc2109.txt
.Ve
.SH "USING CGI::Cookie"
CGI::Cookie is object oriented.  Each cookie object has a name and a
value.  The name is any scalar value.  The value is any scalar or
array value (associative arrays are also allowed).  Cookies also have
several optional attributes, including:
.Ip "\fB1. expiration date\fR" 4
The expiration date tells the browser how long to hang on to the
cookie.  If the cookie specifies an expiration date in the future, the
browser will store the cookie information in a disk file and return it
to the server every time the user reconnects (until the expiration
date is reached).  If the cookie species an expiration date in the
past, the browser will remove the cookie from the disk file.  If the
expiration date is not specified, the cookie will persist only until
the user quits the browser.
.Ip "\fB2. domain\fR" 4
This is a partial or complete domain name for which the cookie is 
valid.  The browser will return the cookie to any host that matches
the partial domain name.  For example, if you specify a domain name
of \*(L".capricorn.com\*(R", then Netscape will return the cookie to
Web servers running on any of the machines \*(L"www.capricorn.com\*(R", 
\*(L"ftp.capricorn.com\*(R", \*(L"feckless.capricorn.com\*(R", etc.  Domain names
must contain at least two periods to prevent attempts to match
on top level domains like \*(L".edu\*(R".  If no domain is specified, then
the browser will only return the cookie to servers on the host the
cookie originated from.
.Ip "\fB3. path\fR" 4
If you provide a cookie path attribute, the browser will check it
against your script's \s-1URL\s0 before returning the cookie.  For example,
if you specify the path \*(L"/cgi-bin\*(R", then the cookie will be returned
to each of the scripts \*(L"/cgi-bin/tally.pl\*(R", \*(L"/cgi-bin/order.pl\*(R",
and \*(L"/cgi-bin/customer_service/complain.pl\*(R", but not to the script
\*(L"/cgi-private/site_admin.pl\*(R".  By default, path is set to \*(L"/\*(R", which
causes the cookie to be sent to any \s-1CGI\s0 script on your site.
.Ip "\fB4. secure flag\fR" 4
If the \*(L"secure\*(R" attribute is set, the cookie will only be sent to your
script if the \s-1CGI\s0 request is occurring on a secure channel, such as \s-1SSL\s0.
.Sh "Creating New Cookies"
.PP
.Vb 7
\&        $c = new CGI::Cookie(-name    =>  'foo',
\&                             -value   =>  'bar',
\&                             -expires =>  '+3M',
\&                             -domain  =>  '.capricorn.com',
\&                             -path    =>  '/cgi-bin/database'
\&                             -secure  =>  1
\&                            );
.Ve
Create cookies from scratch with the \fBnew\fR method.  The \fB\-name\fR and
\fB\-value\fR parameters are required.  The name must be a scalar value.
The value can be a scalar, an array reference, or a hash reference.
(At some point in the future cookies will support one of the Perl
object serialization protocols for full generality).
.PP
\fB\-expires\fR accepts any of the relative or absolute date formats
recognized by \s-1CGI\s0.pm, for example \*(L"+3M\*(R" for three months in the
future.  See \s-1CGI\s0.pm's documentation for details.
.PP
\fB\-domain\fR points to a domain name or to a fully qualified host name.
If not specified, the cookie will be returned only to the Web server
that created it.
.PP
\fB\-path\fR points to a partial \s-1URL\s0 on the current server.  The cookie
will be returned to all URLs beginning with the specified path.  If
not specified, it defaults to \*(L'/\*(R', which returns the cookie to all
pages at your site.
.PP
\fB\-secure\fR if set to a true value instructs the browser to return the
cookie only when a cryptographic protocol is in use.
.Sh "Sending the Cookie to the Browser"
Within a \s-1CGI\s0 script you can send a cookie to the browser by creating
one or more Set-Cookie: fields in the \s-1HTTP\s0 header.  Here is a typical
sequence:
.PP
.Vb 3
\&  my $c = new CGI::Cookie(-name    =>  'foo',
\&                          -value   =>  ['bar','baz'],
\&                          -expires =>  '+3M');
.Ve
.Vb 2
\&  print "Set-Cookie: $c\en";
\&  print "Content-Type: text/html\en\en";
.Ve
To send more than one cookie, create several Set-Cookie: fields.
Alternatively, you may concatenate the cookies together with \*(L"; \*(L" and
send them in one field.
.PP
If you are using \s-1CGI\s0.pm, you send cookies by providing a \-cookie
argument to the \fIheader()\fR method:
.PP
.Vb 1
\&  print header(-cookie=>$c);
.Ve
Mod_perl users can set cookies using the request object's \fIheader_out()\fR
method:
.PP
.Vb 1
\&  $r->header_out('Set-Cookie',$c);
.Ve
Internally, Cookie overloads the "" operator to call its \fIas_string()\fR
method when incorporated into the \s-1HTTP\s0 header.  \fIas_string()\fR turns the
Cookie's internal representation into an \s-1RFC\s0\-compliant text
representation.  You may call \fIas_string()\fR yourself if you prefer:
.PP
.Vb 1
\&  print "Set-Cookie: ",$c->as_string,"\en";
.Ve
.Sh "Recovering Previous Cookies"
.PP
.Vb 1
\&        %cookies = fetch CGI::Cookie;
.Ve
\fBfetch\fR returns an associative array consisting of all cookies
returned by the browser.  The keys of the array are the cookie names.  You
can iterate through the cookies this way:
.PP
.Vb 4
\&        %cookies = fetch CGI::Cookie;
\&        foreach (keys %cookies) {
\&           do_something($cookies{$_});
\&        }
.Ve
In a scalar context, \fIfetch()\fR returns a hash reference, which may be more
efficient if you are manipulating multiple cookies.
    
\s-1CGI\s0.pm uses the \s-1URL\s0 escaping methods to save and restore reserved characters
in its cookies.  If you are trying to retrieve a cookie set by a foreign server,
this escaping method may trip you up.  Use \fIraw_fetch()\fR instead, which has the
same semantics as \fIfetch()\fR, but performs no unescaping.
.PP
You may also retrieve cookies that were stored in some external
form using the \fIparse()\fR class method:
.PP
.Vb 2
\&       $COOKIES = `cat /usr/tmp/Cookie_stash`;
\&       %cookies = parse CGI::Cookie($COOKIES);
.Ve
.Sh "Manipulating Cookies"
Cookie objects have a series of accessor methods to get and set cookie
attributes.  Each accessor has a similar syntax.  Called without
arguments, the accessor returns the current value of the attribute.
Called with an argument, the accessor changes the attribute and
returns its new value.
.Ip "\fBname()\fR" 4
Get or set the cookie's name.  Example:
.Sp
.Vb 2
\&        $name = $c->name;
\&        $new_name = $c->name('fred');
.Ve
.Ip "\fBvalue()\fR" 4
Get or set the cookie's value.  Example:
.Sp
.Vb 2
\&        $value = $c->value;
\&        @new_value = $c->value(['a','b','c','d']);
.Ve
\fBvalue()\fR is context sensitive.  In an array context it will return
the current value of the cookie as an array.  In a scalar context it
will return the \fBfirst\fR value of a multivalued cookie.
.Ip "\fBdomain()\fR" 4
Get or set the cookie's domain.
.Ip "\fBpath()\fR" 4
Get or set the cookie's path.
.Ip "\fBexpires()\fR" 4
Get or set the cookie's expiration time.
.SH "AUTHOR INFORMATION"
be used and modified freely, but I do request that this copyright
notice remain attached to the file.  You may modify this module as you
wish, but if you redistribute a modified version, please attach a note
listing the modifications you have made.
.PP
Address bug reports and comments to:
lstein@genome.wi.mit.edu
.SH "BUGS"
This section intentionally left blank.
.SH "SEE ALSO"
the \fICGI::Carp\fR manpage, the \fICGI\fR manpage
 
=cut

.rn }` ''
.IX Title "CGI::Cookie 3"
.IX Name "CGI::Cookie - Interface to Netscape Cookies"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "USING CGI::Cookie"

.IX Item "\fB1. expiration date\fR"

.IX Item "\fB2. domain\fR"

.IX Item "\fB3. path\fR"

.IX Item "\fB4. secure flag\fR"

.IX Subsection "Creating New Cookies"

.IX Subsection "Sending the Cookie to the Browser"

.IX Subsection "Recovering Previous Cookies"

.IX Subsection "Manipulating Cookies"

.IX Item "\fBname()\fR"

.IX Item "\fBvalue()\fR"

.IX Item "\fBdomain()\fR"

.IX Item "\fBpath()\fR"

.IX Item "\fBexpires()\fR"

.IX Header "AUTHOR INFORMATION"

.IX Header "BUGS"

.IX Header "SEE ALSO"

