.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
.ds L' '
.ds R' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds L' `
.ds R' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH WAIT 1 "perl 5.003, patch 93" "17/Feb/97" "User Contributed Perl Documentation"
.IX Title "WAIT 1"
.UC
.IX Name "CPAN::WAIT - adds commands to search a WAIT4CPAN server to the CPAN C<shell()>"
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
.IX Header "NAME"
CPAN::WAIT \- adds commands to search a WAIT4CPAN server to the CPAN \f(CWshell()\fR
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
.PP
.Vb 7
\&  perl -MCPAN -e shell
\&  > wq au=wall
\&  > wr 3
\&  > wd 3
\&  > wl 20
\&  > wh
\&  > wh wq
.Ve
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fBCPAN::WAIT\fR adds some comands to the CPAN \f(CWshell()\fR to perform
searches on a WAIT server. It connects to a WAIT server using a simple
protocoll resembling NNTP as described in RFC977. It uses the
\fBWAIT::Client\fR module to handle this connection. This in turn
inherits from \fBNet::NNTP\fR from the \fIlibnet\fR package. So you need
\fBNet::NNTP\fR to use this module.
.PP
If no direct connection to the WAIT server is possible, the modules
tries to connect via your HTTP proxy (as given by the CPAN
configuration). Be warned though that the emulation of the stateful
protocol via HTTP is slow.
.PP
The commands available are:
.Ip "\fBwh\fR [\fBcommand\fR]" 5
.IX Item "\fBwh\fR [\fBcommand\fR]"
Displays a short help message if called without arguments. If you
provide the name of another command you will get more information on
this command if available. Currently only \fBwq\fR will be explained.
.Ip "\fBwl\fR \fIcount\fR" 5
.IX Item "\fBwl\fR \fIcount\fR"
Limit the number of hits returned in a search to \fIcount\fR. The limit
usually is set ot 10 of you don't set it.
.Ip "\fBwq\fR \fIquery\fR" 5
.IX Item "\fBwq\fR \fIquery\fR"
Send a query to the server. 
.Sp
Here are some query examples:
.Sp
.Vb 10
\&  information retrieval               free text query 
\&  information or retrieval            same as above 
\&  des=information retrieval           `information' must be in the description 
\&  des=(information retrieval)         one of them in description 
\&  des=(information or retrieval)      same as above 
\&  des=(information and retrieval)     both of them in description 
\&  des=(information not retrieval)     `information' in description and
\&                                      `retrieval' not in description 
\&  des=(information system*)           wild-card search
\&  au=ilia                             author names may be misspelled
.Ve
You can build arbitary boolean combination of the above examples.
Field names may be abbreviated. For further information see
\fIhttp://ls6-www.informatik.uni-dortmund.de/\s-1CPAN\s0\fR
.Sp
The result should look like this:
.Sp
.Vb 1
\&  wq au=wall
.Ve
.Vb 10
\&   1 8.039 a2p - Awk to Perl translator 
\&   2 8.039 s2p - Sed to Perl translator 
\&   3 8.039 perlipc - Perl interprocess communication (signals, fifos, pipes, safe subprocesses, sockets, and semaphores) 
\&   4 8.039 ExtUtils::DynaGlue - Methods for generating Perl extension files 
\&   5 8.039 h2xs - convert .h C header files to Perl extensions 
\&   6 8.039 Sys::Syslog, openlog, closelog, setlogmask, syslog - Perl interface to the UNIX syslog(3) calls 
\&   7 8.039 h2ph - convert .h C header files to .ph Perl header files 
\&   8 8.039 Shell - run shell commands transparently within perl 
\&   9 8.039 pl2pm - Rough tool to translate Perl4 .pl files to Perl5 .pm modules. 
\&  10 8.039 perlpod - plain old documentation 
.Ve
.Ip "\fBwr\fR \fIhit-number\fR" 5
.IX Item "\fBwr\fR \fIhit-number\fR"
Display the Record of hit number \fIhit-number\fR:
.Sp
.Vb 6
\&  wr 1
\&  
\&  source          authors/id/CHIPS/perl5.003_24.tar.gz
\&  headline        a2p - Awk to Perl translator 
\&  size            5643
\&  docid           data/perl/x2p/a2p.pod
.Ve
.Ip "\fBwd\fR \fIhit-number\fR" 5
.IX Item "\fBwd\fR \fIhit-number\fR"
Fetches the full text from the server and runs \fBperlpod\fR on it. Make
sure that you have \fBperlpod\fR in your path. Also check if your
\fBperlpod\fR version can handle absolute pathes. Some older versions
ironically do not find a document if the full patch is given on the
command line.
.SH "AUTHOR"
.IX Header "AUTHOR"
Ulrich Pfeifer <\fIpfeifer@ls6.informatik.uni-dortmund.de\fR>

.rn }` ''
