.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH Exporter 3 "perl 5.004, patch 55" "25/Nov/97" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
Exporter \- Implements default import method for modules
.SH "SYNOPSIS"
In module ModuleName.pm:
.PP
.Vb 3
\&  package ModuleName;
\&  require Exporter;
\&  @ISA = qw(Exporter);
.Ve
.Vb 3
\&  @EXPORT = qw(...);            # symbols to export by default
\&  @EXPORT_OK = qw(...);         # symbols to export on request
\&  %EXPORT_TAGS = tag => [...];  # define names for sets of symbols
.Ve
In other files which wish to use ModuleName:
.PP
.Vb 1
\&  use ModuleName;               # import default symbols into my package
.Ve
.Vb 1
\&  use ModuleName qw(...);       # import listed symbols into my package
.Ve
.Vb 1
\&  use ModuleName ();            # do not import any symbols
.Ve
.SH "DESCRIPTION"
The Exporter module implements a default \f(CWimport\fR method which
many modules choose to inherit rather than implement their own.
.PP
Perl automatically calls the \f(CWimport\fR method when processing a
\f(CWuse\fR statement for a module. Modules and \f(CWuse\fR are documented
in the \fIperlfunc\fR manpage and the \fIperlmod\fR manpage. Understanding the concept of
modules and how the \f(CWuse\fR statement operates is important to
understanding the Exporter.
.Sh "Selecting What To Export"
Do \fBnot\fR export method names!
.PP
Do \fBnot\fR export anything else by default without a good reason!
.PP
Exports pollute the namespace of the module user.  If you must export
try to use \f(CW@EXPORT_OK\fR in preference to \f(CW@EXPORT\fR and avoid short or
common symbol names to reduce the risk of name clashes.
.PP
Generally anything not exported is still accessible from outside the
module using the ModuleName::item_name (or \f(CW$blessed_ref\fR\->method)
syntax.  By convention you can use a leading underscore on names to
informally indicate that they are \*(L'internal\*(R' and not for public use.
.PP
(It is actually possible to get private functions by saying:
.PP
.Vb 2
\&  my $subref = sub { ... };
\&  &$subref;
.Ve
But there's no way to call that directly as a method, since a method
must have a name in the symbol table.)
.PP
As a general rule, if the module is trying to be object oriented
then export nothing. If it's just a collection of functions then
\f(CW@EXPORT_OK\fR anything but use \f(CW@EXPORT\fR with caution.
.PP
Other module design guidelines can be found in the \fIperlmod\fR manpage.
.Sh "Specialised Import Lists"
If the first entry in an import list begins with !, : or / then the
list is treated as a series of specifications which either add to or
delete from the list of names to import. They are processed left to
right. Specifications are in the form:
.PP
.Vb 4
\&    [!]name         This name only
\&    [!]:DEFAULT     All names in @EXPORT
\&    [!]:tag         All names in $EXPORT_TAGS{tag} anonymous list
\&    [!]/pattern/    All names in @EXPORT and @EXPORT_OK which match
.Ve
A leading ! indicates that matching names should be deleted from the
list of names to import.  If the first specification is a deletion it
is treated as though preceded by :\s-1DEFAULT\s0. If you just want to import
extra names in addition to the default set you will still need to
include :\s-1DEFAULT\s0 explicitly.
.PP
e.g., Module.pm defines:
.PP
.Vb 3
\&    @EXPORT      = qw(A1 A2 A3 A4 A5);
\&    @EXPORT_OK   = qw(B1 B2 B3 B4 B5);
\&    %EXPORT_TAGS = (T1 => [qw(A1 A2 B1 B2)], T2 => [qw(A1 A2 B3 B4)]);
.Ve
.Vb 2
\&    Note that you cannot use tags in @EXPORT or @EXPORT_OK.
\&    Names in EXPORT_TAGS must also appear in @EXPORT or @EXPORT_OK.
.Ve
An application using Module can say something like:
.PP
.Vb 1
\&    use Module qw(:DEFAULT :T2 !B3 A3);
.Ve
Other examples include:
.PP
.Vb 2
\&    use Socket qw(!/^[AP]F_/ !SOMAXCONN !SOL_SOCKET);
\&    use POSIX  qw(:errno_h :termios_h !TCSADRAIN !/^EXIT/);
.Ve
Remember that most patterns (using //) will need to be anchored
with a leading ^, e.g., \f(CW/^EXIT/\fR rather than \f(CW/EXIT/\fR.
.PP
You can say \f(CWBEGIN { $Exporter::Verbose=1 }\fR to see how the
specifications are being processed and what is actually being imported
into modules.
.Sh "Exporting without using Export's import method"
Exporter has a special method, \*(L'export_to_level\*(R' which is used in situations
where you can't directly call Export's import method. The export_to_level
method looks like:
.PP
MyPackage->\fIexport_to_level\fR\|($where_to_export, \f(CW@what_to_export\fR);
.PP
where \f(CW$where_to_export\fR is an integer telling how far up the calling stack
to export your symbols, and \f(CW@what_to_export\fR is an array telling what
symbols *to* export (usually this is \f(CW@_\fR).
.PP
For example, suppose that you have a module, A, which already has an
import function:
.PP
package A;
.PP
@\s-1ISA\s0 = \fIqw\fR\|(Exporter);
\f(CW@EXPORT_OK\fR = qw ($b);
.PP
sub import
{
    \f(CW$A::b\fR = 1;     # not a very useful import method
}
.PP
and you want to Export symbol \f(CW$A::b\fR back to the module that called 
package A. Since Exporter relies on the import method to work, via 
inheritance, as it stands \fIExporter::import()\fR will never get called. 
Instead, say the following:
.PP
package A;
\f(CW@ISA\fR = \fIqw\fR\|(Exporter);
\f(CW@EXPORT_OK\fR = qw ($b);
.PP
sub import
{
    \f(CW$A::b\fR = 1;
    A\->\fIexport_to_level\fR\|(1, \f(CW@_\fR);
}
.PP
This will export the symbols one level \*(L'above\*(R' the current package \- ie: to 
the program or module that used package A. 
.PP
Note: Be careful not to modify \*(L'@_\*(R' at all before you call export_to_level
\- or people using your package will get very unexplained results!
.Sh "Module Version Checking"
The Exporter module will convert an attempt to import a number from a
module into a call to \f(CW$module_name\fR\->\fIrequire_version\fR\|($value). This can
be used to validate that the version of the module being used is
greater than or equal to the required version.
.PP
The Exporter module supplies a default require_version method which
checks the value of \f(CW$VERSION\fR in the exporting module.
.PP
Since the default require_version method treats the \f(CW$VERSION\fR number as
a simple numeric value it will regard version 1.10 as lower than
1.9. For this reason it is strongly recommended that you use numbers
with at least two decimal places, e.g., 1.09.
.Sh "Managing Unknown Symbols"
In some situations you may want to prevent certain symbols from being
exported. Typically this applies to extensions which have functions
or constants that may not exist on some systems.
.PP
The names of any symbols that cannot be exported should be listed
in the \f(CW@EXPORT_FAIL\fR array.
.PP
If a module attempts to import any of these symbols the Exporter
will give the module an opportunity to handle the situation before
generating an error. The Exporter will call an export_fail method
with a list of the failed symbols:
.PP
.Vb 1
\&  @failed_symbols = $module_name->export_fail(@failed_symbols);
.Ve
If the export_fail method returns an empty list then no error is
recorded and all the requested symbols are exported. If the returned
list is not empty then an error is generated for each symbol and the
export fails. The Exporter provides a default export_fail method which
simply returns the list unchanged.
.PP
Uses for the export_fail method include giving better error messages
for some symbols and performing lazy architectural checks (put more
symbols into \f(CW@EXPORT_FAIL\fR by default and then take them out if someone
actually tries to use them and an expensive check shows that they are
usable on that platform).
.Sh "Tag Handling Utility Functions"
Since the symbols listed within \f(CW%EXPORT_TAGS\fR must also appear in either
\f(CW@EXPORT\fR or \f(CW@EXPORT_OK\fR, two utility functions are provided which allow
you to easily add tagged sets of symbols to \f(CW@EXPORT\fR or \f(CW@EXPORT_OK:\fR
.PP
.Vb 1
\&  %EXPORT_TAGS = (foo => [qw(aa bb cc)], bar => [qw(aa cc dd)]);
.Ve
.Vb 2
\&  Exporter::export_tags('foo');     # add aa, bb and cc to @EXPORT
\&  Exporter::export_ok_tags('bar');  # add aa, cc and dd to @EXPORT_OK
.Ve
Any names which are not tags are added to \f(CW@EXPORT\fR or \f(CW@EXPORT_OK\fR
unchanged but will trigger a warning (with \f(CW-w\fR) to avoid misspelt tags
names being silently added to \f(CW@EXPORT\fR or \f(CW@EXPORT_OK\fR. Future versions
may make this a fatal error.

.rn }` ''
.IX Title "Exporter 3"
.IX Name "Exporter - Implements default import method for modules"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Subsection "Selecting What To Export"

.IX Subsection "Specialised Import Lists"

.IX Subsection "Exporting without using Export's import method"

.IX Subsection "Module Version Checking"

.IX Subsection "Managing Unknown Symbols"

.IX Subsection "Tag Handling Utility Functions"

