.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH ExtUtils::Manifest 3 "perl 5.004, patch 55" "25/Nov/97" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
ExtUtils::Manifest \- utilities to write and check a MANIFEST file
.SH "SYNOPSIS"
\f(CWrequire ExtUtils::Manifest;\fR
.PP
\f(CWExtUtils::Manifest::mkmanifest;\fR
.PP
\f(CWExtUtils::Manifest::manicheck;\fR
.PP
\f(CWExtUtils::Manifest::filecheck;\fR
.PP
\f(CWExtUtils::Manifest::fullcheck;\fR
.PP
\f(CWExtUtils::Manifest::skipcheck;\fR
.PP
\f(CWExtUtild::Manifest::manifind();\fR
.PP
\f(CWExtUtils::Manifest::maniread($file);\fR
.PP
\f(CWExtUtils::Manifest::manicopy($read,$target,$how);\fR
.SH "DESCRIPTION"
\fIMkmanifest()\fR writes all files in and below the current directory to a
file named in the global variable \f(CW$ExtUtils::Manifest::MANIFEST\fR (which
defaults to \f(CWMANIFEST\fR) in the current directory. It works similar to
.PP
.Vb 1
\&    find . -print
.Ve
but in doing so checks each line in an existing \f(CWMANIFEST\fR file and
includes any comments that are found in the existing \f(CWMANIFEST\fR file
in the new one. Anything between white space and an end of line within
a \f(CWMANIFEST\fR file is considered to be a comment. Filenames and
comments are seperated by one or more TAB characters in the
output. All files that match any regular expression in a file
\f(CWMANIFEST.SKIP\fR (if such a file exists) are ignored.
.PP
\fIManicheck()\fR checks if all the files within a \f(CWMANIFEST\fR in the
current directory really do exist. It only reports discrepancies and
exits silently if MANIFEST and the tree below the current directory
are in sync.
.PP
\fIFilecheck()\fR finds files below the current directory that are not
mentioned in the \f(CWMANIFEST\fR file. An optional file \f(CWMANIFEST.SKIP\fR
will be consulted. Any file matching a regular expression in such a
file will not be reported as missing in the \f(CWMANIFEST\fR file.
.PP
\fIFullcheck()\fR does both a \fImanicheck()\fR and a \fIfilecheck()\fR.
.PP
\fISkipcheck()\fR lists all the files that are skipped due to your
\f(CWMANIFEST.SKIP\fR file.
.PP
\fIManifind()\fR retruns a hash reference. The keys of the hash are the
files found below the current directory.
.PP
\fIManiread\fR\|($file) reads a named \f(CWMANIFEST\fR file (defaults to
\f(CWMANIFEST\fR in the current directory) and returns a HASH reference
with files being the keys and comments being the values of the HASH.
Blank lines and lines which start with \f(CW#\fR in the \f(CWMANIFEST\fR file
are discarded.
.PP
\fIManicopy($read,$target,$how)\fR copies the files that are the keys in
the HASH \fI%$read\fR to the named target directory. The HASH reference
\fI$read\fR is typically returned by the \fImaniread()\fR function. This
function is useful for producing a directory tree identical to the
intended distribution tree. The third parameter \f(CW$how\fR can be used to
specify a different methods of \*(L"copying\*(R". Valid values are \f(CWcp\fR,
which actually copies the files, \f(CWln\fR which creates hard links, and
\f(CWbest\fR which mostly links the files but copies any symbolic link to
make a tree without any symbolic link. Best is the default.
.SH "MANIFEST.SKIP"
The file MANIFEST.SKIP may contain regular expressions of files that
should be ignored by \fImkmanifest()\fR and \fIfilecheck()\fR. The regular
expressions should appear one on each line. Blank lines and lines
which start with \f(CW#\fR are skipped.  Use \f(CW\e#\fR if you need a regular
expression to start with a sharp character. A typical example:
.PP
.Vb 8
\&    \ebRCS\eb
\&    ^MANIFEST\e.
\&    ^Makefile$
\&    ~$
\&    \e.html$
\&    \e.old$
\&    ^blib/
\&    ^MakeMaker-\ed
.Ve
.SH "EXPORT_OK"
\f(CW&mkmanifest\fR, \f(CW&manicheck\fR, \f(CW&filecheck\fR, \f(CW&fullcheck\fR,
\f(CW&maniread\fR, and \f(CW&manicopy\fR are exportable.
.SH "GLOBAL VARIABLES"
\f(CW$ExtUtils::Manifest::MANIFEST\fR defaults to \f(CWMANIFEST\fR. Changing it
results in both a different \f(CWMANIFEST\fR and a different
\f(CWMANIFEST.SKIP\fR file. This is useful if you want to maintain
different distributions for different audiences (say a user version
and a developer version including RCS).
.PP
\f(CW$ExtUtils::Manifest::Quiet\fR defaults to 0. If set to a true value,
all functions act silently.
.SH "DIAGNOSTICS"
All diagnostic output is sent to \f(CWSTDERR\fR.
.Ip "\f(CWNot in MANIFEST:\fR \fIfile\fR" 5
is reported if a file is found, that is missing in the \f(CWMANIFEST\fR
file which is excluded by a regular expression in the file
\f(CWMANIFEST.SKIP\fR.
.Ip "\f(CWNo such file:\fR \fIfile\fR" 5
is reported if a file mentioned in a \f(CWMANIFEST\fR file does not
exist.
.Ip "\f(CWMANIFEST:\fR \fI$!\fR" 5
is reported if \f(CWMANIFEST\fR could not be opened.
.Ip "\f(CWAdded to MANIFEST:\fR \fIfile\fR" 5
is reported by \fImkmanifest()\fR if \f(CW$Verbose\fR is set and a file is added
to \s-1MANIFEST\s0. \f(CW$Verbose\fR is set to 1 by default.
.SH "SEE ALSO"
the \fIExtUtils::MakeMaker\fR manpage which has handy targets for most of the functionality.
.SH "AUTHOR"
Andreas Koenig <\fIkoenig@franz.ww.TU\-Berlin.DE\fR>

.rn }` ''
.IX Title "ExtUtils::Manifest 3"
.IX Name "ExtUtils::Manifest - utilities to write and check a MANIFEST file"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "MANIFEST.SKIP"

.IX Header "EXPORT_OK"

.IX Header "GLOBAL VARIABLES"

.IX Header "DIAGNOSTICS"

.IX Item "\f(CWNot in MANIFEST:\fR \fIfile\fR"

.IX Item "\f(CWNo such file:\fR \fIfile\fR"

.IX Item "\f(CWMANIFEST:\fR \fI$!\fR"

.IX Item "\f(CWAdded to MANIFEST:\fR \fIfile\fR"

.IX Header "SEE ALSO"

.IX Header "AUTHOR"

