.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH Getopt::Long 3 "perl 5.004, patch 55" "25/Nov/97" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
GetOptions \- extended processing of command line options
.SH "SYNOPSIS"
.PP
.Vb 2
\&  use Getopt::Long;
\&  $result = GetOptions (...option-descriptions...);
.Ve
.SH "DESCRIPTION"
The Getopt::Long module implements an extended getopt function called
\fIGetOptions()\fR. This function adheres to the POSIX syntax for command
line options, with GNU extensions. In general, this means that options
have long names instead of single letters, and are introduced with a
double dash \*(L"--\*(R". Support for bundling of command line options, as was
the case with the more traditional single-letter approach, is provided
but not enabled by default. For example, the UNIX \*(L"ps\*(R" command can be
given the command line \*(L"option\*(R"
.PP
.Vb 1
\&  -vax
.Ve
which means the combination of \fB\-v\fR, \fB\-a\fR and \fB\-x\fR. With the new
syntax \fB--vax\fR would be a single option, probably indicating a
computer architecture. 
.PP
Command line options can be used to set values. These values can be
specified in one of two ways:
.PP
.Vb 2
\&  --size 24
\&  --size=24
.Ve
GetOptions is called with a list of option-descriptions, each of which
consists of two elements: the option specifier and the option linkage.
The option specifier defines the name of the option and, optionally,
the value it can take. The option linkage is usually a reference to a
variable that will be set when the option is used. For example, the
following call to GetOptions:
.PP
.Vb 1
\&  GetOptions("size=i" => \e$offset);
.Ve
will accept a command line option \*(L"size\*(R" that must have an integer
value. With a command line of \*(L"\*(--size 24\*(R" this will cause the variable
\f(CW$offset\fR to get the value 24.
.PP
Alternatively, the first argument to GetOptions may be a reference to
a HASH describing the linkage for the options, or an object whose
class is based on a HASH. The following call is equivalent to the
example above:
.PP
.Vb 2
\&  %optctl = ("size" => \e$offset);
\&  GetOptions(\e%optctl, "size=i");
.Ve
Linkage may be specified using either of the above methods, or both.
Linkage specified in the argument list takes precedence over the
linkage specified in the HASH.
.PP
The command line options are taken from array \f(CW@ARGV\fR. Upon completion
of GetOptions, \f(CW@ARGV\fR will contain the rest (i.e. the non-options) of
the command line.
 
Each option specifier designates the name of the option, optionally
followed by an argument specifier. Values for argument specifiers are:
.Ip "<none>" 8
Option does not take an argument. 
The option variable will be set to 1.
.Ip "!" 8
Option does not take an argument and may be negated, i.e. prefixed by
\*(L"no\*(R". E.g. \*(L"foo!\*(R" will allow \fB--foo\fR (with value 1) and \fB\-nofoo\fR
(with value 0).
The option variable will be set to 1, or 0 if negated.
.Ip "=s" 8
Option takes a mandatory string argument.
This string will be assigned to the option variable.
Note that even if the string argument starts with \fB\-\fR or \fB--\fR, it
will not be considered an option on itself.
.Ip ":s" 8
Option takes an optional string argument.
This string will be assigned to the option variable.
If omitted, it will be assigned "" (an empty string).
If the string argument starts with \fB\-\fR or \fB--\fR, it
will be considered an option on itself.
.Ip "=i" 8
Option takes a mandatory integer argument.
This value will be assigned to the option variable.
Note that the value may start with \fB\-\fR to indicate a negative
value. 
.Ip ":i" 8
Option takes an optional integer argument.
This value will be assigned to the option variable.
If omitted, the value 0 will be assigned.
Note that the value may start with \fB\-\fR to indicate a negative
value.
.Ip "=f" 8
Option takes a mandatory real number argument.
This value will be assigned to the option variable.
Note that the value may start with \fB\-\fR to indicate a negative
value.
.Ip ":f" 8
Option takes an optional real number argument.
This value will be assigned to the option variable.
If omitted, the value 0 will be assigned.
.PP
A lone dash \fB\-\fR is considered an option, the corresponding option
name is the empty string.
.PP
A double dash on itself \fB--\fR signals end of the options list.
.Sh "Linkage specification"
The linkage specifier is optional. If no linkage is explicitly
specified but a ref \s-1HASH\s0 is passed, GetOptions will place the value in
the \s-1HASH\s0. For example:
.PP
.Vb 2
\&  %optctl = ();
\&  GetOptions (\e%optctl, "size=i");
.Ve
will perform the equivalent of the assignment
.PP
.Vb 1
\&  $optctl{"size"} = 24;
.Ve
For array options, a reference to an array is used, e.g.:
.PP
.Vb 2
\&  %optctl = ();
\&  GetOptions (\e%optctl, "sizes=i@");
.Ve
with command line \*(L"\-sizes 24 \-sizes 48\*(R" will perform the equivalent of
the assignment
.PP
.Vb 1
\&  $optctl{"sizes"} = [24, 48];
.Ve
For hash options (an option whose argument looks like \*(L"name=value"),
a reference to a hash is used, e.g.:
.PP
.Vb 2
\&  %optctl = ();
\&  GetOptions (\e%optctl, "define=s%");
.Ve
with command line \*(L"\*(--define foo=hello --define bar=world\*(R" will perform the
equivalent of the assignment
.PP
.Vb 1
\&  $optctl{"define"} = {foo=>'hello', bar=>'world')
.Ve
If no linkage is explicitly specified and no ref \s-1HASH\s0 is passed,
GetOptions will put the value in a global variable named after the
option, prefixed by \*(L"opt_\*(R". To yield a usable Perl variable,
characters that are not part of the syntax for variables are
translated to underscores. For example, \*(L"\*(--fpp-struct-return\*(R" will set
the variable \f(CW$opt_fpp_struct_return\fR. Note that this variable resides
in the namespace of the calling program, not necessarily \fBmain\fR.
For example:
.PP
.Vb 1
\&  GetOptions ("size=i", "sizes=i@");
.Ve
with command line \*(L"\-size 10 \-sizes 24 \-sizes 48\*(R" will perform the
equivalent of the assignments
.PP
.Vb 2
\&  $opt_size = 10;
\&  @opt_sizes = (24, 48);
.Ve
A lone dash \fB\-\fR is considered an option, the corresponding Perl
identifier is \f(CW$opt_\fR .
.PP
The linkage specifier can be a reference to a scalar, a reference to
an array, a reference to a hash or a reference to a subroutine.
.PP
If a \s-1REF\s0 \s-1SCALAR\s0 is supplied, the new value is stored in the referenced
variable. If the option occurs more than once, the previous value is
overwritten. 
.PP
If a \s-1REF\s0 \s-1ARRAY\s0 is supplied, the new value is appended (pushed) to the
referenced array. 
.PP
If a \s-1REF\s0 \s-1HASH\s0 is supplied, the option value should look like \*(L"key\*(R" or
\*(L"key=value\*(R" (if the \*(L"=value\*(R" is omitted then a value of 1 is implied).
In this case, the element of the referenced hash with the key \*(L"key\*(R"
is assigned \*(L"value\*(R". 
.PP
If a \s-1REF\s0 \s-1CODE\s0 is supplied, the referenced subroutine is called with
two arguments: the option name and the option value.
The option name is always the true name, not an abbreviation or alias.
.Sh "Aliases and abbreviations"
The option name may actually be a list of option names, separated by
\*(L"|"s, e.g. \*(L"foo|bar|blech=s\*(R". In this example, \*(L"foo\*(R" is the true name
of this option. If no linkage is specified, options \*(L"foo\*(R", \*(L"bar\*(R" and
\*(L"blech\*(R" all will set \f(CW$opt_foo\fR.
.PP
Option names may be abbreviated to uniqueness, depending on
configuration option \fBauto_abbrev\fR.
.Sh "Non-option call-back routine"
A special option specifier, <>, can be used to designate a subroutine
to handle non-option arguments. GetOptions will immediately call this
subroutine for every non-option it encounters in the options list.
This subroutine gets the name of the non-option passed.
This feature requires configuration option \fBpermute\fR, see section
\s-1CONFIGURATION\s0 \s-1OPTIONS\s0.
.PP
See also the examples.
.Sh "Option starters"
On the command line, options can start with \fB\-\fR (traditional), \fB--\fR
(\s-1POSIX\s0) and \fB+\fR (\s-1GNU\s0, now being phased out). The latter is not
allowed if the environment variable \fB\s-1POSIXLY_CORRECT\s0\fR has been
defined.
.PP
Options that start with \*(L"--\*(R" may have an argument appended, separated
with an \*(L"=\*(R", e.g. \*(L"\*(--foo=bar\*(R".
.Sh "Return value"
A return status of 0 (false) indicates that the function detected
one or more errors.
.SH "COMPATIBILITY"
\fIGetopt::Long::GetOptions()\fR is the successor of
\fBnewgetopt.pl\fR that came with Perl 4. It is fully upward compatible.
In fact, the Perl 5 version of newgetopt.pl is just a wrapper around
the module.
.PP
If an \*(L"@\*(R" sign is appended to the argument specifier, the option is
treated as an array. \fIValue\fR\|(s) are not set, but pushed into array
\f(CW@opt_name\fR. If explicit linkage is supplied, this must be a reference
to an ARRAY.
.PP
If an \*(L"%\*(R" sign is appended to the argument specifier, the option is
treated as a hash. \fIValue\fR\|(s) of the form \*(L"name=value\*(R" are set by
setting the element of the hash \f(CW%opt_name\fR with key \*(L"name\*(R" to \*(L"value\*(R"
(if the \*(L"=value\*(R" portion is omitted it defaults to 1). If explicit
linkage is supplied, this must be a reference to a HASH.
.PP
If configuration option \fBgetopt_compat\fR is set (see section
CONFIGURATION OPTIONS), options that start with \*(L"+\*(R" or \*(L"\-\*(R" may also
include their arguments, e.g. \*(L"+foo=bar\*(R". This is for compatiblity
with older implementations of the GNU \*(L"getopt\*(R" routine.
.PP
If the first argument to GetOptions is a string consisting of only
non-alphanumeric characters, it is taken to specify the option starter
characters. Everything starting with one of these characters from the
starter will be considered an option. \fBUsing a starter argument is
strongly deprecated.\fR
.PP
For convenience, option specifiers may have a leading \fB\-\fR or \fB--\fR,
so it is possible to write:
.PP
.Vb 1
\&   GetOptions qw(-foo=s --bar=i --ar=s);
.Ve
.SH "EXAMPLES"
If the option specifier is \*(L"one:i\*(R" (i.e. takes an optional integer
argument), then the following situations are handled:
.PP
.Vb 2
\&   -one -two            -> $opt_one = '', -two is next option
\&   -one -2              -> $opt_one = -2
.Ve
Also, assume specifiers \*(L"foo=s\*(R" and \*(L"bar:s\*(R" :
.PP
.Vb 3
\&   -bar -xxx            -> $opt_bar = '', '-xxx' is next option
\&   -foo -bar            -> $opt_foo = '-bar'
\&   -foo --              -> $opt_foo = '--'
.Ve
In GNU or POSIX format, option names and values can be combined:
.PP
.Vb 3
\&   +foo=blech           -> $opt_foo = 'blech'
\&   --bar=               -> $opt_bar = ''
\&   --bar=--             -> $opt_bar = '--'
.Ve
Example of using variable references:
.PP
.Vb 1
\&   $ret = GetOptions ('foo=s', \e$foo, 'bar=i', 'ar=s', \e@ar);
.Ve
With command line options \*(L"\-foo blech \-bar 24 \-ar xx \-ar yy\*(R" 
this will result in:
.PP
.Vb 3
\&   $foo = 'blech'
\&   $opt_bar = 24
\&   @ar = ('xx','yy')
.Ve
Example of using the <> option specifier:
.PP
.Vb 2
\&   @ARGV = qw(-foo 1 bar -foo 2 blech);
\&   GetOptions("foo=i", \e$myfoo, "<>", \e&mysub);
.Ve
Results:
.PP
.Vb 2
\&   mysub("bar") will be called (with $myfoo being 1)
\&   mysub("blech") will be called (with $myfoo being 2)
.Ve
Compare this with:
.PP
.Vb 2
\&   @ARGV = qw(-foo 1 bar -foo 2 blech);
\&   GetOptions("foo=i", \e$myfoo);
.Ve
This will leave the non-options in \f(CW@ARGV:\fR
.PP
.Vb 2
\&   $myfoo -> 2
\&   @ARGV -> qw(bar blech)
.Ve
.SH "CONFIGURATION OPTIONS"
\fBGetOptions\fR can be configured by calling subroutine
\fBGetopt::Long::config\fR. This subroutine takes a list of quoted
strings, each specifying a configuration option to be set, e.g.
\fBignore_case\fR. Options can be reset by prefixing with \fBno_\fR, e.g.
\fBno_ignore_case\fR. Case does not matter. Multiple calls to \fBconfig\fR
are possible.
.PP
Previous versions of Getopt::Long used variables for the purpose of
configuring. Although manipulating these variables still work, it
is strongly encouraged to use the new \fBconfig\fR routine. Besides, it
is much easier.
.PP
The following options are available:
.Ip "default" 12
This option causes all configuration options to be reset to their
default values.
.Ip "auto_abbrev" 12
Allow option names to be abbreviated to uniqueness.
Default is set unless environment variable
\s-1POSIXLY_CORRECT\s0 has been set, in which case \fBauto_abbrev\fR is reset.
.Ip "getopt_compat   " 12
Allow \*(L'+\*(R' to start options.
Default is set unless environment variable
\s-1POSIXLY_CORRECT\s0 has been set, in which case \fBgetopt_compat\fR is reset.
.Ip "require_order" 12
Whether non-options are allowed to be mixed with
options.
Default is set unless environment variable
\s-1POSIXLY_CORRECT\s0 has been set, in which case b<require_order> is reset.
.Sp
See also \fBpermute\fR, which is the opposite of \fBrequire_order\fR.
.Ip "permute" 12
Whether non-options are allowed to be mixed with
options.
Default is set unless environment variable
\s-1POSIXLY_CORRECT\s0 has been set, in which case \fBpermute\fR is reset.
Note that \fBpermute\fR is the opposite of \fBrequire_order\fR.
.Sp
If \fBpermute\fR is set, this means that 
.Sp
.Vb 1
\&    -foo arg1 -bar arg2 arg3
.Ve
is equivalent to
.Sp
.Vb 1
\&    -foo -bar arg1 arg2 arg3
.Ve
If a non-option call-back routine is specified, \f(CW@ARGV\fR will always be
empty upon succesful return of GetOptions since all options have been
processed, except when \fB--\fR is used:
.Sp
.Vb 1
\&    -foo arg1 -bar arg2 -- arg3
.Ve
will call the call-back routine for arg1 and arg2, and terminate
leaving arg2 in \f(CW@ARGV\fR.
.Sp
If \fBrequire_order\fR is set, options processing
terminates when the first non-option is encountered.
.Sp
.Vb 1
\&    -foo arg1 -bar arg2 arg3
.Ve
is equivalent to
.Sp
.Vb 1
\&    -foo -- arg1 -bar arg2 arg3
.Ve
.Ip "bundling (default: reset)" 12
Setting this variable to a non-zero value will allow single-character
options to be bundled. To distinguish bundles from long option names,
long options must be introduced with \fB--\fR and single-character
options (and bundles) with \fB\-\fR. For example,
.Sp
.Vb 1
\&    ps -vax --vax
.Ve
would be equivalent to
.Sp
.Vb 1
\&    ps -v -a -x --vax
.Ve
provided \*(L"vax\*(R", \*(L"v\*(R", \*(L"a\*(R" and \*(L"x\*(R" have been defined to be valid
options. 
.Sp
Bundled options can also include a value in the bundle; this value has
to be the last part of the bundle, e.g.
.Sp
.Vb 1
\&    scale -h24 -w80
.Ve
is equivalent to
.Sp
.Vb 1
\&    scale -h 24 -w 80
.Ve
Note: resetting \fBbundling\fR also resets \fBbundling_override\fR.
.Ip "bundling_override (default: reset)" 12
If \fBbundling_override\fR is set, bundling is enabled as with
\fBbundling\fR but now long option names override option bundles. In the
above example, \fB\-vax\fR would be interpreted as the option \*(L"vax\*(R", not
the bundle \*(L"v\*(R", \*(L"a\*(R", \*(L"x\*(R".
.Sp
Note: resetting \fBbundling_override\fR also resets \fBbundling\fR.
.Sp
\fBNote:\fR Using option bundling can easily lead to unexpected results,
especially when mixing long options and bundles. Caveat emptor.
.Ip "ignore_case  (default: set)" 12
If set, case is ignored when matching options.
.Sp
Note: resetting \fBignore_case\fR also resets \fBignore_case_always\fR.
.Ip "ignore_case_always (default: reset)" 12
When bundling is in effect, case is ignored on single-character
options also. 
.Sp
Note: resetting \fBignore_case_always\fR also resets \fBignore_case\fR.
.Ip "pass_through (default: reset)" 12
Unknown options are passed through in \f(CW@ARGV\fR instead of being flagged
as errors. This makes it possible to write wrapper scripts that
process only part of the user supplied options, and passes the
remaining options to some other program.
.Sp
This can be very confusing, especially when \fBpermute\fR is also set.
.Ip "debug (default: reset)" 12
Enable copious debugging output.
.SH "OTHER USEFUL VARIABLES"
.Ip "$Getopt::Long::\s-1VERSION\s0" 12
The version number of this Getopt::Long implementation in the format
\f(CWmajor\fR.\f(CWminor\fR. This can be used to have Exporter check the
version, e.g.
.Sp
.Vb 1
\&    use Getopt::Long 3.00;
.Ve
You can inspect \f(CW$Getopt::Long::major_version\fR and
\f(CW$Getopt::Long::minor_version\fR for the individual components.
.Ip "$Getopt::Long::error" 12
Internal error flag. May be incremented from a call-back routine to
cause options parsing to fail.

.rn }` ''
.IX Title "Getopt::Long 3"
.IX Name "GetOptions - extended processing of command line options"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Item "<none>"

.IX Item "!"

.IX Item "=s"

.IX Item ":s"

.IX Item "=i"

.IX Item ":i"

.IX Item "=f"

.IX Item ":f"

.IX Subsection "Linkage specification"

.IX Subsection "Aliases and abbreviations"

.IX Subsection "Non-option call-back routine"

.IX Subsection "Option starters"

.IX Subsection "Return value"

.IX Header "COMPATIBILITY"

.IX Header "EXAMPLES"

.IX Header "CONFIGURATION OPTIONS"

.IX Item "default"

.IX Item "auto_abbrev"

.IX Item "getopt_compat   "

.IX Item "require_order"

.IX Item "permute"

.IX Item "bundling (default: reset)"

.IX Item "bundling_override (default: reset)"

.IX Item "ignore_case  (default: set)"

.IX Item "ignore_case_always (default: reset)"

.IX Item "pass_through (default: reset)"

.IX Item "debug (default: reset)"

.IX Header "OTHER USEFUL VARIABLES"

.IX Item "$Getopt::Long::\s-1VERSION\s0"

.IX Item "$Getopt::Long::error"

