.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH lib::HTTP::Headers 3 "perl 5.004, patch 55" "16/Sep/96" "User Contributed Perl Documentation"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
HTTP::Headers \- Class encapsulating HTTP Message headers
.SH "SYNOPSIS"
.PP
.Vb 2
\& require HTTP::Headers;
\& $request = new HTTP::Headers;
.Ve
.SH "DESCRIPTION"
The \f(CWHTTP::Headers\fR class encapsulates HTTP\-style message headers.
The headers consist of attribute-value pairs, which may be repeated,
and which are printed in a particular order.
.PP
Instances of this class are usually created as member variables of the
\f(CWHTTP::Request\fR and \f(CWHTTP::Response\fR classes, internal to the
library.
.SH "METHODS"
.Sh "\f(CW$h\fR = new \s-1HTTP::\s0Headers"
Constructs a new \f(CWHTTP::Headers\fR object.  You might pass some initial
attribute-value pairs as parameters to the constructor.  \fIE.g.\fR:
.PP
.Vb 4
\& $h = new HTTP::Headers
\&     Date         => 'Thu, 03 Feb 1994 00:00:00 GMT',
\&     Content_Type => 'text/html; version=3.2',
\&     Content_Base => 'http://www.sn.no/';
.Ve
.Sh "\f(CW$h\fR\->\fIheader\fR\|($field [=> \f(CW$val\fR],...)"
Get or set the value of a header.  The header field name is not case
sensitive.  To make the life easier for perl users who wants to avoid
quoting before the => operator, you can use \*(L'_\*(R' as a synonym for \*(L'\-\*(R'
in header names.
.PP
The value argument may be a scalar or a reference to a list of
scalars. If the value argument is not defined, then the header is not
modified.
.PP
The \fIheader()\fR method accepts multiple ($field => \f(CW$value\fR) pairs.
.PP
The list of previous values for the last \f(CW$field\fR is returned.  Only the
first header value is returned in scalar context.
.PP
.Vb 5
\& $header->header(MIME_Version => '1.0',
\&                 User_Agent   => 'My-Web-Client/0.01');
\& $header->header(Accept => "text/html, text/plain, image/*");
\& $header->header(Accept => [qw(text/html text/plain image/*)]);
\& @accepts = $header->header('Accept');
.Ve
.Sh "\f(CW$h\fR\->\fIscan\fR\|(\e&doit)"
Apply a subroutine to each header in turn.  The callback routine is
called with two parameters; the name of the field and a single value.
If the header has more than one value, then the routine is called once
for each value.  The field name passed to the callback routine has
case as suggested by \s-1HTTP\s0 Spec, and the headers will be visited in the
recommended \*(L"Good Practice\*(R" order.
.Sh "\f(CW$h\fR\->\fIas_string\fR\|([$endl])"
Return the header fields as a formatted \s-1MIME\s0 header.  Since it
internally uses the \f(CWscan()\fR method to build the string, the result
will use case as suggested by \s-1HTTP\s0 Spec, and it will follow
recommended \*(L"Good Practice\*(R" of ordering the header fieds.  Long header
values are not folded. 
.PP
The optional parameter specifies the line ending sequence to use.  The
default is \f(CW"\en"\fR.  Embedded \*(L"\en\*(R" characters in the header will be
substitued with this line ending sequence.
.Sh "\f(CW$h\fR\->\fIpush_header\fR\|($field, \f(CW$val\fR)"
Add a new field value of the specified header.  The header field name
is not case sensitive.  The field need not already have a
value. Previous values for the same field are retained.  The argument
may be a scalar or a reference to a list of scalars.
.PP
.Vb 1
\& $header->push_header(Accept => 'image/jpeg');
.Ve
.Sh "\f(CW$h\fR\->\fIremove_header\fR\|($field,...)"
This function removes the headers with the specified names.
.Sh "\f(CW$h\fR\->clone"
Returns a copy of this \s-1HTTP::\s0Headers object.
.SH "CONVENIENCE METHODS"
The most frequently used headers can also be accessed through the
following convenience methods.  These methods can both be used to read
and to set the value of a header.  The header value is set if you pass
an argument to the method.  The old header value is always returned.
.PP
Methods that deal with dates/times always convert their value to system
time (seconds since Jan 1, 1970) and they also expect this kind of
value when the header value is set.
.Sh "\f(CW$h\fR\->date"
This header represents the date and time at which the message was
originated. \fIE.g.\fR:
.PP
.Vb 1
\&  $h->date(time);  # set current date
.Ve
.Sh "\f(CW$h\fR\->expires"
This header gives the date and time after which the entity should be
considered stale.
.Sh "\f(CW$h\fR\->if_modified_since"
This header is used to make a request conditional.  If the requested
resource has not been modified since the time specified in this field,
then the server will return a \f(CW"304 Not Modified"\fR response instead of
the document itself.
.Sh "\f(CW$h\fR\->last_modified"
This header indicates the date and time at which the resource was last
modified. \fIE.g.\fR:
.PP
.Vb 4
\&  # check if document is more than 1 hour old
\&  if ($h->last_modified < time - 60*60) {
\&        ...
\&  }
.Ve
.Sh "\f(CW$h\fR\->content_type"
The Content-Type header field indicates the media type of the message
content. \fIE.g.\fR:
.PP
.Vb 1
\&  $h->content_type('text/html');
.Ve
The value returned will be converted to lower case, and potential
parameters will be chopped off and returned as a separate value if in
an array context.  This makes it safe to do the following:
.PP
.Vb 5
\&  if ($h->content_type eq 'text/html') {
\&     # we enter this place even if the real header value happens to
\&     # be 'TEXT/HTML; version=3.0'
\&     ...
\&  }
.Ve
.Sh "\f(CW$h\fR\->content_encoding"
The Content-Encoding header field is used as a modifier to the
media type.  When present, its value indicates what additional
encoding mechanism has been applied to the resource.
.Sh "\f(CW$h\fR\->content_length"
A decimal number indicating the size in bytes of the message content.
.Sh "\f(CW$h\fR\->title"
The title of the document.  In libwww-perl this header will be
initialized automatically from the <\s-1TITLE\s0>...</\s-1TITLE\s0> element
of \s-1HTML\s0 documents.  \fIThis header is no longer part of the \s-1HTTP\s0
standard.\fR
.Sh "\f(CW$h\fR\->user_agent"
This header field is used in request messages and contains information
about the user agent originating the request.  \fIE.g.\fR:
.PP
.Vb 1
\&  $h->user_agent('Mozilla/1.2');
.Ve
.Sh "\f(CW$h\fR\->server"
The server header field contains information about the software being
used by the originating server program handling the request.
.Sh "\f(CW$h\fR\->from"
This header should contain an Internet e-mail address for the human
user who controls the requesting user agent.  The address should be
machine-usable, as defined by \s-1RFC822\s0.  E.g.:
.PP
.Vb 1
\&  $h->from('Gisle Aas <aas@sn.no>');
.Ve
.Sh "\f(CW$h\fR\->referer"
Used to specify the address (\s-1URI\s0) of the document from which the
requested resouce address was obtained.
.Sh "\f(CW$h\fR\->www_authenticate"
This header must be included as part of a \*(L"401 Unauthorized\*(R" response.
The field value consist of a challenge that indicates the
authentication scheme and parameters applicable to the requested \s-1URI\s0.
.Sh "\f(CW$h\fR\->authorization"
A user agent that wishes to authenticate itself with a server, may do
so by including this header.
.Sh "\f(CW$h\fR\->authorization_basic"
This method is used to get or set an authorization header that use the
\*(L"Basic Authentication Scheme\*(R".  In array context it will return two
values; the user name and the password.  In scalar context it will
return \fI"uname:password\*(R"\fR as a single string value.
.PP
When used to set the header value, it expects two arguments.  \fIE.g.\fR:
.PP
.Vb 1
\&  $h->authorization_basic($uname, $password);
.Ve

.rn }` ''
.IX Title "lib::HTTP::Headers 3"
.IX Name "HTTP::Headers - Class encapsulating HTTP Message headers"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "METHODS"

.IX Subsection "\f(CW$h\fR = new \s-1HTTP::\s0Headers"

.IX Subsection "\f(CW$h\fR\->\fIheader\fR\|($field [=> \f(CW$val\fR],...)"

.IX Subsection "\f(CW$h\fR\->\fIscan\fR\|(\e&doit)"

.IX Subsection "\f(CW$h\fR\->\fIas_string\fR\|([$endl])"

.IX Subsection "\f(CW$h\fR\->\fIpush_header\fR\|($field, \f(CW$val\fR)"

.IX Subsection "\f(CW$h\fR\->\fIremove_header\fR\|($field,...)"

.IX Subsection "\f(CW$h\fR\->clone"

.IX Header "CONVENIENCE METHODS"

.IX Subsection "\f(CW$h\fR\->date"

.IX Subsection "\f(CW$h\fR\->expires"

.IX Subsection "\f(CW$h\fR\->if_modified_since"

.IX Subsection "\f(CW$h\fR\->last_modified"

.IX Subsection "\f(CW$h\fR\->content_type"

.IX Subsection "\f(CW$h\fR\->content_encoding"

.IX Subsection "\f(CW$h\fR\->content_length"

.IX Subsection "\f(CW$h\fR\->title"

.IX Subsection "\f(CW$h\fR\->user_agent"

.IX Subsection "\f(CW$h\fR\->server"

.IX Subsection "\f(CW$h\fR\->from"

.IX Subsection "\f(CW$h\fR\->referer"

.IX Subsection "\f(CW$h\fR\->www_authenticate"

.IX Subsection "\f(CW$h\fR\->authorization"

.IX Subsection "\f(CW$h\fR\->authorization_basic"

