.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH Net::NNTP 3 "perl 5.005, patch 53" "30/Nov/97" "User Contributed Perl Documentation"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
Net::NNTP \- NNTP Client class
.SH "SYNOPSIS"
.PP
.Vb 4
\&    use Net::NNTP;
\&    
\&    $nntp = Net::NNTP->new("some.host.name");
\&    $nntp->quit;
.Ve
.SH "DESCRIPTION"
\f(CWNet::NNTP\fR is a class implementing a simple NNTP client in Perl as described
in RFC977. \f(CWNet::NNTP\fR inherits its communication methods from \f(CWNet::Cmd\fR
.SH "CONSTRUCTOR"
.Ip "new ( [ \s-1HOST\s0 ] [, \s-1OPTIONS\s0 ])" 4
This is the constructor for a new Net::\s-1NNTP\s0 object. \f(CWHOST\fR is the
name of the remote host to which a \s-1NNTP\s0 connection is required. If not
given two environment variables are checked, first \f(CWNNTPSERVER\fR then
\f(CWNEWSHOST\fR, then \f(CWNet::Config\fR is checked, and if a host is not found
then \f(CWnews\fR is used.
.Sp
\f(CWOPTIONS\fR are passed in a hash like fashion, using key and value pairs.
Possible options are:
.Sp
\fBTimeout\fR \- Maximum time, in seconds, to wait for a response from the
\s-1NNTP\s0 server, a value of zero will cause all \s-1IO\s0 operations to block.
(default: 120)
.Sp
\fBDebug\fR \- Enable the printing of debugging information to \s-1STDERR\s0
.SH "METHODS"
Unless otherwise stated all methods return either a \fItrue\fR or \fIfalse\fR
value, with \fItrue\fR meaning that the operation was a success. When a method
states that it returns a value, failure will be returned as \fIundef\fR or an
empty list.
.Ip "article ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )" 4
Retrieve the header, a blank line, then the body (text) of the
specified article. 
.Sp
If no arguments are passed then the current article in the current
newsgroup is returned.
.Sp
\f(CWMSGNUM\fR is a numeric id of an article in the
current newsgroup, and will change the current article pointer.
\f(CWMSGID\fR is the message id of an article as
shown in that article's header.  It is anticipated that the client
will obtain the \f(CWMSGID\fR from a list provided by the \f(CWnewnews\fR
command, from references contained within another article, or from
the message-id provided in the response to some other commands.
.Sp
Returns a reference to an array containing the article.
.Ip "body ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )" 4
Retrieve the body (text) of the specified article. 
.Sp
Takes the same arguments as \f(CWarticle\fR
.Sp
Returns a reference to an array containing the body of the article.
.Ip "head ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )" 4
Retrieve the header of the specified article. 
.Sp
Takes the same arguments as \f(CWarticle\fR
.Sp
Returns a reference to an array containing the header of the article.
.Ip "nntpstat ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )" 4
The \f(CWnntpstat\fR command is similar to the \f(CWarticle\fR command except that no
text is returned.  When selecting by message number within a group,
the \f(CWnntpstat\fR command serves to set the \*(L"current article pointer\*(R" without
sending text.
.Sp
Using the \f(CWnntpstat\fR command to
select by message-id is valid but of questionable value, since a
selection by message-id does \fBnot\fR alter the \*(L"current article pointer\*(R".
.Sp
Returns the message-id of the \*(L"current article\*(R".
.Ip "group ( [ \s-1GROUP\s0 ] )" 4
Set and/or get the current group. If \f(CWGROUP\fR is not given then information
is returned on the current group.
.Sp
In a scalar context it returns the group name.
.Sp
In an array context the return value is a list containing, the number
of articles in the group, the number of the first article, the number
of the last article and the group name.
.Ip "ihave ( \s-1MSGID\s0 [, \s-1MESSAGE\s0 ])" 4
The \f(CWihave\fR command informs the server that the client has an article
whose id is \f(CWMSGID\fR.  If the server desires a copy of that
article, and \f(CWMESSAGE\fR has been given the it will be sent.
.Sp
Returns \fItrue\fR if the server desires the article and \f(CWMESSAGE\fR was
successfully sent,if specified.
.Sp
If \f(CWMESSAGE\fR is not specified then the message must be sent using the
\f(CWdatasend\fR and \f(CWdataend\fR methods from the \fINet::Cmd\fR manpage
.Sp
\f(CWMESSAGE\fR can be either an array of lines or a reference to an array.
.Ip "last ()" 4
Set the \*(L"current article pointer\*(R" to the previous article in the current
newsgroup.
.Sp
Returns the message-id of the article.
.Ip "date ()" 4
Returns the date on the remote server. This date will be in a \s-1UNIX\s0 time
format (seconds since 1970)
.Ip "postok ()" 4
\f(CWpostok\fR will return \fItrue\fR if the servers initial response indicated
that it will allow posting.
.Ip "authinfo ( \s-1USER\s0, \s-1PASS\s0 )" 4
.Ip "list ()" 4
Obtain information about all the active newsgroups. The results is a reference
to a hash where the key is a group name and each value is a reference to an
array. The elements in this array are:\- the first article number in the group,
the last article number in the group and any information flags about the group.
.Ip "newgroups ( \s-1SINCE\s0 [, \s-1DISTRIBUTIONS\s0 ])" 4
\f(CWSINCE\fR is a time value and \f(CWDISTRIBUTIONS\fR is either a distribution
pattern or a reference to a list of distribution patterns.
The result is the same as \f(CWlist\fR, but the
groups return will be limited to those created after \f(CWSINCE\fR and, if
specified, in one of the distribution areas in \f(CWDISTRIBUTIONS\fR. 
.Ip "newnews ( \s-1SINCE\s0 [, \s-1GROUPS\s0 [, \s-1DISTRIBUTIONS\s0 ]])" 4
\f(CWSINCE\fR is a time value. \f(CWGROUPS\fR is either a group pattern or a reference
to a list of group patterns. \f(CWDISTRIBUTIONS\fR is either a distribution
pattern or a reference to a list of distribution patterns.
.Sp
Returns a reference to a list which contains the message-ids of all news posted
after \f(CWSINCE\fR, that are in a groups which matched \f(CWGROUPS\fR and a
distribution which matches \f(CWDISTRIBUTIONS\fR.
.Ip "next ()" 4
Set the \*(L"current article pointer\*(R" to the next article in the current
newsgroup.
.Sp
Returns the message-id of the article.
.Ip "post ( [ \s-1MESSAGE\s0 ] )" 4
Post a new article to the news server. If \f(CWMESSAGE\fR is specified and posting
is allowed then the message will be sent.
.Sp
If \f(CWMESSAGE\fR is not specified then the message must be sent using the
\f(CWdatasend\fR and \f(CWdataend\fR methods from the \fINet::Cmd\fR manpage
.Sp
\f(CWMESSAGE\fR can be either an array of lines or a reference to an array.
.Ip "slave ()" 4
Tell the remote server that I am not a user client, but probably another
news server.
.Ip "quit ()" 4
Quit the remote server and close the socket connection.
.Sh "Extension methods"
These methods use commands that are not part of the \s-1RFC977\s0 documentation. Some
servers may not support all of them.
.Ip "newsgroups ( [ \s-1PATTERN\s0 ] )" 4
Returns a reference to a hash where the keys are all the group names which
match \f(CWPATTERN\fR, or all of the groups if no pattern is specified, and
each value contains the description text for the group.
.Ip "distributions ()" 4
Returns a reference to a hash where the keys are all the possible
distribution names and the values are the distribution descriptions.
.Ip "subscriptions ()" 4
Returns a reference to a list which contains a list of groups which
are recommended for a new user to subscribe to.
.Ip "overview_fmt ()" 4
Returns a reference to an array which contain the names of the fields returned
by \f(CWxover\fR.
.Ip "active_times ()" 4
Returns a reference to a hash where the keys are the group names and each
value is a reference to an array containing the time the groups was created
and an identifier, possibly an Email address, of the creator.
.Ip "active ( [ \s-1PATTERN\s0 ] )" 4
Similar to \f(CWlist\fR but only active groups that match the pattern are returned.
\f(CWPATTERN\fR can be a group pattern.
.Ip "xgtitle ( \s-1PATTERN\s0 )" 4
Returns a reference to a hash where the keys are all the group names which
match \f(CWPATTERN\fR and each value is the description text for the group.
.Ip "xhdr ( \s-1HEADER\s0, \s-1MESSAGE\s0\-\s-1SPEC\s0 )" 4
Obtain the header field \f(CWHEADER\fR for all the messages specified. 
.Sp
The return value will be a reference
to a hash where the keys are the message numbers and each value contains
the text of the requested header for that message.
.Ip "xover ( \s-1MESSAGE\s0\-\s-1SPEC\s0 )" 4
The return value will be a reference
to a hash where the keys are the message numbers and each value contains
a reference to an array which contains the overview fields for that
message.
.Sp
The names of the fields can be obtained by calling \f(CWoverview_fmt\fR.
.Ip "xpath ( \s-1MESSAGE\s0\-\s-1ID\s0 )" 4
Returns the path name to the file on the server which contains the specified
message.
.Ip "xpat ( \s-1HEADER\s0, \s-1PATTERN\s0, \s-1MESSAGE\s0\-\s-1SPEC\s0)" 4
The result is the same as \f(CWxhdr\fR except the is will be restricted to
headers where the text of the header matches \f(CWPATTERN\fR
.Ip "xrover" 4
The \s-1XROVER\s0 command returns reference information for the \fIarticle\fR\|(s)
specified.
.Sp
Returns a reference to a \s-1HASH\s0 where the keys are the message numbers and the
values are the References: lines from the articles
.Ip "listgroup ( [ \s-1GROUP\s0 ] )" 4
Returns a reference to a list of all the active messages in \f(CWGROUP\fR, or
the current group if \f(CWGROUP\fR is not specified.
.Ip "reader" 4
Tell the server that you are a reader and not another server.
.Sp
This is required by some servers. For example if you are connecting to
an \s-1INN\s0 server and you have transfer permission your connection will
be connected to the transfer daemon, not the \s-1NNTP\s0 daemon. Issuing
this command will cause the transfer daemon to hand over control
to the \s-1NNTP\s0 daemon.
.Sp
Some servers do not understand this command, but issuing it and ignoring
the response is harmless.
.SH "UNSUPPORTED"
The following NNTP command are unsupported by the package, and there are
no plans to do so.
.PP
.Vb 4
\&    AUTHINFO GENERIC
\&    XTHREAD
\&    XSEARCH
\&    XINDEX
.Ve
.SH "DEFINITIONS"
.Ip "\s-1MESSAGE\s0\-\s-1SPEC\s0" 4
\f(CWMESSAGE-SPEC\fR is either a single message-id, a single message number, or
a reference to a list of two message numbers.
.Sp
If \f(CWMESSAGE-SPEC\fR is a reference to a list of two message numbers and the
second number in a range is less than or equal to the first then the range
represents all messages in the group after the first message number.
.Sp
\fB\s-1NOTE\s0\fR For compatibility reasons only with earlier versions of Net::\s-1NNTP\s0
a message spec can be passed as a list of two numbers, this is depreciated
and a reference to the list should now be passed
.Ip "\s-1PATTERN\s0" 4
The \f(CWNNTP\fR protocol uses the \f(CWWILDMAT\fR format for patterns.
The \s-1WILDMAT\s0 format was first developed by Rich Salz based on
the format used in the \s-1UNIX\s0 \*(L"find\*(R" command to articulate
file names. It was developed to provide a uniform mechanism
for matching patterns in the same manner that the \s-1UNIX\s0 shell
matches filenames.
.Sp
Patterns are implicitly anchored at the
beginning and end of each string when testing for a match.
.Sp
There are five pattern matching operations other than a strict
one-to-one match between the pattern and the source to be
checked for a match.
.Sp
The first is an asterisk \f(CW*\fR to match any sequence of zero or more
characters.
.Sp
The second is a question mark \f(CW?\fR to match any single character. The
third specifies a specific set of characters.
.Sp
The set is specified as a list of characters, or as a range of characters
where the beginning and end of the range are separated by a minus (or dash)
character, or as any combination of lists and ranges. The dash can
also be included in the set as a character it if is the beginning
or end of the set. This set is enclosed in square brackets. The
close square bracket \f(CW]\fR may be used in a set if it is the first
character in the set.
.Sp
The fourth operation is the same as the
logical not of the third operation and is specified the same
way as the third with the addition of a caret character \f(CW^\fR at
the beginning of the test string just inside the open square
bracket.
.Sp
The final operation uses the backslash character to
invalidate the special meaning of the a open square bracket \f(CW[\fR,
the asterisk, backslash or the question mark. Two backslashes in
sequence will result in the evaluation of the backslash as a
character with no special meaning.
.Ip "Examples" 8
.Ip "\f(CW[^]-]\fR" 8
matches any single character other than a close square
bracket or a minus sign/dash.
.Ip "\f(CW*bdc\fR" 8
matches any string that ends with the string \*(L"bdc\*(R"
including the string \*(L"bdc\*(R" (without quotes).
.Ip "\f(CW[0-9a-zA-Z]\fR" 8
matches any single printable alphanumeric \s-1ASCII\s0 character.
.Ip "\f(CWa??d\fR" 8
matches any four character string which begins
with a and ends with d.
.SH "SEE ALSO"
the \fINet::Cmd\fR manpage
.SH "AUTHOR"
Graham Barr <gbarr@pobox.com>
.SH "COPYRIGHT"
Copyright (c) 1995-1997 Graham Barr. All rights reserved.
This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

.rn }` ''
.IX Title "Net::NNTP 3"
.IX Name "Net::NNTP - NNTP Client class"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "CONSTRUCTOR"

.IX Item "new ( [ \s-1HOST\s0 ] [, \s-1OPTIONS\s0 ])"

.IX Header "METHODS"

.IX Item "article ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )"

.IX Item "body ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )"

.IX Item "head ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )"

.IX Item "nntpstat ( [ \s-1MSGID\s0|\s-1MSGNUM\s0 ] )"

.IX Item "group ( [ \s-1GROUP\s0 ] )"

.IX Item "ihave ( \s-1MSGID\s0 [, \s-1MESSAGE\s0 ])"

.IX Item "last ()"

.IX Item "date ()"

.IX Item "postok ()"

.IX Item "authinfo ( \s-1USER\s0, \s-1PASS\s0 )"

.IX Item "list ()"

.IX Item "newgroups ( \s-1SINCE\s0 [, \s-1DISTRIBUTIONS\s0 ])"

.IX Item "newnews ( \s-1SINCE\s0 [, \s-1GROUPS\s0 [, \s-1DISTRIBUTIONS\s0 ]])"

.IX Item "next ()"

.IX Item "post ( [ \s-1MESSAGE\s0 ] )"

.IX Item "slave ()"

.IX Item "quit ()"

.IX Subsection "Extension methods"

.IX Item "newsgroups ( [ \s-1PATTERN\s0 ] )"

.IX Item "distributions ()"

.IX Item "subscriptions ()"

.IX Item "overview_fmt ()"

.IX Item "active_times ()"

.IX Item "active ( [ \s-1PATTERN\s0 ] )"

.IX Item "xgtitle ( \s-1PATTERN\s0 )"

.IX Item "xhdr ( \s-1HEADER\s0, \s-1MESSAGE\s0\-\s-1SPEC\s0 )"

.IX Item "xover ( \s-1MESSAGE\s0\-\s-1SPEC\s0 )"

.IX Item "xpath ( \s-1MESSAGE\s0\-\s-1ID\s0 )"

.IX Item "xpat ( \s-1HEADER\s0, \s-1PATTERN\s0, \s-1MESSAGE\s0\-\s-1SPEC\s0)"

.IX Item "xrover"

.IX Item "listgroup ( [ \s-1GROUP\s0 ] )"

.IX Item "reader"

.IX Header "UNSUPPORTED"

.IX Header "DEFINITIONS"

.IX Item "\s-1MESSAGE\s0\-\s-1SPEC\s0"

.IX Item "\s-1PATTERN\s0"

.IX Item "Examples"

.IX Item "\f(CW[^]-]\fR"

.IX Item "\f(CW*bdc\fR"

.IX Item "\f(CW[0-9a-zA-Z]\fR"

.IX Item "\f(CWa??d\fR"

.IX Header "SEE ALSO"

.IX Header "AUTHOR"

.IX Header "COPYRIGHT"

