.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH Net::FTP 3 "perl 5.004, patch 55" "25/Nov/97" "User Contributed Perl Documentation"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
Net::FTP \- FTP Client class
.SH "SYNOPSIS"
.PP
.Vb 7
\&    use Net::FTP;
\&    
\&    $ftp = Net::FTP->new("some.host.name");
\&    $ftp->login("anonymous","me@here.there");
\&    $ftp->cwd("/pub");
\&    $ftp->get("that.file");
\&    $ftp->quit;
.Ve
.SH "DESCRIPTION"
\f(CWNet::FTP\fR is a class implementing a simple FTP client in Perl as
described in RFC959.  It provides wrappers for a subset of the RFC959
commands.
.SH "OVERVIEW"
FTP stands for File Transfer Protocol.  It is a way of transferring
files between networked machines.  The protocol defines a client
(whose commands are provided by this module) and a server (not
implemented in this module).  Communication is always initiated by the
client, and the server responds with a message and a status code (and
sometimes with data).
.PP
The FTP protocol allows files to be sent to or fetched from the
server.  Each transfer involves a \fBlocal file\fR (on the client) and a
\fBremote file\fR (on the server).  In this module, the same file name
will be used for both local and remote if only one is specified.  This
means that transferring remote file \f(CW/path/to/file\fR will try to put
that file in \f(CW/path/to/file\fR locally, unless you specify a local file
name.
.PP
The protocol also defines several standard \fBtranslations\fR which the
file can undergo during transfer.  These are ASCII, EBCDIC, binary,
and byte.  ASCII is the default type, and indicates that the sender of
files will translate the ends of lines to a standard representation
which the receiver will then translate back into their local
representation.  EBCDIC indicates the file being transferred is in
EBCDIC format.  Binary (also known as image) format sends the data as
a contiguous bit stream.  Byte format transfers the data as bytes, the
values of which remain the same regardless of differences in byte size
between the two machines (in theory \- in practice you should only use
this if you really know what you're doing).
.SH "CONSTRUCTOR"
.Ip "new (\s-1HOST\s0 [,\s-1OPTIONS\s0])" 4
This is the constructor for a new Net::\s-1FTP\s0 object. \f(CWHOST\fR is the
name of the remote host to which a \s-1FTP\s0 connection is required.
.Sp
\f(CWOPTIONS\fR are passed in a hash like fashion, using key and value pairs.
Possible options are:
.Sp
\fBFirewall\fR \- The name of a machine which acts as a \s-1FTP\s0 firewall. This can be
overridden by an environment variable \f(CWFTP_FIREWALL\fR. If specified, and the
given host cannot be directly connected to, then the
connection is made to the firewall machine and the string \f(CW@hostname\fR is
appended to the login identifier. This kind of setup is also refered to
as a ftp proxy.
.Sp
\fBPort\fR \- The port number to connect to on the remote machine for the
\s-1FTP\s0 connection
.Sp
\fBTimeout\fR \- Set a timeout value (defaults to 120)
.Sp
\fBDebug\fR \- debug level (see the debug method in the \fINet::Cmd\fR manpage)
.Sp
\fBPassive\fR \- If set to \fItrue\fR then all data transfers will be done using 
passive mode. This is required for some \fIdumb\fR servers, and some
firewall configurations.  This can also be set by the environment
variable \f(CWFTP_PASSIVE\fR.
.SH "METHODS"
Unless otherwise stated all methods return either a \fItrue\fR or \fIfalse\fR
value, with \fItrue\fR meaning that the operation was a success. When a method
states that it returns a value, failure will be returned as \fIundef\fR or an
empty list.
.Ip "login ([\s-1LOGIN\s0 [,\s-1PASSWORD\s0 [, \s-1ACCOUNT\s0] ] ])" 4
Log into the remote \s-1FTP\s0 server with the given login information. If
no arguments are given then the \f(CWNet::FTP\fR uses the \f(CWNet::Netrc\fR
package to lookup the login information for the connected host.
If no information is found then a login of \fIanonymous\fR is used.
If no password is given and the login is \fIanonymous\fR then the users
Email address will be used for a password.
.Sp
If the connection is via a firewall then the \f(CWauthorize\fR method will
be called with no arguments.
.Ip "authorize ( [\s-1AUTH\s0 [, \s-1RESP\s0]])" 4
This is a protocol used by some firewall ftp proxies. It is used
to authorise the user to send data out.  If both arguments are not specified
then \f(CWauthorize\fR uses \f(CWNet::Netrc\fR to do a lookup.
.Ip "type (\s-1TYPE\s0 [, \s-1ARGS\s0])" 4
This method will send the \s-1TYPE\s0 command to the remote \s-1FTP\s0 server
to change the type of data transfer. The return value is the previous
value.
.Ip "ascii ([\s-1ARGS\s0]) binary([\s-1ARGS\s0]) ebcdic([\s-1ARGS\s0]) byte([\s-1ARGS\s0])" 4
Synonyms for \f(CWtype\fR with the first arguments set correctly
.Sp
\fB\s-1NOTE\s0\fR ebcdic and byte are not fully supported.
.Ip "rename ( \s-1OLDNAME\s0, \s-1NEWNAME\s0 )" 4
Rename a file on the remote \s-1FTP\s0 server from \f(CWOLDNAME\fR to \f(CWNEWNAME\fR. This
is done by sending the \s-1RNFR\s0 and \s-1RNTO\s0 commands.
.Ip "delete ( \s-1FILENAME\s0 )" 4
Send a request to the server to delete \f(CWFILENAME\fR.
.Ip "cwd ( [ \s-1DIR\s0 ] )" 4
Attempt to change directory to the directory given in \f(CW$dir\fR.  If
\f(CW$dir\fR is \f(CW".."\fR, the \s-1FTP\s0 \f(CWCDUP\fR command is used to attempt to
move up one directory. If no directory is given then an attempt is made
to change the directory to the root directory.
.Ip "cdup ()" 4
Change directory to the parent of the current directory.
.Ip "pwd ()" 4
Returns the full pathname of the current directory.
.Ip "rmdir ( \s-1DIR\s0 )" 4
Remove the directory with the name \f(CWDIR\fR.
.Ip "mkdir ( \s-1DIR\s0 [, \s-1RECURSE\s0 ])" 4
Create a new directory with the name \f(CWDIR\fR. If \f(CWRECURSE\fR is \fItrue\fR then
\f(CWmkdir\fR will attempt to create all the directories in the given path.
.Sp
Returns the full pathname to the new directory.
.Ip "ls ( [ \s-1DIR\s0 ] )" 4
Get a directory listing of \f(CWDIR\fR, or the current directory.
.Sp
In an array context, returns a list of lines returned from the server. In
a scalar context, returns a reference to a list.
.Ip "dir ( [ \s-1DIR\s0 ] )" 4
Get a directory listing of \f(CWDIR\fR, or the current directory in long format.
.Sp
In an array context, returns a list of lines returned from the server. In
a scalar context, returns a reference to a list.
.Ip "get ( \s-1REMOTE_FILE\s0 [, \s-1LOCAL_FILE\s0 [, \s-1WHERE\s0]] )" 4
Get \f(CWREMOTE_FILE\fR from the server and store locally. \f(CWLOCAL_FILE\fR may be
a filename or a filehandle. If not specified the the file will be stored in
the current directory with the same leafname as the remote file.
.Sp
If \f(CWWHERE\fR is given then the first \f(CWWHERE\fR bytes of the file will
not be transfered, and the remaining bytes will be appended to
the local file if it already exists.
.Sp
Returns \f(CWLOCAL_FILE\fR, or the generated local file name if \f(CWLOCAL_FILE\fR
is not given.
.Ip "put ( \s-1LOCAL_FILE\s0 [, \s-1REMOTE_FILE\s0 ] )" 4
Put a file on the remote server. \f(CWLOCAL_FILE\fR may be a name or a filehandle.
If \f(CWLOCAL_FILE\fR is a filehandle then \f(CWREMOTE_FILE\fR must be specified. If
\f(CWREMOTE_FILE\fR is not specified then the file will be stored in the current
directory with the same leafname as \f(CWLOCAL_FILE\fR.
.Sp
Returns \f(CWREMOTE_FILE\fR, or the generated remote filename if \f(CWREMOTE_FILE\fR
is not given.
.Sp
\fB\s-1NOTE\s0\fR: If for some reason the transfer does not complete and an error is
returned then the contents that had been transfered will not be remove
automatically.
.Ip "put_unique ( \s-1LOCAL_FILE\s0 [, \s-1REMOTE_FILE\s0 ] )" 4
Same as put but uses the \f(CWSTOU\fR command.
.Sp
Returns the name of the file on the server.
.Ip "append ( \s-1LOCAL_FILE\s0 [, \s-1REMOTE_FILE\s0 ] )" 4
Same as put but appends to the file on the remote server.
.Sp
Returns \f(CWREMOTE_FILE\fR, or the generated remote filename if \f(CWREMOTE_FILE\fR
is not given.
.Ip "unique_name ()" 4
Returns the name of the last file stored on the server using the
\f(CWSTOU\fR command.
.Ip "mdtm ( \s-1FILE\s0 )" 4
Returns the \fImodification time\fR of the given file
.Ip "size ( \s-1FILE\s0 )" 4
Returns the size in bytes for the given file as stored on the remote server.
.Sp
\fB\s-1NOTE\s0\fR: The size reported is the size of the stored file on the remote server.
If the file is subsequently transfered from the server in \s-1ASCII\s0 mode
and the remote server and local machine have different ideas about
\*(L"End Of Line\*(R" then the size of file on the local machine after transfer
may be different.
.Ip "supported ( \s-1CMD\s0 )" 4
Returns \s-1TRUE\s0 if the remote server supports the given command.
.PP
The following methods can return different results depending on
how they are called. If the user explicitly calls either
of the \f(CWpasv\fR or \f(CWport\fR methods then these methods will
return a \fItrue\fR or \fIfalse\fR value. If the user does not
call either of these methods then the result will be a
reference to a \f(CWNet::FTP::dataconn\fR based object.
.Ip "nlst ( [ \s-1DIR\s0 ] )" 4
Send a \f(CWNLST\fR command to the server, with an optional parameter.
.Ip "list ( [ \s-1DIR\s0 ] )" 4
Same as \f(CWnlst\fR but using the \f(CWLIST\fR command
.Ip "retr ( \s-1FILE\s0 )" 4
Begin the retrieval of a file called \f(CWFILE\fR from the remote server.
.Ip "stor ( \s-1FILE\s0 )" 4
Tell the server that you wish to store a file. \f(CWFILE\fR is the
name of the new file that should be created.
.Ip "stou ( \s-1FILE\s0 )" 4
Same as \f(CWstor\fR but using the \f(CWSTOU\fR command. The name of the unique
file which was created on the server will be available via the \f(CWunique_name\fR
method after the data connection has been closed.
.Ip "appe ( \s-1FILE\s0 )" 4
Tell the server that we want to append some data to the end of a file
called \f(CWFILE\fR. If this file does not exist then create it.
.PP
If for some reason you want to have complete control over the data connection,
this includes generating it and calling the \f(CWresponse\fR method when required,
then the user can use these methods to do so.
.PP
However calling these methods only affects the use of the methods above that
can return a data connection. They have no effect on methods \f(CWget\fR, \f(CWput\fR,
\f(CWput_unique\fR and those that do not require data connections.
.Ip "port ( [ \s-1PORT\s0 ] )" 4
Send a \f(CWPORT\fR command to the server. If \f(CWPORT\fR is specified then it is sent
to the server. If not the a listen socket is created and the correct information
sent to the server.
.Ip "pasv ()" 4
Tell the server to go into passive mode. Returns the text that represents the
port on which the server is listening, this text is in a suitable form to
sent to another ftp server using the \f(CWport\fR method.
.PP
The following methods can be used to transfer files between two remote
servers, providing that these two servers can connect directly to each other.
.Ip "pasv_xfer ( \s-1SRC_FILE\s0, \s-1DEST_SERVER\s0 [, \s-1DEST_FILE\s0 ] )" 4
This method will do a file transfer between two remote ftp servers. If
\f(CWDEST_FILE\fR is omitted then the leaf name of \f(CWSRC_FILE\fR will be used.
.Ip "pasv_xfer_unique ( \s-1SRC_FILE\s0, \s-1DEST_SERVER\s0 [, \s-1DEST_FILE\s0 ] )" 4
Like \f(CWpasv_xfer\fR but the file is stored on the remote server using
the \s-1STOU\s0 command.
.Ip "pasv_wait ( \s-1NON_PASV_SERVER\s0 )" 4
This method can be used to wait for a transfer to complete between a passive
server and a non-passive server. The method should be called on the passive
server with the \f(CWNet::FTP\fR object for the non-passive server passed as an
argument.
.Ip "abort ()" 4
Abort the current data transfer.
.Ip "quit ()" 4
Send the \s-1QUIT\s0 command to the remote \s-1FTP\s0 server and close the socket connection.
.Sh "Methods for the adventurous"
\f(CWNet::FTP\fR inherits from \f(CWNet::Cmd\fR so methods defined in \f(CWNet::Cmd\fR may
be used to send commands to the remote \s-1FTP\s0 server.
.Ip "quot (\s-1CMD\s0 [,\s-1ARGS\s0])" 4
Send a command, that Net::\s-1FTP\s0 does not directly support, to the remote
server and wait for a response.
.Sp
Returns most significant digit of the response code.
.Sp
\fB\s-1WARNING\s0\fR This call should only be used on commands that do not require
data connections. Misuse of this method can hang the connection.
.SH "THE dataconn CLASS"
Some of the methods defined in \f(CWNet::FTP\fR return an object which will
be derived from this class.The dataconn class itself is derived from
the \f(CWIO::Socket::INET\fR class, so any normal IO operations can be performed.
However the following methods are defined in the dataconn class and IO should
be performed using these.
.Ip "read ( \s-1BUFFER\s0, \s-1SIZE\s0 [, \s-1TIMEOUT\s0 ] )" 4
Read \f(CWSIZE\fR bytes of data from the server and place it into \f(CWBUFFER\fR, also
performing any <\s-1CRLF\s0> translation necessary. \f(CWTIMEOUT\fR is optional, if not
given the the timeout value from the command connection will be used.
.Sp
Returns the number of bytes read before any <\s-1CRLF\s0> translation.
.Ip "write ( \s-1BUFFER\s0, \s-1SIZE\s0 [, \s-1TIMEOUT\s0 ] )" 4
Write \f(CWSIZE\fR bytes of data from \f(CWBUFFER\fR to the server, also
performing any <\s-1CRLF\s0> translation necessary. \f(CWTIMEOUT\fR is optional, if not
given the the timeout value from the command connection will be used.
.Sp
Returns the number of bytes written before any <\s-1CRLF\s0> translation.
.Ip "abort ()" 4
Abort the current data transfer.
.Ip "close ()" 4
Close the data connection and get a response from the \s-1FTP\s0 server. Returns
\fItrue\fR if the connection was closed successfully and the first digit of
the response from the server was a \*(L'2\*(R'.
.SH "UNIMPLEMENTED"
The following RFC959 commands have not been implemented:
.Ip "\fB\s-1ALLO\s0\fR" 4
Allocates storage for the file to be transferred.
.Ip "\fB\s-1SMNT\s0\fR" 4
Mount a different file system structure without changing login or
accounting information.
.Ip "\fB\s-1HELP\s0\fR" 4
Ask the server for \*(L"helpful information\*(R" (that's what the \s-1RFC\s0 says) on
the commands it accepts.
.Ip "\fB\s-1MODE\s0\fR" 4
Specifies transfer mode (stream, block or compressed) for file to be
transferred.
.Ip "\fB\s-1SITE\s0\fR" 4
Request remote server site parameters.
.Ip "\fB\s-1SYST\s0\fR" 4
Request remote server system identification.
.Ip "\fB\s-1STAT\s0\fR" 4
Request remote server status.
.Ip "\fB\s-1STRU\s0\fR" 4
Specifies file structure for file to be transferred.
.Ip "\fB\s-1REIN\s0\fR" 4
Reinitialize the connection, flushing all I/O and account information.
.SH "REPORTING BUGS"
When reporting bugs/problems please include as much information as possible.
It may be difficult for me to reproduce the problem as almost every setup
is different.
.PP
A small script which yields the problem will probably be of help. It would
also be useful if this script was run with the extra options \f(CWDebug =\fR 1>
passed to the constructor, and the output sent with the bug report. If you
cannot include a small script then please include a Debug trace from a
run of your program which does yield the problem.
.SH "AUTHOR"
Graham Barr <gbarr@pobox.com>
.SH "SEE ALSO"
the \fINet::Netrc\fR manpage
the \fINet::Cmd\fR manpage
.PP
\fIftp\fR\|(1), \fIftpd\fR\|(8), RFC 959
http://www.cis.ohio-state.edu/htbin/rfc/rfc959.html
.SH "CREDITS"
Henry Gabryjelski <henryg@WPI.EDU> \- for the suggestion of creating directories
recursively.
.PP
Nathan Torkington <gnat@frii.com> \- for some input on the documentation.
.PP
Roderick Schertler <roderick@gate.net> \- for various inputs
.SH "COPYRIGHT"
Copyright (c) 1995-1997 Graham Barr. All rights reserved.
This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

.rn }` ''
.IX Title "Net::FTP 3"
.IX Name "Net::FTP - FTP Client class"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OVERVIEW"

.IX Header "CONSTRUCTOR"

.IX Item "new (\s-1HOST\s0 [,\s-1OPTIONS\s0])"

.IX Header "METHODS"

.IX Item "login ([\s-1LOGIN\s0 [,\s-1PASSWORD\s0 [, \s-1ACCOUNT\s0] ] ])"

.IX Item "authorize ( [\s-1AUTH\s0 [, \s-1RESP\s0]])"

.IX Item "type (\s-1TYPE\s0 [, \s-1ARGS\s0])"

.IX Item "ascii ([\s-1ARGS\s0]) binary([\s-1ARGS\s0]) ebcdic([\s-1ARGS\s0]) byte([\s-1ARGS\s0])"

.IX Item "rename ( \s-1OLDNAME\s0, \s-1NEWNAME\s0 )"

.IX Item "delete ( \s-1FILENAME\s0 )"

.IX Item "cwd ( [ \s-1DIR\s0 ] )"

.IX Item "cdup ()"

.IX Item "pwd ()"

.IX Item "rmdir ( \s-1DIR\s0 )"

.IX Item "mkdir ( \s-1DIR\s0 [, \s-1RECURSE\s0 ])"

.IX Item "ls ( [ \s-1DIR\s0 ] )"

.IX Item "dir ( [ \s-1DIR\s0 ] )"

.IX Item "get ( \s-1REMOTE_FILE\s0 [, \s-1LOCAL_FILE\s0 [, \s-1WHERE\s0]] )"

.IX Item "put ( \s-1LOCAL_FILE\s0 [, \s-1REMOTE_FILE\s0 ] )"

.IX Item "put_unique ( \s-1LOCAL_FILE\s0 [, \s-1REMOTE_FILE\s0 ] )"

.IX Item "append ( \s-1LOCAL_FILE\s0 [, \s-1REMOTE_FILE\s0 ] )"

.IX Item "unique_name ()"

.IX Item "mdtm ( \s-1FILE\s0 )"

.IX Item "size ( \s-1FILE\s0 )"

.IX Item "supported ( \s-1CMD\s0 )"

.IX Item "nlst ( [ \s-1DIR\s0 ] )"

.IX Item "list ( [ \s-1DIR\s0 ] )"

.IX Item "retr ( \s-1FILE\s0 )"

.IX Item "stor ( \s-1FILE\s0 )"

.IX Item "stou ( \s-1FILE\s0 )"

.IX Item "appe ( \s-1FILE\s0 )"

.IX Item "port ( [ \s-1PORT\s0 ] )"

.IX Item "pasv ()"

.IX Item "pasv_xfer ( \s-1SRC_FILE\s0, \s-1DEST_SERVER\s0 [, \s-1DEST_FILE\s0 ] )"

.IX Item "pasv_xfer_unique ( \s-1SRC_FILE\s0, \s-1DEST_SERVER\s0 [, \s-1DEST_FILE\s0 ] )"

.IX Item "pasv_wait ( \s-1NON_PASV_SERVER\s0 )"

.IX Item "abort ()"

.IX Item "quit ()"

.IX Subsection "Methods for the adventurous"

.IX Item "quot (\s-1CMD\s0 [,\s-1ARGS\s0])"

.IX Header "THE dataconn CLASS"

.IX Item "read ( \s-1BUFFER\s0, \s-1SIZE\s0 [, \s-1TIMEOUT\s0 ] )"

.IX Item "write ( \s-1BUFFER\s0, \s-1SIZE\s0 [, \s-1TIMEOUT\s0 ] )"

.IX Item "abort ()"

.IX Item "close ()"

.IX Header "UNIMPLEMENTED"

.IX Item "\fB\s-1ALLO\s0\fR"

.IX Item "\fB\s-1SMNT\s0\fR"

.IX Item "\fB\s-1HELP\s0\fR"

.IX Item "\fB\s-1MODE\s0\fR"

.IX Item "\fB\s-1SITE\s0\fR"

.IX Item "\fB\s-1SYST\s0\fR"

.IX Item "\fB\s-1STAT\s0\fR"

.IX Item "\fB\s-1STRU\s0\fR"

.IX Item "\fB\s-1REIN\s0\fR"

.IX Header "REPORTING BUGS"

.IX Header "AUTHOR"

.IX Header "SEE ALSO"

.IX Header "CREDITS"

.IX Header "COPYRIGHT"

