.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH overload 3 "perl 5.005, patch 53" "5/Nov/98" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
overload \- Package for overloading perl operations
.SH "SYNOPSIS"
.PP
.Vb 1
\&    package SomeThing;
.Ve
.Vb 5
\&    use overload 
\&        '+' => \e&myadd,
\&        '-' => \e&mysub;
\&        # etc
\&    ...
.Ve
.Vb 7
\&    package main;
\&    $a = new SomeThing 57;
\&    $b=5+$a;
\&    ...
\&    if (overload::Overloaded $b) {...}
\&    ...
\&    $strval = overload::StrVal $b;
.Ve
.SH "CAVEAT SCRIPTOR"
Overloading of operators is a subject not to be taken lightly.
Neither its precise implementation, syntax, nor semantics are
100% endorsed by Larry Wall.  So any of these may be changed 
at some point in the future.
.SH "DESCRIPTION"
.Sh "Declaration of overloaded functions"
The compilation directive
.PP
.Vb 4
\&    package Number;
\&    use overload
\&        "+" => \e&add, 
\&        "*=" => "muas";
.Ve
declares function \fINumber::add()\fR for addition, and method \fImuas()\fR in
the \*(L"class\*(R" \f(CWNumber\fR (or one of its base classes)
for the assignment form \f(CW*=\fR of multiplication.  
.PP
Arguments of this directive come in (key, value) pairs.  Legal values
are values legal inside a \f(CW&{ ... }\fR call, so the name of a
subroutine, a reference to a subroutine, or an anonymous subroutine
will all work.  Note that values specified as strings are
interpreted as methods, not subroutines.  Legal keys are listed below.
.PP
The subroutine \f(CWadd\fR will be called to execute \f(CW$a+$b\fR if \f(CW$a\fR
is a reference to an object blessed into the package \f(CWNumber\fR, or if \f(CW$a\fR is
not an object from a package with defined mathemagic addition, but \f(CW$b\fR is a
reference to a \f(CWNumber\fR.  It can also be called in other situations, like
\f(CW$a+=7\fR, or \f(CW$a++\fR.  See the section on \fI\s-1MAGIC\s0 \s-1AUTOGENERATION\s0\fR.  (Mathemagical
methods refer to methods triggered by an overloaded mathematical
operator.)
.PP
Since overloading respects inheritance via the \f(CW@ISA\fR hierarchy, the
above declaration would also trigger overloading of \f(CW+\fR and \f(CW*=\fR in
all the packages which inherit from \f(CWNumber\fR.
.Sh "Calling Conventions for Binary Operations"
The functions specified in the \f(CWuse overload ...\fR directive are called
with three (in one particular case with four, see the section on \fILast Resort\fR)
arguments.  If the corresponding operation is binary, then the first
two arguments are the two arguments of the operation.  However, due to
general object calling conventions, the first argument should always be
an object in the package, so in the situation of \f(CW7+$a\fR, the
order of the arguments is interchanged.  It probably does not matter
when implementing the addition method, but whether the arguments
are reversed is vital to the subtraction method.  The method can
query this information by examining the third argument, which can take
three different values:
.Ip "\s-1FALSE\s0" 7
the order of arguments is as in the current operation.
.Ip "\s-1TRUE\s0" 7
the arguments are reversed.
.Ip "\f(CWundef\fR" 7
the current operation is an assignment variant (as in
\f(CW$a+=7\fR), but the usual function is called instead.  This additional
information can be used to generate some optimizations.  Compare
the section on \fICalling Conventions for Mutators\fR.
.Sh "Calling Conventions for Unary Operations"
Unary operation are considered binary operations with the second
argument being \f(CWundef\fR.  Thus the functions that overloads \f(CW{"++"}\fR
is called with arguments \f(CW($a,undef,'')\fR when \f(CW$a\fR++ is executed.
.Sh "Calling Conventions for Mutators"
Two types of mutators have different calling conventions:
.Ip "\f(CW++\fR and \f(CW--\fR" 5
The routines which implement these operators are expected to actually
\fImutate\fR their arguments.  So, assuming that \f(CW$obj\fR is a reference to a
number,
.Sp
.Vb 1
\&  sub incr { my $n = $ {$_[0]}; ++$n; $_[0] = bless \e$n}
.Ve
is an appropriate implementation of overloaded \f(CW++\fR.  Note that
.Sp
.Vb 1
\&  sub incr { ++$ {$_[0]} ; shift }
.Ve
is \s-1OK\s0 if used with preincrement and with postincrement. (In the case
of postincrement a copying will be performed, see the section on \fICopy Constructor\fR.)
.Ip "\f(CWx=\fR and other assignment versions" 5
There is nothing special about these methods.  They may change the
value of their arguments, and may leave it as is.  The result is going
to be assigned to the value in the left-hand-side if different from
this value.
.Sp
This allows for the same method to be used as averloaded \f(CW+=\fR and
\f(CW+\fR.  Note that this is \fIallowed\fR, but not recommended, since by the
semantic of the section on \fIFallback\fR Perl will call the method for \f(CW+\fR anyway,
if \f(CW+=\fR is not overloaded.
.PP
\fBWarning.\fR  Due to the presense of assignment versions of operations,
routines which may be called in assignment context may create 
self-referencial structures.  Currently Perl will not free self-referential 
structures until cycles are \f(CWexplicitly\fR broken.  You may get problems
when traversing your structures too.
.PP
Say, 
.PP
.Vb 1
\&  use overload '+' => sub { bless [ \e$_[0], \e$_[1] ] };
.Ve
is asking for trouble, since for code \f(CW$obj += $foo\fR the subroutine
is called as \f(CW$obj = add($obj, $foo, undef)\fR, or \f(CW$obj = [\e$obj, 
\e$foo]\fR.  If using such a subroutine is an important optimization, one
can overload \f(CW+=\fR explicitly by a non-"optimized\*(R" version, or switch
to non-optimized version if \f(CWnot defined $_[2]\fR (see 
the section on \fICalling Conventions for Binary Operations\fR).
.PP
Even if no \fIexplicit\fR assignment-variants of operators are present in
the script, they may be generated by the optimizer.  Say, \f(CW",$obj,"\fR or
\&\f(CW',' . $obj . ','\fR may be both optimized to
.PP
.Vb 1
\&  my $tmp = ',' . $obj;    $tmp .= ',';
.Ve
.Sh "Overloadable Operations"
The following symbols can be specified in \f(CWuse overload\fR directive:
.Ip "\(bu \fIArithmetic operations\fR" 5
.Sp
.Vb 2
\&    "+", "+=", "-", "-=", "*", "*=", "/", "/=", "%", "%=",
\&    "**", "**=", "<<", "<<=", ">>", ">>=", "x", "x=", ".", ".=",
.Ve
For these operations a substituted non-assignment variant can be called if
the assignment variant is not available.  Methods for operations \*(L"\f(CW+\fR\*(R",
\*(L"\f(CW-\fR\*(R", \*(L"\f(CW+=\fR\*(R", and \*(L"\f(CW-=\fR\*(R" can be called to automatically generate
increment and decrement methods.  The operation \*(L"\f(CW-\fR\*(R" can be used to
autogenerate missing methods for unary minus or \f(CWabs\fR.
.Sp
See the section on \fI\s-1MAGIC\s0 \s-1AUTOGENERATION\s0\fR, the section on \fICalling Conventions for Mutators\fR and
the section on \fICalling Conventions for Binary Operations\fR) for details of these
substitutions.
.Ip "\(bu \fIComparison operations\fR" 5
.Sp
.Vb 2
\&    "<",  "<=", ">",  ">=", "==", "!=", "<=>",
\&    "lt", "le", "gt", "ge", "eq", "ne", "cmp",
.Ve
If the corresponding \*(L"spaceship\*(R" variant is available, it can be
used to substitute for the missing operation.  During \f(CWsort\fRing
arrays, \f(CWcmp\fR is used to compare values subject to \f(CWuse overload\fR.
.Ip "\(bu \fIBit operations\fR" 5
.Sp
.Vb 1
\&    "&", "^", "|", "neg", "!", "~",
.Ve
\*(L"\f(CWneg\fR\*(R" stands for unary minus.  If the method for \f(CWneg\fR is not
specified, it can be autogenerated using the method for
subtraction. If the method for \*(L"\f(CW!\fR\*(R" is not specified, it can be
autogenerated using the methods for \*(L"\f(CWbool\fR\*(R", or \*(L"\f(CW\e"\e"\fR\*(R", or \*(L"\f(CW0+\fR\*(R".
.Ip "\(bu \fIIncrement and decrement\fR" 5
.Sp
.Vb 1
\&    "++", "--",
.Ve
If undefined, addition and subtraction methods can be
used instead.  These operations are called both in prefix and
postfix form.
.Ip "\(bu \fITranscendental functions\fR" 5
.Sp
.Vb 1
\&    "atan2", "cos", "sin", "exp", "abs", "log", "sqrt",
.Ve
If \f(CWabs\fR is unavailable, it can be autogenerated using methods
for \*(L"<\*(R" or \*(L"<=>\*(R" combined with either unary minus or subtraction.
.Ip "\(bu \fIBoolean, string and numeric conversion\fR" 5
.Sp
.Vb 1
\&    "bool", "\e"\e"", "0+",
.Ve
If one or two of these operations are not overloaded, the remaining ones can
be used instead.  \f(CWbool\fR is used in the flow control operators
(like \f(CWwhile\fR) and for the ternary \*(L"\f(CW?:\fR\*(R" operation.  These functions can
return any arbitrary Perl value.  If the corresponding operation for this value
is overloaded too, that operation will be called again with this value.
.Ip "\(bu \fIIteration\fR" 5
.Sp
.Vb 1
\&    "<>"
.Ve
If not overloaded, the argument will be converted to a filehandle or
glob (which may require a stringification).  The same overloading
happens both for the \fIread-filehandle\fR syntax \f(CW<$var>\fR and
\fIglobbing\fR syntax \f(CW<${var}>\fR.
.Ip "\(bu \fIDereferencing\fR" 5
.Sp
.Vb 1
\&    '${}', '@{}', '%{}', '&{}', '*{}'.
.Ve
If not overloaded, the argument will be dereferenced \fIas is\fR, thus
should be of correct type.  These functions should return a reference
of correct type, or another object with overloaded dereferencing.
.Ip "\(bu \fISpecial\fR" 5
.Sp
.Vb 1
\&    "nomethod", "fallback", "=",
.Ve
see the section on \fI\s-1SPECIAL\s0 \s-1SYMBOLS\s0 \s-1FOR\s0 \f(CWuse overload\fR\fR.
.PP
See the section on \fIFallback\fR for an explanation of when a missing method can be
autogenerated.
.PP
A computer-readable form of the above table is available in the hash
\f(CW%overload::ops\fR, with values being space-separated lists of names:
.PP
.Vb 13
\& with_assign      => '+ - * / % ** << >> x .',
\& assign           => '+= -= *= /= %= **= <<= >>= x= .=',
\& str_comparison   => '< <= > >= == !=',
\& '3way_comparison'=> '<=> cmp',
\& num_comparison   => 'lt le gt ge eq ne',
\& binary           => '& | ^',
\& unary            => 'neg ! ~',
\& mutators         => '++ --',
\& func             => 'atan2 cos sin exp abs log sqrt',
\& conversion       => 'bool "" 0+',
\& iterators        => '<>',
\& dereferencing    => '${} @{} %{} &{} *{}',
\& special          => 'nomethod fallback ='
.Ve
.Sh "Inheritance and overloading"
Inheritance interacts with overloading in two ways.
.Ip "Strings as values of \f(CWuse overload\fR directive" 5
If \f(CWvalue\fR in
.Sp
.Vb 1
\&  use overload key => value;
.Ve
is a string, it is interpreted as a method name.
.Ip "Overloading of an operation is inherited by derived classes" 5
Any class derived from an overloaded class is also overloaded.  The
set of overloaded methods is the union of overloaded methods of all
the ancestors. If some method is overloaded in several ancestor, then
which description will be used is decided by the usual inheritance
rules:
.Sp
If \f(CWA\fR inherits from \f(CWB\fR and \f(CWC\fR (in this order), \f(CWB\fR overloads
\f(CW+\fR with \f(CW\e&D::plus_sub\fR, and \f(CWC\fR overloads \f(CW+\fR by \f(CW"plus_meth"\fR,
then the subroutine \f(CWD::plus_sub\fR will be called to implement
operation \f(CW+\fR for an object in package \f(CWA\fR.
.PP
Note that since the value of the \f(CWfallback\fR key is not a subroutine,
its inheritance is not governed by the above rules.  In the current
implementation, the value of \f(CWfallback\fR in the first overloaded
ancestor is used, but this is accidental and subject to change.
.SH "SPECIAL SYMBOLS FOR \f(CWuse overload\fR"
Three keys are recognized by Perl that are not covered by the above
description.
.Sh "Last Resort"
\f(CW"nomethod"\fR should be followed by a reference to a function of four
parameters.  If defined, it is called when the overloading mechanism
cannot find a method for some operation.  The first three arguments of
this function coincide with the arguments for the corresponding method if
it were found, the fourth argument is the symbol
corresponding to the missing method.  If several methods are tried,
the last one is used.  Say, \f(CW1-$a\fR can be equivalent to
.PP
.Vb 1
\&        &nomethodMethod($a,1,1,"-")
.Ve
if the pair \f(CW"nomethod" => "nomethodMethod"\fR was specified in the
\f(CWuse overload\fR directive.
.PP
If some operation cannot be resolved, and there is no function
assigned to \f(CW"nomethod"\fR, then an exception will be raised via \fIdie()\fR--
unless \f(CW"fallback"\fR was specified as a key in \f(CWuse overload\fR directive.
.Sh "Fallback "
The key \f(CW"fallback"\fR governs what to do if a method for a particular
operation is not found.  Three different cases are possible depending on
the value of \f(CW"fallback"\fR:
.Ip "\(bu \f(CWundef\fR" 16
Perl tries to use a
substituted method (see the section on \fI\s-1MAGIC\s0 \s-1AUTOGENERATION\s0\fR).  If this fails, it
then tries to calls \f(CW"nomethod"\fR value; if missing, an exception
will be raised.
.Ip "\(bu \s-1TRUE\s0" 16
The same as for the \f(CWundef\fR value, but no exception is raised.  Instead,
it silently reverts to what it would have done were there no \f(CWuse overload\fR
present.
.Ip "\(bu defined, but \s-1FALSE\s0" 16
No autogeneration is tried.  Perl tries to call
\f(CW"nomethod"\fR value, and if this is missing, raises an exception. 
.PP
\fBNote.\fR \f(CW"fallback"\fR inheritance via \f(CW@ISA\fR is not carved in stone
yet, see the section on \fIInheritance and overloading\fR.
.Sh "Copy Constructor"
The value for \f(CW"="\fR is a reference to a function with three
arguments, i.e., it looks like the other values in \f(CWuse
overload\fR. However, it does not overload the Perl assignment
operator. This would go against Camel hair.
.PP
This operation is called in the situations when a mutator is applied
to a reference that shares its object with some other reference, such
as
.PP
.Vb 2
\&        $a=$b; 
\&        ++$a;
.Ve
To make this change \f(CW$a\fR and not change \f(CW$b\fR, a copy of \f(CW$$a\fR is made,
and \f(CW$a\fR is assigned a reference to this new object.  This operation is
done during execution of the \f(CW++$a\fR, and not during the assignment,
(so before the increment \f(CW$$a\fR coincides with \f(CW$$b\fR).  This is only
done if \f(CW++\fR is expressed via a method for \f(CW'++'\fR or \f(CW'+='\fR (or
\f(CWnomethod\fR).  Note that if this operation is expressed via \f(CW'+'\fR
a nonmutator, i.e., as in
.PP
.Vb 2
\&        $a=$b; 
\&        $a=$a+1;
.Ve
then \f(CW$a\fR does not reference a new copy of \f(CW$$a\fR, since $$a does not
appear as lvalue when the above code is executed.
.PP
If the copy constructor is required during the execution of some mutator,
but a method for \f(CW'='\fR was not specified, it can be autogenerated as a
string copy if the object is a plain scalar.
.Ip "\fBExample\fR" 5
The actually executed code for 
.Sp
.Vb 3
\&        $a=$b; 
\&        Something else which does not modify $a or $b....
\&        ++$a;
.Ve
may be
.Sp
.Vb 4
\&        $a=$b; 
\&        Something else which does not modify $a or $b....
\&        $a = $a->clone(undef,"");
\&        $a->incr(undef,"");
.Ve
if \f(CW$b\fR was mathemagical, and \f(CW'++'\fR was overloaded with \f(CW\e&incr\fR,
\&\f(CW'='\fR was overloaded with \f(CW\e&clone\fR.
.PP
Same behaviour is triggered by \f(CW$b = $a++\fR, which is consider a synonim for
\f(CW$b = $a; ++$a\fR.
.SH "MAGIC AUTOGENERATION"
If a method for an operation is not found, and the value for  \f(CW"fallback"\fR is
TRUE or undefined, Perl tries to autogenerate a substitute method for
the missing operation based on the defined operations.  Autogenerated method
substitutions are possible for the following operations:
.Ip "\fIAssignment forms of arithmetic operations\fR" 16
\f(CW$a+=$b\fR can use the method for \f(CW"+"\fR if the method for \f(CW"+="\fR
is not defined.
.Ip "\fIConversion operations\fR " 16
String, numeric, and boolean conversion are calculated in terms of one
another if not all of them are defined.
.Ip "\fIIncrement and decrement\fR" 16
The \f(CW++$a\fR operation can be expressed in terms of \f(CW$a+=1\fR or \f(CW$a+1\fR,
and \f(CW$a--\fR in terms of \f(CW$a-=1\fR and \f(CW$a-1\fR.
.Ip "\f(CWabs($a)\fR" 16
can be expressed in terms of \f(CW$a<0\fR and \f(CW-$a\fR (or \f(CW0-$a\fR).
.Ip "\fIUnary minus\fR" 16
can be expressed in terms of subtraction.
.Ip "\fINegation\fR" 16
\f(CW!\fR and \f(CWnot\fR can be expressed in terms of boolean conversion, or
string or numerical conversion.
.Ip "\fIConcatenation\fR" 16
can be expressed in terms of string conversion.
.Ip "\fIComparison operations\fR " 16
can be expressed in terms of its \*(L"spaceship\*(R" counterpart: either
\f(CW<=>\fR or \f(CWcmp\fR:
.Sp
.Vb 2
\&    <, >, <=, >=, ==, !=        in terms of <=>
\&    lt, gt, le, ge, eq, ne      in terms of cmp
.Ve
.Ip "\fIIterator\fR" 16
.Sp
.Vb 1
\&    <>                          in terms of builtin operations
.Ve
.Ip "\fIDereferencing\fR" 16
.Sp
.Vb 1
\&    ${} @{} %{} &{} *{}         in terms of builtin operations
.Ve
.Ip "\fICopy operator\fR" 16
can be expressed in terms of an assignment to the dereferenced value, if this
value is a scalar and not a reference.
.SH "Losing overloading"
The restriction for the comparison operation is that even if, for example,
`\f(CWcmp\fR\*(R' should return a blessed reference, the autogenerated `\f(CWlt\fR\*(R'
function will produce only a standard logical value based on the
numerical value of the result of `\f(CWcmp\fR\*(R'.  In particular, a working
numeric conversion is needed in this case (possibly expressed in terms of
other conversions).
.PP
Similarly, \f(CW.=\fR  and \f(CWx=\fR operators lose their mathemagical properties
if the string conversion substitution is applied.
.PP
When you \fIchop()\fR a mathemagical object it is promoted to a string and its
mathemagical properties are lost.  The same can happen with other
operations as well.
.SH "Run-time Overloading"
Since all \f(CWuse\fR directives are executed at compile-time, the only way to
change overloading during run-time is to
.PP
.Vb 1
\&    eval 'use overload "+" => \e&addmethod';
.Ve
You can also use
.PP
.Vb 1
\&    eval 'no overload "+", "--", "<="';
.Ve
though the use of these constructs during run-time is questionable.
.SH "Public functions"
Package \f(CWoverload.pm\fR provides the following public functions:
.Ip "overload::StrVal(arg)" 5
Gives string value of \f(CWarg\fR as in absence of stringify overloading.
.Ip "overload::Overloaded(arg)" 5
Returns true if \f(CWarg\fR is subject to overloading of some operations.
.Ip "overload::Method(obj,op)" 5
Returns \f(CWundef\fR or a reference to the method that implements \f(CWop\fR.
.SH "Overloading constants"
For some application Perl parser mangles constants too much.  It is possible
to hook into this process via \fIoverload::constant()\fR and \fIoverload::remove_constant()\fR
functions.
.PP
These functions take a hash as an argument.  The recognized keys of this hash
are
.Ip "integer" 8
to overload integer constants,
.Ip "float" 8
to overload floating point constants,
.Ip "binary" 8
to overload octal and hexadecimal constants,
.Ip "q" 8
to overload \f(CWq\fR\-quoted strings, constant pieces of \f(CWqq\fR\- and \f(CWqx\fR\-quoted
strings and here-documents,
.Ip "qr" 8
to overload constant pieces of regular expressions.
.PP
The corresponding values are references to functions which take three arguments:
the first one is the \fIinitial\fR string form of the constant, the second one
is how Perl interprets this constant, the third one is how the constant is used.  
Note that the initial string form does not
contain string delimiters, and has backslashes in backslash-delimiter 
combinations stripped (thus the value of delimiter is not relevant for
processing of this string).  The return value of this function is how this 
constant is going to be interpreted by Perl.  The third argument is undefined
unless for overloaded \f(CWq\fR\- and \f(CWqr\fR\- constants, it is \f(CWq\fR in single-quote
context (comes from strings, regular expressions, and single-quote \s-1HERE\s0
documents), it is \f(CWtr\fR for arguments of \f(CWtr\fR/\f(CWy\fR operators, 
it is \f(CWs\fR for right-hand side of \f(CWs\fR\-operator, and it is \f(CWqq\fR otherwise.
.PP
Since an expression \f(CW"ab$cd,,"\fR is just a shortcut for \f(CW'ab' . $cd . ',,'\fR,
it is expected that overloaded constant strings are equipped with reasonable
overloaded catenation operator, otherwise absurd results will result.  
Similarly, negative numbers are considered as negations of positive constants.
.PP
Note that it is probably meaningless to call the functions \fIoverload::constant()\fR
and \fIoverload::remove_constant()\fR from anywhere but \fIimport()\fR and \fIunimport()\fR methods.
From these methods they may be called as
.PP
.Vb 6
\&        sub import {
\&          shift;
\&          return unless @_;
\&          die "unknown import: @_" unless @_ == 1 and $_[0] eq ':constant';
\&          overload::constant integer => sub {Math::BigInt->new(shift)};
\&        }
.Ve
\fB\s-1BUGS\s0\fR Currently overloaded-ness of constants does not propagate 
into \f(CWeval '...'\fR.
.SH "IMPLEMENTATION"
What follows is subject to change RSN.
.PP
The table of methods for all operations is cached in magic for the
symbol table hash for the package.  The cache is invalidated during
processing of \f(CWuse overload\fR, \f(CWno overload\fR, new function
definitions, and changes in \f(CW@ISA\fR. However, this invalidation remains
unprocessed until the next \f(CWbless\fRing into the package. Hence if you
want to change overloading structure dynamically, you'll need an
additional (fake) \f(CWbless\fRing to update the table.
.PP
(Every SVish thing has a magic queue, and magic is an entry in that
queue.  This is how a single variable may participate in multiple
forms of magic simultaneously.  For instance, environment variables
regularly have two forms at once: their \f(CW%ENV\fR magic and their taint
magic. However, the magic which implements overloading is applied to
the stashes, which are rarely used directly, thus should not slow down
Perl.)
.PP
If an object belongs to a package using overload, it carries a special
flag.  Thus the only speed penalty during arithmetic operations without
overloading is the checking of this flag.
.PP
In fact, if \f(CWuse overload\fR is not present, there is almost no overhead
for overloadable operations, so most programs should not suffer
measurable performance penalties.  A considerable effort was made to
minimize the overhead when overload is used in some package, but the
arguments in question do not belong to packages using overload.  When
in doubt, test your speed with \f(CWuse overload\fR and without it.  So far
there have been no reports of substantial speed degradation if Perl is
compiled with optimization turned on.
.PP
There is no size penalty for data if overload is not used. The only
size penalty if overload is used in some package is that \fIall\fR the
packages acquire a magic during the next \f(CWbless\fRing into the
package. This magic is three-words-long for packages without
overloading, and carries the cache tabel if the package is overloaded.
.PP
Copying (\f(CW$a=$b\fR) is shallow; however, a one-level-deep copying is 
carried out before any operation that can imply an assignment to the
object \f(CW$a\fR (or \f(CW$b\fR) refers to, like \f(CW$a++\fR.  You can override this
behavior by defining your own copy constructor (see the section on \fICopy Constructor\fR).
.PP
It is expected that arguments to methods that are not explicitly supposed
to be changed are constant (but this is not enforced).
.SH "Metaphor clash"
One may wonder why the semantic of overloaded \f(CW=\fR is so counterintuive.
If it \fIlooks\fR counterintuive to you, you are subject to a metaphor 
clash.  
.PP
Here is a Perl object metaphor:
.PP
\fI  object is a reference to blessed data\fR
.PP
and an arithmetic metaphor:
.PP
\fI  object is a thing by itself\fR.
.PP
The \fImain\fR problem of overloading \f(CW=\fR is the fact that these metaphors
imply different actions on the assignment \f(CW$a = $b\fR if \f(CW$a\fR and \f(CW$b\fR are
objects.  Perl-think implies that \f(CW$a\fR becomes a reference to whatever
\f(CW$b\fR was referencing.  Arithmetic-think implies that the value of \*(L"object\*(R"
\f(CW$a\fR is changed to become the value of the object \f(CW$b\fR, preserving the fact
that \f(CW$a\fR and \f(CW$b\fR are separate entities.
.PP
The difference is not relevant in the absence of mutators.  After
a Perl-way assignment an operation which mutates the data referenced by \f(CW$a\fR
would change the data referenced by \f(CW$b\fR too.  Effectively, after 
\f(CW$a = $b\fR values of \f(CW$a\fR and \f(CW$b\fR become \fIindistinguishable\fR.
.PP
On the other hand, anyone who has used algebraic notation knows the 
expressive power of the arithmetic metaphor.  Overloading works hard
to enable this metaphor while preserving the Perlian way as far as
possible.  Since it is not not possible to freely mix two contradicting
metaphors, overloading allows the arithmetic way to write things \fIas
far as all the mutators are called via overloaded access only\fR.  The
way it is done is described in the section on \fICopy Constructor\fR.
.PP
If some mutator methods are directly applied to the overloaded values,
one may need to \fIexplicitly unlink\fR other values which references the 
same value:
.PP
.Vb 6
\&    $a = new Data 23;
\&    ...
\&    $b = $a;            # $b is "linked" to $a
\&    ...
\&    $a = $a->clone;     # Unlink $b from $a
\&    $a->increment_by(4);
.Ve
Note that overloaded access makes this transparent:
.PP
.Vb 3
\&    $a = new Data 23;
\&    $b = $a;            # $b is "linked" to $a
\&    $a += 4;            # would unlink $b automagically
.Ve
However, it would not make
.PP
.Vb 2
\&    $a = new Data 23;
\&    $a = 4;             # Now $a is a plain 4, not 'Data'
.Ve
preserve \*(L"objectness\*(R" of \f(CW$a\fR.  But Perl \fIhas\fR a way to make assignments
to an object do whatever you want.  It is just not the overload, but
\fItie()\fRing interface (see the \f(CWtie\fR entry in the \fIperlfunc\fR manpage).  Adding a \fIFETCH()\fR method
which returns the object itself, and \fISTORE()\fR method which changes the 
value of the object, one can reproduce the arithmetic metaphor in its
completeness, at least for variables which were \fItie()\fRd from the start.
.PP
(Note that a workaround for a bug may be needed, see the section on \fIBUGS\fR.)
.SH "Cookbook"
Please add examples to what follows!
.Sh "Two-face scalars"
Put this in \fItwo_face.pm\fR in your Perl library directory:
.PP
.Vb 6
\&  package two_face;             # Scalars with separate string and
\&                                # numeric values.
\&  sub new { my $p = shift; bless [@_], $p }
\&  use overload '""' => \e&str, '0+' => \e&num, fallback => 1;
\&  sub num {shift->[1]}
\&  sub str {shift->[0]}
.Ve
Use it as follows:
.PP
.Vb 4
\&  require two_face;
\&  my $seven = new two_face ("vii", 7);
\&  printf "seven=$seven, seven=%d, eight=%d\en", $seven, $seven+1;
\&  print "seven contains `i'\en" if $seven =~ /i/;
.Ve
(The second line creates a scalar which has both a string value, and a
numeric value.)  This prints:
.PP
.Vb 2
\&  seven=vii, seven=7, eight=8
\&  seven contains `i'
.Ve
.Sh "Two-face references"
Suppose you want to create an object which is accessible as both an
array reference, and a hash reference, similar to the builtin
array-accessible-as-a-hash builtin Perl type.  Let us make it better than the builtin
type, there will be no restriction that you cannot use the index 0 of
your array.
.PP
.Vb 12
\&  package two_refs;
\&  use overload '%{}' => \e&gethash, '@{}' => sub { $ {shift()} };
\&  sub new { 
\&    my $p = shift; 
\&    bless \e [@_], $p;
\&  }
\&  sub gethash {
\&    my %h;
\&    my $self = shift;
\&    tie %h, ref $self, $self;
\&    \e%h;
\&  }
.Ve
.Vb 16
\&  sub TIEHASH { my $p = shift; bless \e shift, $p }
\&  my %fields;
\&  my $i = 0;
\&  $fields{$_} = $i++ foreach qw{zero one two three};
\&  sub STORE { 
\&    my $self = ${shift()};
\&    my $key = $fields{shift()};
\&    defined $key or die "Out of band access";
\&    $$self->[$key] = shift;
\&  }
\&  sub FETCH { 
\&    my $self = ${shift()};
\&    my $key = $fields{shift()};
\&    defined $key or die "Out of band access";
\&    $$self->[$key];
\&  }
.Ve
Now one can access an object using both the array and hash syntax:
.PP
.Vb 3
\&  my $bar = new two_refs 3,4,5,6;
\&  $bar->[2] = 11;
\&  $bar->{two} == 11 or die 'bad hash fetch';
.Ve
Note several important features of this example.  First of all, the
\fIactual\fR type of \f(CW$bar\fR is a scalar reference, and we do not overload
the scalar dereference.  Thus we can get the \fIactual\fR non-overloaded
contents of \f(CW$bar\fR by just using \f(CW$$bar\fR (what we do in functions which
overload dereference).  Similarly, the object returned by the
\fI\s-1TIEHASH\s0()\fR method is a scalar reference.
.PP
Second, we create a new tied hash each time the hash syntax is used.
This allows us not to worry about a possibility of a reference loop,
would would lead to a memory leak.
.PP
Both these problems can be cured.  Say, if we want to overload hash
dereference on a reference to an object which is \fIimplemented\fR as a
hash itself, the only problem one has to circumvent is how to access
this \fIactual\fR hash (as opposed to the \fIvirtual\fR exhibited by
overloaded dereference operator).  Here is one possible fetching routine:
.PP
.Vb 8
\&  sub access_hash {
\&    my ($self, $key) = (shift, shift);
\&    my $class = ref $self;
\&    bless $self, 'overload::dummy'; # Disable overloading of %{} 
\&    my $out = $self->{$key};
\&    bless $self, $class;        # Restore overloading
\&    $out;
\&  }
.Ve
To move creation of the tied hash on each access, one may an extra
level of indirection which allows a non-circular structure of references:
.PP
.Vb 16
\&  package two_refs1;
\&  use overload '%{}' => sub { ${shift()}->[1] },
\&               '@{}' => sub { ${shift()}->[0] };
\&  sub new { 
\&    my $p = shift; 
\&    my $a = [@_];
\&    my %h;
\&    tie %h, $p, $a;
\&    bless \e [$a, \e%h], $p;
\&  }
\&  sub gethash {
\&    my %h;
\&    my $self = shift;
\&    tie %h, ref $self, $self;
\&    \e%h;
\&  }
.Ve
.Vb 16
\&  sub TIEHASH { my $p = shift; bless \e shift, $p }
\&  my %fields;
\&  my $i = 0;
\&  $fields{$_} = $i++ foreach qw{zero one two three};
\&  sub STORE { 
\&    my $a = ${shift()};
\&    my $key = $fields{shift()};
\&    defined $key or die "Out of band access";
\&    $a->[$key] = shift;
\&  }
\&  sub FETCH { 
\&    my $a = ${shift()};
\&    my $key = $fields{shift()};
\&    defined $key or die "Out of band access";
\&    $a->[$key];
\&  }
.Ve
Now if \f(CW$baz\fR is overloaded like this, then \f(CW$bar\fR is a reference to a
reference to the intermediate array, which keeps a reference to an
actual array, and the access hash.  The \fItie()\fRing object for the access
hash is also a reference to a reference to the actual array, so 
.Ip "\(bu" 5
There are no loops of references.
.Ip "\(bu" 5
Both \*(L"objects\*(R" which are blessed into the class \f(CWtwo_refs1\fR are
references to a reference to an array, thus references to a \fIscalar\fR.
Thus the accessor expression \f(CW$$foo->[$ind]\fR involves no
overloaded operations.
.Sh "Symbolic calculator"
Put this in \fIsymbolic.pm\fR in your Perl library directory:
.PP
.Vb 2
\&  package symbolic;             # Primitive symbolic calculator
\&  use overload nomethod => \e&wrap;
.Ve
.Vb 6
\&  sub new { shift; bless ['n', @_] }
\&  sub wrap {
\&    my ($obj, $other, $inv, $meth) = @_;
\&    ($obj, $other) = ($other, $obj) if $inv;
\&    bless [$meth, $obj, $other];
\&  }
.Ve
This module is very unusual as overloaded modules go: it does not
provide any usual overloaded operators, instead it provides the the section on \fILast
Resort\fR operator \f(CWnomethod\fR.  In this example the corresponding
subroutine returns an object which encupsulates operations done over
the objects: \f(CWnew symbolic 3\fR contains \f(CW['n', 3]\fR, \f(CW2 + new
symbolic 3\fR contains \f(CW['+', 2, ['n', 3]]\fR.
.PP
Here is an example of the script which \*(L"calculates\*(R" the side of
circumscribed octagon using the above package:
.PP
.Vb 9
\&  require symbolic;
\&  my $iter = 1;                 # 2**($iter+2) = 8
\&  my $side = new symbolic 1;
\&  my $cnt = $iter;
\&  
\&  while ($cnt--) {
\&    $side = (sqrt(1 + $side**2) - 1)/$side;
\&  }
\&  print "OK\en";
.Ve
The value of \f(CW$side\fR is
.PP
.Vb 2
\&  ['/', ['-', ['sqrt', ['+', 1, ['**', ['n', 1], 2]],
\&                       undef], 1], ['n', 1]]
.Ve
Note that while we obtained this value using a nice little script,
there is no simple way to \fIuse\fR this value.  In fact this value may
be inspected in debugger (see the \fIperldebug\fR manpage), but ony if
\f(CWbareStringify\fR \fBO\fRption is set, and not via \f(CWp\fR command.
.PP
If one attempts to print this value, then the overloaded operator
\f(CW""\fR will be called, which will call \f(CWnomethod\fR operator.  The
result of this operator will be stringified again, but this result is
again of type \f(CWsymbolic\fR, which will lead to an infinite loop.
.PP
Add a pretty-printer method to the module \fIsymbolic.pm\fR:
.PP
.Vb 8
\&  sub pretty {
\&    my ($meth, $a, $b) = @{+shift};
\&    $a = 'u' unless defined $a;
\&    $b = 'u' unless defined $b;
\&    $a = $a->pretty if ref $a;
\&    $b = $b->pretty if ref $b;
\&    "[$meth $a $b]";
\&  } 
.Ve
Now one can finish the script by
.PP
.Vb 1
\&  print "side = ", $side->pretty, "\en";
.Ve
The method \f(CWpretty\fR is doing object-to-string conversion, so it
is natural to overload the operator \f(CW""\fR using this method.  However,
inside such a method it is not necessary to pretty-print the
\fIcomponents\fR \f(CW$a\fR and \f(CW$b\fR of an object.  In the above subroutine
\f(CW"[$meth $a $b]"\fR is a catenation of some strings and components \f(CW$a\fR
and \f(CW$b\fR.  If these components use overloading, the catenation operator
will look for an overloaded operator \f(CW.\fR, if not present, it will
look for an overloaded operator \f(CW""\fR.  Thus it is enough to use
.PP
.Vb 7
\&  use overload nomethod => \e&wrap, '""' => \e&str;
\&  sub str {
\&    my ($meth, $a, $b) = @{+shift};
\&    $a = 'u' unless defined $a;
\&    $b = 'u' unless defined $b;
\&    "[$meth $a $b]";
\&  } 
.Ve
Now one can change the last line of the script to
.PP
.Vb 1
\&  print "side = $side\en";
.Ve
which outputs
.PP
.Vb 1
\&  side = [/ [- [sqrt [+ 1 [** [n 1 u] 2]] u] 1] [n 1 u]]
.Ve
and one can inspect the value in debugger using all the possible
methods.  
.PP
Something is is still amiss: consider the loop variable \f(CW$cnt\fR of the
script.  It was a number, not an object.  We cannot make this value of
type \f(CWsymbolic\fR, since then the loop will not terminate.
.PP
Indeed, to terminate the cycle, the \f(CW$cnt\fR should become false.
However, the operator \f(CWbool\fR for checking falsity is overloaded (this
time via overloaded \f(CW""\fR), and returns a long string, thus any object
of type \f(CWsymbolic\fR is true.  To overcome this, we need a way to
compare an object to 0.  In fact, it is easier to write a numeric
conversion routine.
.PP
Here is the text of \fIsymbolic.pm\fR with such a routine added (and
slightly modifed \fIstr()\fR):
.PP
.Vb 3
\&  package symbolic;             # Primitive symbolic calculator
\&  use overload
\&    nomethod => \e&wrap, '""' => \e&str, '0+' => \e&num;
.Ve
.Vb 31
\&  sub new { shift; bless ['n', @_] }
\&  sub wrap {
\&    my ($obj, $other, $inv, $meth) = @_;
\&    ($obj, $other) = ($other, $obj) if $inv;
\&    bless [$meth, $obj, $other];
\&  }
\&  sub str {
\&    my ($meth, $a, $b) = @{+shift};
\&    $a = 'u' unless defined $a;
\&    if (defined $b) {
\&      "[$meth $a $b]";
\&    } else {
\&      "[$meth $a]";
\&    }
\&  } 
\&  my %subr = ( n => sub {$_[0]}, 
\&               sqrt => sub {sqrt $_[0]}, 
\&               '-' => sub {shift() - shift()},
\&               '+' => sub {shift() + shift()},
\&               '/' => sub {shift() / shift()},
\&               '*' => sub {shift() * shift()},
\&               '**' => sub {shift() ** shift()},
\&             );
\&  sub num {
\&    my ($meth, $a, $b) = @{+shift};
\&    my $subr = $subr{$meth} 
\&      or die "Do not know how to ($meth) in symbolic";
\&    $a = $a->num if ref $a eq __PACKAGE__;
\&    $b = $b->num if ref $b eq __PACKAGE__;
\&    $subr->($a,$b);
\&  }
.Ve
All the work of numeric conversion is done in \f(CW%subr\fR and \fInum()\fR.  Of
course, \f(CW%subr\fR is not complete, it contains only operators used in teh
example below.  Here is the extra-credit question: why do we need an
explicit recursion in \fInum()\fR?  (Answer is at the end of this section.)
.PP
Use this module like this:
.PP
.Vb 11
\&  require symbolic;
\&  my $iter = new symbolic 2;    # 16-gon
\&  my $side = new symbolic 1;
\&  my $cnt = $iter;
\&  
\&  while ($cnt) {
\&    $cnt = $cnt - 1;            # Mutator `--' not implemented
\&    $side = (sqrt(1 + $side**2) - 1)/$side;
\&  }
\&  printf "%s=%f\en", $side, $side;
\&  printf "pi=%f\en", $side*(2**($iter+2));
.Ve
It prints (without so many line breaks)
.PP
.Vb 4
\&  [/ [- [sqrt [+ 1 [** [/ [- [sqrt [+ 1 [** [n 1] 2]]] 1]
\&                          [n 1]] 2]]] 1]
\&     [/ [- [sqrt [+ 1 [** [n 1] 2]]] 1] [n 1]]]=0.198912
\&  pi=3.182598
.Ve
The above module is very primitive.  It does not implement
mutator methods (\f(CW++\fR, \f(CW-=\fR and so on), does not do deep copying
(not required without mutators!), and implements only those arithmetic
operations which are used in the example.
.PP
To implement most arithmetic operattions is easy, one should just use
the tables of operations, and change the code which fills \f(CW%subr\fR to
.PP
.Vb 12
\&  my %subr = ( 'n' => sub {$_[0]} );
\&  foreach my $op (split " ", $overload::ops{with_assign}) {
\&    $subr{$op} = $subr{"$op="} = eval "sub {shift() $op shift()}";
\&  }
\&  my @bins = qw(binary 3way_comparison num_comparison str_comparison);
\&  foreach my $op (split " ", "@overload::ops{ @bins }") {
\&    $subr{$op} = eval "sub {shift() $op shift()}";
\&  }
\&  foreach my $op (split " ", "@overload::ops{qw(unary func)}") {
\&    print "defining `$op'\en";
\&    $subr{$op} = eval "sub {$op shift()}";
\&  }
.Ve
Due to the section on \fICalling Conventions for Mutators\fR, we do not need anything
special to make \f(CW+=\fR and friends work, except filling \f(CW+=\fR entry of
\f(CW%subr\fR, and defining a copy constructor (needed since Perl has no
way to know that the implementation of \f(CW'+='\fR does not mutate
the argument, compare the section on \fICopy Constructor\fR).
.PP
To implement a copy constructor, add \f(CW'=' =\fR \e&cpy> to \f(CWuse overload\fR
line, and code (this code assumes that mutators change things one level
deep only, so recursive copying is not needed):
.PP
.Vb 4
\&  sub cpy {
\&    my $self = shift;
\&    bless [@$self], ref $self;
\&  }
.Ve
To make \f(CW++\fR and \f(CW--\fR work, we need to implement actual mutators, 
either directly, or in \f(CWnomethod\fR.  We continue to do things inside
\f(CWnomethod\fR, thus add
.PP
.Vb 4
\&    if ($meth eq '++' or $meth eq '--') {
\&      @$obj = ($meth, (bless [@$obj]), 1); # Avoid circular reference
\&      return $obj;
\&    }
.Ve
after the first line of \fIwrap()\fR.  This is not a most effective 
implementation, one may consider
.PP
.Vb 1
\&  sub inc { $_[0] = bless ['++', shift, 1]; }
.Ve
instead.
.PP
As a final remark, note that one can fill \f(CW%subr\fR by
.PP
.Vb 13
\&  my %subr = ( 'n' => sub {$_[0]} );
\&  foreach my $op (split " ", $overload::ops{with_assign}) {
\&    $subr{$op} = $subr{"$op="} = eval "sub {shift() $op shift()}";
\&  }
\&  my @bins = qw(binary 3way_comparison num_comparison str_comparison);
\&  foreach my $op (split " ", "@overload::ops{ @bins }") {
\&    $subr{$op} = eval "sub {shift() $op shift()}";
\&  }
\&  foreach my $op (split " ", "@overload::ops{qw(unary func)}") {
\&    $subr{$op} = eval "sub {$op shift()}";
\&  }
\&  $subr{'++'} = $subr{'+'};
\&  $subr{'--'} = $subr{'-'};
.Ve
This finishes implementation of a primitive symbolic calculator in 
50 lines of Perl code.  Since the numeric values of subexpressions 
are not cached, the calculator is very slow.
.PP
Here is the answer for the exercise: In the case of \fIstr()\fR, we need no
explicit recursion since the overloaded \f(CW.\fR\-operator will fall back
to an existing overloaded operator \f(CW""\fR.  Overloaded arithmetic
operators \fIdo not\fR fall back to numeric conversion if \f(CWfallback\fR is
not explicitly requested.  Thus without an explicit recursion \fInum()\fR
would convert \f(CW['+', $a, $b]\fR to \f(CW$a + $b\fR, which would just rebuild
the argument of \fInum()\fR.
.PP
If you wonder why defaults for conversion are different for \fIstr()\fR and
\fInum()\fR, note how easy it was to write the symbolic calculator.  This
simplicity is due to an appropriate choice of defaults.  One extra
note: due to teh explicit recursion \fInum()\fR is more fragile than \fIsym()\fR:
we need to explicitly check for the type of \f(CW$a\fR and \f(CW$b\fR.  If componets
\f(CW$a\fR and \f(CW$b\fR happen to be of some related type, this may lead to problems.
.Sh "\fIReally\fR symbolic calculator"
One may wonder why we call the above calculator symbolic.  The reason
is that the actual calculation of the value of expression is postponed
until the value is \fIused\fR.
.PP
To see it in action, add a method
.PP
.Vb 5
\&  sub STORE { 
\&    my $obj = shift; 
\&    $#$obj = 1; 
\&    @$obj->[0,1] = ('=', shift);
\&  }
.Ve
to the package \f(CWsymbolic\fR.  After this change one can do
.PP
.Vb 3
\&  my $a = new symbolic 3;
\&  my $b = new symbolic 4;
\&  my $c = sqrt($a**2 + $b**2);
.Ve
and the numeric value of \f(CW$c\fR becomes 5.  However, after calling
.PP
.Vb 1
\&  $a->STORE(12);  $b->STORE(5);
.Ve
the numeric value of \f(CW$c\fR becomes 13.  There is no doubt now that the module
symbolic provides a \fIsymbolic\fR calculator indeed.
.PP
To hide the rough edges under the hood, provide a \fItie()\fRd interface to the
package \f(CWsymbolic\fR (compare with the section on \fIMetaphor clash\fR).  Add methods
.PP
.Vb 3
\&  sub TIESCALAR { my $pack = shift; $pack->new(@_) }
\&  sub FETCH { shift }
\&  sub nop {  }          # Around a bug
.Ve
(the bug is described in the section on \fI\s-1BUGS\s0\fR).  One can use this new interface as
.PP
.Vb 3
\&  tie $a, 'symbolic', 3;
\&  tie $b, 'symbolic', 4;
\&  $a->nop;  $b->nop;    # Around a bug
.Ve
.Vb 1
\&  my $c = sqrt($a**2 + $b**2);
.Ve
Now numeric value of \f(CW$c\fR is 5.  After \f(CW$a = 12; $b = 5\fR the numeric value
of \f(CW$c\fR becomes 13.  To insulate the user of the module add a method
.PP
.Vb 1
\&  sub vars { my $p = shift; tie($_, $p), $_->nop foreach @_; }
.Ve
Now
.PP
.Vb 3
\&  my ($a, $b);
\&  symbolic->vars($a, $b);
\&  my $c = sqrt($a**2 + $b**2);
.Ve
.Vb 2
\&  $a = 3; $b = 4;
\&  printf "c5  %s=%f\en", $c, $c;
.Ve
.Vb 2
\&  $a = 12; $b = 5;
\&  printf "c13  %s=%f\en", $c, $c;
.Ve
shows that the numeric value of \f(CW$c\fR follows changes to the values of \f(CW$a\fR
and \f(CW$b\fR.
.SH "AUTHOR"
Ilya Zakharevich <\fIilya@math.mps.ohio-state.edu\fR>.
.SH "DIAGNOSTICS"
When Perl is run with the \fB\-Do\fR switch or its equivalent, overloading
induces diagnostic messages.
.PP
Using the \f(CWm\fR command of Perl debugger (see the \fIperldebug\fR manpage) one can
deduce which operations are overloaded (and which ancestor triggers
this overloading). Say, if \f(CWeq\fR is overloaded, then the method \f(CW(eq\fR
is shown by debugger. The method \f(CW()\fR corresponds to the \f(CWfallback\fR
key (in fact a presence of this method shows that this package has
overloading enabled, and it is what is used by the \f(CWOverloaded\fR
function of module \f(CWoverload\fR).
.SH "BUGS"
Because it is used for overloading, the per-package hash \f(CW%OVERLOAD\fR now
has a special meaning in Perl. The symbol table is filled with names
looking like line-noise.
.PP
For the purpose of inheritance every overloaded package behaves as if
\f(CWfallback\fR is present (possibly undefined). This may create
interesting effects if some package is not overloaded, but inherits
from two overloaded packages.
.PP
Relation between overloading and \fItie()\fRing is broken.  Overloading is 
triggered or not basing on the \fIprevious\fR class of \fItie()\fRd value.
.PP
This happens because the presence of overloading is checked too early, 
before any \fItie()\fRd access is attempted.  If the \fIFETCH()\fRed class of the
\fItie()\fRd value does not change, a simple workaround is to access the value 
immediately after \fItie()\fRing, so that after this call the \fIprevious\fR class
coincides with the current one.
.PP
\fBNeeded:\fR a way to fix this without a speed penalty.
.PP
Barewords are not covered by overloaded string constants.
.PP
This document is confusing.  There are grammos and misleading language
used in places.  It would seem a total rewrite is needed.

.rn }` ''
.IX Title "overload 3"
.IX Name "overload - Package for overloading perl operations"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "CAVEAT SCRIPTOR"

.IX Header "DESCRIPTION"

.IX Subsection "Declaration of overloaded functions"

.IX Subsection "Calling Conventions for Binary Operations"

.IX Item "\s-1FALSE\s0"

.IX Item "\s-1TRUE\s0"

.IX Item "\f(CWundef\fR"

.IX Subsection "Calling Conventions for Unary Operations"

.IX Subsection "Calling Conventions for Mutators"

.IX Item "\f(CW++\fR and \f(CW--\fR"

.IX Item "\f(CWx=\fR and other assignment versions"

.IX Subsection "Overloadable Operations"

.IX Item "\(bu \fIArithmetic operations\fR"

.IX Item "\(bu \fIComparison operations\fR"

.IX Item "\(bu \fIBit operations\fR"

.IX Item "\(bu \fIIncrement and decrement\fR"

.IX Item "\(bu \fITranscendental functions\fR"

.IX Item "\(bu \fIBoolean, string and numeric conversion\fR"

.IX Item "\(bu \fIIteration\fR"

.IX Item "\(bu \fIDereferencing\fR"

.IX Item "\(bu \fISpecial\fR"

.IX Subsection "Inheritance and overloading"

.IX Item "Strings as values of \f(CWuse overload\fR directive"

.IX Item "Overloading of an operation is inherited by derived classes"

.IX Header "SPECIAL SYMBOLS FOR \f(CWuse overload\fR"

.IX Subsection "Last Resort"

.IX Subsection "Fallback "

.IX Item "\(bu \f(CWundef\fR"

.IX Item "\(bu \s-1TRUE\s0"

.IX Item "\(bu defined, but \s-1FALSE\s0"

.IX Subsection "Copy Constructor"

.IX Item "\fBExample\fR"

.IX Header "MAGIC AUTOGENERATION"

.IX Item "\fIAssignment forms of arithmetic operations\fR"

.IX Item "\fIConversion operations\fR "

.IX Item "\fIIncrement and decrement\fR"

.IX Item "\f(CWabs($a)\fR"

.IX Item "\fIUnary minus\fR"

.IX Item "\fINegation\fR"

.IX Item "\fIConcatenation\fR"

.IX Item "\fIComparison operations\fR "

.IX Item "\fIIterator\fR"

.IX Item "\fIDereferencing\fR"

.IX Item "\fICopy operator\fR"

.IX Header "Losing overloading"

.IX Header "Run-time Overloading"

.IX Header "Public functions"

.IX Item "overload::StrVal(arg)"

.IX Item "overload::Overloaded(arg)"

.IX Item "overload::Method(obj,op)"

.IX Header "Overloading constants"

.IX Item "integer"

.IX Item "float"

.IX Item "binary"

.IX Item "q"

.IX Item "qr"

.IX Header "IMPLEMENTATION"

.IX Header "Metaphor clash"

.IX Header "Cookbook"

.IX Subsection "Two-face scalars"

.IX Subsection "Two-face references"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Subsection "Symbolic calculator"

.IX Subsection "\fIReally\fR symbolic calculator"

.IX Header "AUTHOR"

.IX Header "DIAGNOSTICS"

.IX Header "BUGS"

