.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH POSIX 3 "perl 5.004, patch 55" "25/Nov/97" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
POSIX \- Perl interface to IEEE Std 1003.1
.SH "SYNOPSIS"
.PP
.Vb 3
\&    use POSIX;
\&    use POSIX qw(setsid);
\&    use POSIX qw(:errno_h :fcntl_h);
.Ve
.Vb 1
\&    printf "EINTR is %d\en", EINTR;
.Ve
.Vb 1
\&    $sess_id = POSIX::setsid();
.Ve
.Vb 2
\&    $fd = POSIX::open($path, O_CREAT|O_EXCL|O_WRONLY, 0644);
\&        # note: that's a filedescriptor, *NOT* a filehandle
.Ve
.SH "DESCRIPTION"
The POSIX module permits you to access all (or nearly all) the standard
POSIX 1003.1 identifiers.  Many of these identifiers have been given Perl-ish
interfaces.  Things which are \f(CW#defines\fR in C, like EINTR or O_NDELAY, are
automatically exported into your namespace.  All functions are only exported
if you ask for them explicitly.  Most likely people will prefer to use the
fully-qualified function names.
.PP
This document gives a condensed list of the features available in the POSIX
module.  Consult your operating system's manpages for general information on
most features.  Consult the \fIperlfunc\fR manpage for functions which are noted as being
identical to Perl's builtin functions.
.PP
The first section describes POSIX functions from the 1003.1 specification.
The second section describes some classes for signal objects, TTY objects,
and other miscellaneous objects.  The remaining sections list various
constants and macros in an organization which roughly follows IEEE Std
1003.1b-1993.
.SH "NOTE"
The POSIX module is probably the most complex Perl module supplied with
the standard distribution.  It incorporates autoloading, namespace games,
and dynamic loading of code that's in Perl, C, or both.  It's a great
source of wisdom.
.SH "CAVEATS"
A few functions are not implemented because they are C specific.  If you
attempt to call these, they will print a message telling you that they
aren't implemented, and suggest using the Perl equivalent should one
exist.  For example, trying to access the \fIsetjmp()\fR call will elicit the
message \*(L"\fIsetjmp()\fR is C\-specific: use eval {} instead\*(R".
.PP
Furthermore, some evil vendors will claim 1003.1 compliance, but in fact
are not so: they will not pass the PCTS (POSIX Compliance Test Suites).
For example, one vendor may not define EDEADLK, or the semantics of the
errno values set by \fIopen\fR\|(2) might not be quite right.  Perl does not
attempt to verify POSIX compliance.  That means you can currently
successfully say \*(L"use POSIX\*(R",  and then later in your program you find
that your vendor has been lax and there's no usable ICANON macro after
all.  This could be construed to be a bug.
.SH "FUNCTIONS"
.Ip "_exit" 8
This is identical to the C function \f(CW_exit()\fR.
.Ip "abort" 8
This is identical to the C function \f(CWabort()\fR.
.Ip "abs" 8
This is identical to Perl's builtin \f(CWabs()\fR function.
.Ip "access" 8
Determines the accessibility of a file.
.Sp
.Vb 3
\&        if( POSIX::access( "/", &POSIX::R_OK ) ){
\&                print "have read permission\en";
\&        }
.Ve
Returns \f(CWundef\fR on failure.
.Ip "acos" 8
This is identical to the C function \f(CWacos()\fR.
.Ip "alarm" 8
This is identical to Perl's builtin \f(CWalarm()\fR function.
.Ip "asctime" 8
This is identical to the C function \f(CWasctime()\fR.
.Ip "asin" 8
This is identical to the C function \f(CWasin()\fR.
.Ip "assert" 8
Unimplemented.
.Ip "atan" 8
This is identical to the C function \f(CWatan()\fR.
.Ip "atan2" 8
This is identical to Perl's builtin \f(CWatan2()\fR function.
.Ip "atexit" 8
\fIatexit()\fR is C\-specific: use \s-1END\s0 {} instead.
.Ip "atof" 8
\fIatof()\fR is C\-specific.
.Ip "atoi" 8
\fIatoi()\fR is C\-specific.
.Ip "atol" 8
\fIatol()\fR is C\-specific.
.Ip "bsearch" 8
\fIbsearch()\fR not supplied.
.Ip "calloc" 8
\fIcalloc()\fR is C\-specific.
.Ip "ceil" 8
This is identical to the C function \f(CWceil()\fR.
.Ip "chdir" 8
This is identical to Perl's builtin \f(CWchdir()\fR function.
.Ip "chmod" 8
This is identical to Perl's builtin \f(CWchmod()\fR function.
.Ip "chown" 8
This is identical to Perl's builtin \f(CWchown()\fR function.
.Ip "clearerr" 8
Use method \f(CWIO::Handle::clearerr()\fR instead.
.Ip "clock" 8
This is identical to the C function \f(CWclock()\fR.
.Ip "close" 8
Close the file.  This uses file descriptors such as those obtained by calling
\f(CWPOSIX::open\fR.
.Sp
.Vb 2
\&        $fd = POSIX::open( "foo", &POSIX::O_RDONLY );
\&        POSIX::close( $fd );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "closedir" 8
This is identical to Perl's builtin \f(CWclosedir()\fR function.
.Ip "cos" 8
This is identical to Perl's builtin \f(CWcos()\fR function.
.Ip "cosh" 8
This is identical to the C function \f(CWcosh()\fR.
.Ip "creat" 8
Create a new file.  This returns a file descriptor like the ones returned by
\f(CWPOSIX::open\fR.  Use \f(CWPOSIX::close\fR to close the file.
.Sp
.Vb 2
\&        $fd = POSIX::creat( "foo", 0611 );
\&        POSIX::close( $fd );
.Ve
.Ip "ctermid" 8
Generates the path name for the controlling terminal.
.Sp
.Vb 1
\&        $path = POSIX::ctermid();
.Ve
.Ip "ctime" 8
This is identical to the C function \f(CWctime()\fR.
.Ip "cuserid" 8
Get the character login name of the user.
.Sp
.Vb 1
\&        $name = POSIX::cuserid();
.Ve
.Ip "difftime" 8
This is identical to the C function \f(CWdifftime()\fR.
.Ip "div" 8
\fIdiv()\fR is C\-specific.
.Ip "dup" 8
This is similar to the C function \f(CWdup()\fR.
.Sp
This uses file descriptors such as those obtained by calling
\f(CWPOSIX::open\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "dup2" 8
This is similar to the C function \f(CWdup2()\fR.
.Sp
This uses file descriptors such as those obtained by calling
\f(CWPOSIX::open\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "errno" 8
Returns the value of errno.
.Sp
.Vb 1
\&        $errno = POSIX::errno();
.Ve
.Ip "execl" 8
\fIexecl()\fR is C\-specific.
.Ip "execle" 8
\fIexecle()\fR is C\-specific.
.Ip "execlp" 8
\fIexeclp()\fR is C\-specific.
.Ip "execv" 8
\fIexecv()\fR is C\-specific.
.Ip "execve" 8
\fIexecve()\fR is C\-specific.
.Ip "execvp" 8
\fIexecvp()\fR is C\-specific.
.Ip "exit" 8
This is identical to Perl's builtin \f(CWexit()\fR function.
.Ip "exp" 8
This is identical to Perl's builtin \f(CWexp()\fR function.
.Ip "fabs" 8
This is identical to Perl's builtin \f(CWabs()\fR function.
.Ip "fclose" 8
Use method \f(CWIO::Handle::close()\fR instead.
.Ip "fcntl" 8
This is identical to Perl's builtin \f(CWfcntl()\fR function.
.Ip "fdopen" 8
Use method \f(CWIO::Handle::new_from_fd()\fR instead.
.Ip "feof" 8
Use method \f(CWIO::Handle::eof()\fR instead.
.Ip "ferror" 8
Use method \f(CWIO::Handle::error()\fR instead.
.Ip "fflush" 8
Use method \f(CWIO::Handle::flush()\fR instead.
.Ip "fgetc" 8
Use method \f(CWIO::Handle::getc()\fR instead.
.Ip "fgetpos" 8
Use method \f(CWIO::Seekable::getpos()\fR instead.
.Ip "fgets" 8
Use method \f(CWIO::Handle::gets()\fR instead.
.Ip "fileno" 8
Use method \f(CWIO::Handle::fileno()\fR instead.
.Ip "floor" 8
This is identical to the C function \f(CWfloor()\fR.
.Ip "fmod" 8
This is identical to the C function \f(CWfmod()\fR.
.Ip "fopen" 8
Use method \f(CWIO::File::open()\fR instead.
.Ip "fork" 8
This is identical to Perl's builtin \f(CWfork()\fR function.
.Ip "fpathconf" 8
Retrieves the value of a configurable limit on a file or directory.  This
uses file descriptors such as those obtained by calling \f(CWPOSIX::open\fR.
.Sp
The following will determine the maximum length of the longest allowable
pathname on the filesystem which holds \f(CW/tmp/foo\fR.
.Sp
.Vb 2
\&        $fd = POSIX::open( "/tmp/foo", &POSIX::O_RDONLY );
\&        $path_max = POSIX::fpathconf( $fd, &POSIX::_PC_PATH_MAX );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "fprintf" 8
\fIfprintf()\fR is C\-specific\*(--use printf instead.
.Ip "fputc" 8
\fIfputc()\fR is C\-specific\*(--use print instead.
.Ip "fputs" 8
\fIfputs()\fR is C\-specific\*(--use print instead.
.Ip "fread" 8
\fIfread()\fR is C\-specific\*(--use read instead.
.Ip "free" 8
\fIfree()\fR is C\-specific.
.Ip "freopen" 8
\fIfreopen()\fR is C\-specific\*(--use open instead.
.Ip "frexp" 8
Return the mantissa and exponent of a floating-point number.
.Sp
.Vb 1
\&        ($mantissa, $exponent) = POSIX::frexp( 3.14 );
.Ve
.Ip "fscanf" 8
\fIfscanf()\fR is C\-specific\*(--use <> and regular expressions instead.
.Ip "fseek" 8
Use method \f(CWIO::Seekable::seek()\fR instead.
.Ip "fsetpos" 8
Use method \f(CWIO::Seekable::setpos()\fR instead.
.Ip "fstat" 8
Get file status.  This uses file descriptors such as those obtained by
calling \f(CWPOSIX::open\fR.  The data returned is identical to the data from
Perl's builtin \f(CWstat\fR function.
.Sp
.Vb 2
\&        $fd = POSIX::open( "foo", &POSIX::O_RDONLY );
\&        @stats = POSIX::fstat( $fd );
.Ve
.Ip "ftell" 8
Use method \f(CWIO::Seekable::tell()\fR instead.
.Ip "fwrite" 8
\fIfwrite()\fR is C\-specific\*(--use print instead.
.Ip "getc" 8
This is identical to Perl's builtin \f(CWgetc()\fR function.
.Ip "getchar" 8
Returns one character from \s-1STDIN\s0.
.Ip "getcwd" 8
Returns the name of the current working directory.
.Ip "getegid" 8
Returns the effective group id.
.Ip "getenv" 8
Returns the value of the specified enironment variable.
.Ip "geteuid" 8
Returns the effective user id.
.Ip "getgid" 8
Returns the user's real group id.
.Ip "getgrgid" 8
This is identical to Perl's builtin \f(CWgetgrgid()\fR function.
.Ip "getgrnam" 8
This is identical to Perl's builtin \f(CWgetgrnam()\fR function.
.Ip "getgroups" 8
Returns the ids of the user's supplementary groups.
.Ip "getlogin" 8
This is identical to Perl's builtin \f(CWgetlogin()\fR function.
.Ip "getpgrp" 8
This is identical to Perl's builtin \f(CWgetpgrp()\fR function.
.Ip "getpid" 8
Returns the process's id.
.Ip "getppid" 8
This is identical to Perl's builtin \f(CWgetppid()\fR function.
.Ip "getpwnam" 8
This is identical to Perl's builtin \f(CWgetpwnam()\fR function.
.Ip "getpwuid" 8
This is identical to Perl's builtin \f(CWgetpwuid()\fR function.
.Ip "gets" 8
Returns one line from \s-1STDIN\s0.
.Ip "getuid" 8
Returns the user's id.
.Ip "gmtime" 8
This is identical to Perl's builtin \f(CWgmtime()\fR function.
.Ip "isalnum" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isalpha" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isatty" 8
Returns a boolean indicating whether the specified filehandle is connected
to a tty.
.Ip "iscntrl" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isdigit" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isgraph" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "islower" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isprint" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "ispunct" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isspace" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isupper" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "isxdigit" 8
This is identical to the C function, except that it can apply to a single
character or to a whole string.
.Ip "kill" 8
This is identical to Perl's builtin \f(CWkill()\fR function.
.Ip "labs" 8
\fIlabs()\fR is C\-specific, use abs instead.
.Ip "ldexp" 8
This is identical to the C function \f(CWldexp()\fR.
.Ip "ldiv" 8
\fIldiv()\fR is C\-specific, use / and int instead.
.Ip "link" 8
This is identical to Perl's builtin \f(CWlink()\fR function.
.Ip "localeconv" 8
Get numeric formatting information.  Returns a reference to a hash
containing the current locale formatting values.
.Sp
The database for the \fBde\fR (Deutsch or German) locale.
.Sp
.Vb 21
\&        $loc = POSIX::setlocale( &POSIX::LC_ALL, "de" );
\&        print "Locale = $loc\en";
\&        $lconv = POSIX::localeconv();
\&        print "decimal_point    = ", $lconv->{decimal_point},   "\en";
\&        print "thousands_sep    = ", $lconv->{thousands_sep},   "\en";
\&        print "grouping = ", $lconv->{grouping},        "\en";
\&        print "int_curr_symbol  = ", $lconv->{int_curr_symbol}, "\en";
\&        print "currency_symbol  = ", $lconv->{currency_symbol}, "\en";
\&        print "mon_decimal_point = ", $lconv->{mon_decimal_point}, "\en";
\&        print "mon_thousands_sep = ", $lconv->{mon_thousands_sep}, "\en";
\&        print "mon_grouping     = ", $lconv->{mon_grouping},    "\en";
\&        print "positive_sign    = ", $lconv->{positive_sign},   "\en";
\&        print "negative_sign    = ", $lconv->{negative_sign},   "\en";
\&        print "int_frac_digits  = ", $lconv->{int_frac_digits}, "\en";
\&        print "frac_digits      = ", $lconv->{frac_digits},     "\en";
\&        print "p_cs_precedes    = ", $lconv->{p_cs_precedes},   "\en";
\&        print "p_sep_by_space   = ", $lconv->{p_sep_by_space},  "\en";
\&        print "n_cs_precedes    = ", $lconv->{n_cs_precedes},   "\en";
\&        print "n_sep_by_space   = ", $lconv->{n_sep_by_space},  "\en";
\&        print "p_sign_posn      = ", $lconv->{p_sign_posn},     "\en";
\&        print "n_sign_posn      = ", $lconv->{n_sign_posn},     "\en";
.Ve
.Ip "localtime" 8
This is identical to Perl's builtin \f(CWlocaltime()\fR function.
.Ip "log" 8
This is identical to Perl's builtin \f(CWlog()\fR function.
.Ip "log10" 8
This is identical to the C function \f(CWlog10()\fR.
.Ip "longjmp" 8
\fIlongjmp()\fR is C\-specific: use die instead.
.Ip "lseek" 8
Move the file's read/write position.  This uses file descriptors such as
those obtained by calling \f(CWPOSIX::open\fR.
.Sp
.Vb 2
\&        $fd = POSIX::open( "foo", &POSIX::O_RDONLY );
\&        $off_t = POSIX::lseek( $fd, 0, &POSIX::SEEK_SET );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "malloc" 8
\fImalloc()\fR is C\-specific.
.Ip "mblen" 8
This is identical to the C function \f(CWmblen()\fR.
.Ip "mbstowcs" 8
This is identical to the C function \f(CWmbstowcs()\fR.
.Ip "mbtowc" 8
This is identical to the C function \f(CWmbtowc()\fR.
.Ip "memchr" 8
\fImemchr()\fR is C\-specific, use \fIindex()\fR instead.
.Ip "memcmp" 8
\fImemcmp()\fR is C\-specific, use eq instead.
.Ip "memcpy" 8
\fImemcpy()\fR is C\-specific, use = instead.
.Ip "memmove" 8
\fImemmove()\fR is C\-specific, use = instead.
.Ip "memset" 8
\fImemset()\fR is C\-specific, use x instead.
.Ip "mkdir" 8
This is identical to Perl's builtin \f(CWmkdir()\fR function.
.Ip "mkfifo" 8
This is similar to the C function \f(CWmkfifo()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "mktime" 8
Convert date/time info to a calendar time.
.Sp
Synopsis:
.Sp
.Vb 1
\&        mktime(sec, min, hour, mday, mon, year, wday = 0, yday = 0, isdst = 0)
.Ve
The month (\f(CWmon\fR), weekday (\f(CWwday\fR), and yearday (\f(CWyday\fR) begin at zero.
I.e. January is 0, not 1; Sunday is 0, not 1; January 1st is 0, not 1.  The
year (\f(CWyear\fR) is given in years since 1900.  I.e. The year 1995 is 95; the
year 2001 is 101.  Consult your system's \f(CWmktime()\fR manpage for details
about these and the other arguments.
.Sp
Calendar time for December 12, 1995, at 10:30 am.
.Sp
.Vb 2
\&        $time_t = POSIX::mktime( 0, 30, 10, 12, 11, 95 );
\&        print "Date = ", POSIX::ctime($time_t);
.Ve
Returns \f(CWundef\fR on failure.
.Ip "modf" 8
Return the integral and fractional parts of a floating-point number.
.Sp
.Vb 1
\&        ($fractional, $integral) = POSIX::modf( 3.14 );
.Ve
.Ip "nice" 8
This is similar to the C function \f(CWnice()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "offsetof" 8
\fIoffsetof()\fR is C\-specific.
.Ip "open" 8
Open a file for reading for writing.  This returns file descriptors, not
Perl filehandles.  Use \f(CWPOSIX::close\fR to close the file.
.Sp
Open a file read-only with mode 0666.
.Sp
.Vb 1
\&        $fd = POSIX::open( "foo" );
.Ve
Open a file for read and write.
.Sp
.Vb 1
\&        $fd = POSIX::open( "foo", &POSIX::O_RDWR );
.Ve
Open a file for write, with truncation.
.Sp
.Vb 1
\&        $fd = POSIX::open( "foo", &POSIX::O_WRONLY | &POSIX::O_TRUNC );
.Ve
Create a new file with mode 0640.  Set up the file for writing.
.Sp
.Vb 1
\&        $fd = POSIX::open( "foo", &POSIX::O_CREAT | &POSIX::O_WRONLY, 0640 );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "opendir" 8
Open a directory for reading.
.Sp
.Vb 3
\&        $dir = POSIX::opendir( "/tmp" );
\&        @files = POSIX::readdir( $dir );
\&        POSIX::closedir( $dir );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "pathconf" 8
Retrieves the value of a configurable limit on a file or directory.
.Sp
The following will determine the maximum length of the longest allowable
pathname on the filesystem which holds \f(CW/tmp\fR.
.Sp
.Vb 1
\&        $path_max = POSIX::pathconf( "/tmp", &POSIX::_PC_PATH_MAX );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "pause" 8
This is similar to the C function \f(CWpause()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "perror" 8
This is identical to the C function \f(CWperror()\fR.
.Ip "pipe" 8
Create an interprocess channel.  This returns file descriptors like those
returned by \f(CWPOSIX::open\fR.
.Sp
.Vb 3
\&        ($fd0, $fd1) = POSIX::pipe();
\&        POSIX::write( $fd0, "hello", 5 );
\&        POSIX::read( $fd1, $buf, 5 );
.Ve
.Ip "pow" 8
Computes \f(CW$x\fR raised to the power \f(CW$exponent\fR.
.Sp
.Vb 1
\&        $ret = POSIX::pow( $x, $exponent );
.Ve
.Ip "printf" 8
Prints the specified arguments to \s-1STDOUT\s0.
.Ip "putc" 8
\fIputc()\fR is C\-specific\*(--use print instead.
.Ip "putchar" 8
\fIputchar()\fR is C\-specific\*(--use print instead.
.Ip "puts" 8
\fIputs()\fR is C\-specific\*(--use print instead.
.Ip "qsort" 8
\fIqsort()\fR is C\-specific, use sort instead.
.Ip "raise" 8
Sends the specified signal to the current process.
.Ip "rand" 8
\fIrand()\fR is non-portable, use Perl's rand instead.
.Ip "read" 8
Read from a file.  This uses file descriptors such as those obtained by
calling \f(CWPOSIX::open\fR.  If the buffer \f(CW$buf\fR is not large enough for the
read then Perl will extend it to make room for the request.
.Sp
.Vb 2
\&        $fd = POSIX::open( "foo", &POSIX::O_RDONLY );
\&        $bytes = POSIX::read( $fd, $buf, 3 );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "readdir" 8
This is identical to Perl's builtin \f(CWreaddir()\fR function.
.Ip "realloc" 8
\fIrealloc()\fR is C\-specific.
.Ip "remove" 8
This is identical to Perl's builtin \f(CWunlink()\fR function.
.Ip "rename" 8
This is identical to Perl's builtin \f(CWrename()\fR function.
.Ip "rewind" 8
Seeks to the beginning of the file.
.Ip "rewinddir" 8
This is identical to Perl's builtin \f(CWrewinddir()\fR function.
.Ip "rmdir" 8
This is identical to Perl's builtin \f(CWrmdir()\fR function.
.Ip "scanf" 8
\fIscanf()\fR is C\-specific\*(--use <> and regular expressions instead.
.Ip "setgid" 8
Sets the real group id for this process.
.Ip "setjmp" 8
\fIsetjmp()\fR is C\-specific: use eval {} instead.
.Ip "setlocale" 8
Modifies and queries program's locale.
.Sp
The following will set the traditional \s-1UNIX\s0 system locale behavior
(the second argument \f(CW"C"\fR).
.Sp
.Vb 1
\&        $loc = POSIX::setlocale( &POSIX::LC_ALL, "C" );
.Ve
The following will query (the missing second argument) the current
\s-1LC_CTYPE\s0 category.
.Sp
.Vb 1
\&        $loc = POSIX::setlocale( &POSIX::LC_CTYPE);
.Ve
The following will set the \s-1LC_CTYPE\s0 behaviour according to the locale
environment variables (the second argument \f(CW""\fR).
Please see your systems the \fIsetlocale(3)\fR manpage documentation for the locale
environment variables\*(R' meaning or consult the \fIperllocale\fR manpage.
.Sp
.Vb 1
\&        $loc = POSIX::setlocale( &POSIX::LC_CTYPE, "");
.Ve
The following will set the \s-1LC_COLLATE\s0 behaviour to Argentinian
Spanish. \fB\s-1NOTE\s0\fR: The naming and availability of locales depends on
your operating system. Please consult the \fIperllocale\fR manpage for how to find
out which locales are available in your system.
.Sp
.Vb 1
\&        $loc = POSIX::setlocale( &POSIX::LC_ALL, "es_AR.ISO8859-1" );
.Ve
.Ip "setpgid" 8
This is similar to the C function \f(CWsetpgid()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "setsid" 8
This is identical to the C function \f(CWsetsid()\fR.
.Ip "setuid" 8
Sets the real user id for this process.
.Ip "sigaction" 8
Detailed signal management.  This uses \f(CWPOSIX::SigAction\fR objects for the
\f(CWaction\fR and \f(CWoldaction\fR arguments.  Consult your system's \f(CWsigaction\fR
manpage for details.
.Sp
Synopsis:
.Sp
.Vb 1
\&        sigaction(sig, action, oldaction = 0)
.Ve
Returns \f(CWundef\fR on failure.
.Ip "siglongjmp" 8
\fIsiglongjmp()\fR is C\-specific: use die instead.
.Ip "sigpending" 8
Examine signals that are blocked and pending.  This uses \f(CWPOSIX::SigSet\fR
objects for the \f(CWsigset\fR argument.  Consult your system's \f(CWsigpending\fR
manpage for details.
.Sp
Synopsis:
.Sp
.Vb 1
\&        sigpending(sigset)
.Ve
Returns \f(CWundef\fR on failure.
.Ip "sigprocmask" 8
Change and/or examine calling process's signal mask.  This uses
\f(CWPOSIX::SigSet\fR objects for the \f(CWsigset\fR and \f(CWoldsigset\fR arguments.
Consult your system's \f(CWsigprocmask\fR manpage for details.
.Sp
Synopsis:
.Sp
.Vb 1
\&        sigprocmask(how, sigset, oldsigset = 0)
.Ve
Returns \f(CWundef\fR on failure.
.Ip "sigsetjmp" 8
\fIsigsetjmp()\fR is C\-specific: use eval {} instead.
.Ip "sigsuspend" 8
Install a signal mask and suspend process until signal arrives.  This uses
\f(CWPOSIX::SigSet\fR objects for the \f(CWsignal_mask\fR argument.  Consult your
system's \f(CWsigsuspend\fR manpage for details.
.Sp
Synopsis:
.Sp
.Vb 1
\&        sigsuspend(signal_mask)
.Ve
Returns \f(CWundef\fR on failure.
.Ip "sin" 8
This is identical to Perl's builtin \f(CWsin()\fR function.
.Ip "sinh" 8
This is identical to the C function \f(CWsinh()\fR.
.Ip "sleep" 8
This is identical to Perl's builtin \f(CWsleep()\fR function.
.Ip "sprintf" 8
This is identical to Perl's builtin \f(CWsprintf()\fR function.
.Ip "sqrt" 8
This is identical to Perl's builtin \f(CWsqrt()\fR function.
.Ip "srand" 8
\fIsrand()\fR.
.Ip "sscanf" 8
\fIsscanf()\fR is C\-specific\*(--use regular expressions instead.
.Ip "stat" 8
This is identical to Perl's builtin \f(CWstat()\fR function.
.Ip "strcat" 8
\fIstrcat()\fR is C\-specific, use .= instead.
.Ip "strchr" 8
\fIstrchr()\fR is C\-specific, use \fIindex()\fR instead.
.Ip "strcmp" 8
\fIstrcmp()\fR is C\-specific, use eq instead.
.Ip "strcoll" 8
This is identical to the C function \f(CWstrcoll()\fR.
.Ip "strcpy" 8
\fIstrcpy()\fR is C\-specific, use = instead.
.Ip "strcspn" 8
\fIstrcspn()\fR is C\-specific, use regular expressions instead.
.Ip "strerror" 8
Returns the error string for the specified errno.
.Ip "strftime" 8
Convert date and time information to string.  Returns the string.
.Sp
Synopsis:
.Sp
.Vb 1
\&        strftime(fmt, sec, min, hour, mday, mon, year, wday = 0, yday = 0, isdst = 0)
.Ve
The month (\f(CWmon\fR), weekday (\f(CWwday\fR), and yearday (\f(CWyday\fR) begin at zero.
I.e. January is 0, not 1; Sunday is 0, not 1; January 1st is 0, not 1.  The
year (\f(CWyear\fR) is given in years since 1900.  I.e. The year 1995 is 95; the
year 2001 is 101.  Consult your system's \f(CWstrftime()\fR manpage for details
about these and the other arguments.
.Sp
The string for Tuesday, December 12, 1995.
.Sp
.Vb 2
\&        $str = POSIX::strftime( "%A, %B %d, %Y", 0, 0, 0, 12, 11, 95, 2 );
\&        print "$str\en";
.Ve
.Ip "strlen" 8
\fIstrlen()\fR is C\-specific, use length instead.
.Ip "strncat" 8
\fIstrncat()\fR is C\-specific, use .= instead.
.Ip "strncmp" 8
\fIstrncmp()\fR is C\-specific, use eq instead.
.Ip "strncpy" 8
\fIstrncpy()\fR is C\-specific, use = instead.
.Ip "stroul" 8
\fIstroul()\fR is C\-specific.
.Ip "strpbrk" 8
\fIstrpbrk()\fR is C\-specific.
.Ip "strrchr" 8
\fIstrrchr()\fR is C\-specific, use \fIrindex()\fR instead.
.Ip "strspn" 8
\fIstrspn()\fR is C\-specific.
.Ip "strstr" 8
This is identical to Perl's builtin \f(CWindex()\fR function.
.Ip "strtod" 8
String to double translation. Returns the parsed number and the number
of characters in the unparsed portion of the string.  Truly
\s-1POSIX\s0\-compliant systems set $! ($\s-1ERRNO\s0) to indicate a translation
error, so clear $! before calling strtod.  However, non-\s-1POSIX\s0 systems
may not check for overflow, and therefore will never set $!.
.Sp
strtod should respect any \s-1POSIX\s0 \fIsetlocale()\fR settings.
.Sp
To parse a string \f(CW$str\fR as a floating point number use
.Sp
.Vb 2
\&    $! = 0;
\&    ($num, $n_unparsed) = POSIX::strtod($str);
.Ve
The second returned item and $! can be used to check for valid input:
.Sp
.Vb 3
\&    if (($str eq '') || ($n_unparsed != 0) || !$!) {
\&        die "Non-numeric input $str" . $! ? ": $!\en" : "\en";
\&    }
.Ve
When called in a scalar context strtod returns the parsed number.
.Ip "strtok" 8
\fIstrtok()\fR is C\-specific.
.Ip "strtol" 8
String to (long) integer translation.  Returns the parsed number and
the number of characters in the unparsed portion of the string.  Truly
\s-1POSIX\s0\-compliant systems set $! ($\s-1ERRNO\s0) to indicate a translation
error, so clear $! before calling strtol.  However, non-\s-1POSIX\s0 systems
may not check for overflow, and therefore will never set $!.
.Sp
strtol should respect any \s-1POSIX\s0 \fIsetlocale()\fR settings.
.Sp
To parse a string \f(CW$str\fR as a number in some base \f(CW$base\fR use
.Sp
.Vb 2
\&    $! = 0;
\&    ($num, $n_unparsed) = POSIX::strtol($str, $base);
.Ve
The base should be zero or between 2 and 36, inclusive.  When the base
is zero or omitted strtol will use the string itself to determine the
base: a leading \*(L"0x\*(R" or \*(L"0X\*(R" means hexadecimal; a leading \*(L"0\*(R" means
octal; any other leading characters mean decimal.  Thus, \*(L"1234\*(R" is
parsed as a decimal number, \*(L"01234\*(R" as an octal number, and \*(L"0x1234\*(R"
as a hexadecimal number.
.Sp
The second returned item and $! can be used to check for valid input:
.Sp
.Vb 3
\&    if (($str eq '') || ($n_unparsed != 0) || !$!) {
\&        die "Non-numeric input $str" . $! ? ": $!\en" : "\en";
\&    }
.Ve
When called in a scalar context strtol returns the parsed number.
.Ip "strtoul" 8
String to unsigned (long) integer translation.  strtoul is identical
to strtol except that strtoul only parses unsigned integers.  See
\fIstrtol\fR for details.
.Sp
Note: Some vendors supply strtod and strtol but not strtoul.
Other vendors that do suply strtoul parse \*(L"\-1\*(R" as a valid value.
.Ip "strxfrm" 8
String transformation.  Returns the transformed string.
.Sp
.Vb 1
\&        $dst = POSIX::strxfrm( $src );
.Ve
.Ip "sysconf" 8
Retrieves values of system configurable variables.
.Sp
The following will get the machine's clock speed.
.Sp
.Vb 1
\&        $clock_ticks = POSIX::sysconf( &POSIX::_SC_CLK_TCK );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "system" 8
This is identical to Perl's builtin \f(CWsystem()\fR function.
.Ip "tan" 8
This is identical to the C function \f(CWtan()\fR.
.Ip "tanh" 8
This is identical to the C function \f(CWtanh()\fR.
.Ip "tcdrain" 8
This is similar to the C function \f(CWtcdrain()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "tcflow" 8
This is similar to the C function \f(CWtcflow()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "tcflush" 8
This is similar to the C function \f(CWtcflush()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "tcgetpgrp" 8
This is identical to the C function \f(CWtcgetpgrp()\fR.
.Ip "tcsendbreak" 8
This is similar to the C function \f(CWtcsendbreak()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "tcsetpgrp" 8
This is similar to the C function \f(CWtcsetpgrp()\fR.
.Sp
Returns \f(CWundef\fR on failure.
.Ip "time" 8
This is identical to Perl's builtin \f(CWtime()\fR function.
.Ip "times" 8
The \fItimes()\fR function returns elapsed realtime since some point in the past
(such as system startup), user and system times for this process, and user
and system times used by child processes.  All times are returned in clock
ticks.
.Sp
.Vb 1
\&    ($realtime, $user, $system, $cuser, $csystem) = POSIX::times();
.Ve
Note: Perl's builtin \f(CWtimes()\fR function returns four values, measured in
seconds.
.Ip "tmpfile" 8
Use method \f(CWIO::File::new_tmpfile()\fR instead.
.Ip "tmpnam" 8
Returns a name for a temporary file.
.Sp
.Vb 1
\&        $tmpfile = POSIX::tmpnam();
.Ve
.Ip "tolower" 8
This is identical to Perl's builtin \f(CWlc()\fR function.
.Ip "toupper" 8
This is identical to Perl's builtin \f(CWuc()\fR function.
.Ip "ttyname" 8
This is identical to the C function \f(CWttyname()\fR.
.Ip "tzname" 8
Retrieves the time conversion information from the \f(CWtzname\fR variable.
.Sp
.Vb 2
\&        POSIX::tzset();
\&        ($std, $dst) = POSIX::tzname();
.Ve
.Ip "tzset" 8
This is identical to the C function \f(CWtzset()\fR.
.Ip "umask" 8
This is identical to Perl's builtin \f(CWumask()\fR function.
.Ip "uname" 8
Get name of current operating system.
.Sp
.Vb 1
\&        ($sysname, $nodename, $release, $version, $machine ) = POSIX::uname();
.Ve
.Ip "ungetc" 8
Use method \f(CWIO::Handle::ungetc()\fR instead.
.Ip "unlink" 8
This is identical to Perl's builtin \f(CWunlink()\fR function.
.Ip "utime" 8
This is identical to Perl's builtin \f(CWutime()\fR function.
.Ip "vfprintf" 8
\fIvfprintf()\fR is C\-specific.
.Ip "vprintf" 8
\fIvprintf()\fR is C\-specific.
.Ip "vsprintf" 8
\fIvsprintf()\fR is C\-specific.
.Ip "wait" 8
This is identical to Perl's builtin \f(CWwait()\fR function.
.Ip "waitpid" 8
Wait for a child process to change state.  This is identical to Perl's
builtin \f(CWwaitpid()\fR function.
.Sp
.Vb 2
\&        $pid = POSIX::waitpid( -1, &POSIX::WNOHANG );
\&        print "status = ", ($? / 256), "\en";
.Ve
.Ip "wcstombs" 8
This is identical to the C function \f(CWwcstombs()\fR.
.Ip "wctomb" 8
This is identical to the C function \f(CWwctomb()\fR.
.Ip "write" 8
Write to a file.  This uses file descriptors such as those obtained by
calling \f(CWPOSIX::open\fR.
.Sp
.Vb 3
\&        $fd = POSIX::open( "foo", &POSIX::O_WRONLY );
\&        $buf = "hello";
\&        $bytes = POSIX::write( $b, $buf, 5 );
.Ve
Returns \f(CWundef\fR on failure.
.SH "CLASSES"
.Sh "\s-1POSIX::\s0SigAction"
.Ip "new" 8
Creates a new \f(CWPOSIX::SigAction\fR object which corresponds to the C
\f(CWstruct sigaction\fR.  This object will be destroyed automatically when it is
no longer needed.  The first parameter is the fully-qualified name of a sub
which is a signal-handler.  The second parameter is a \f(CWPOSIX::SigSet\fR
object, it defaults to the empty set.  The third parameter contains the
\f(CWsa_flags\fR, it defaults to 0.
.Sp
.Vb 2
\&        $sigset = POSIX::SigSet->new(SIGINT, SIGQUIT);
\&        $sigaction = POSIX::SigAction->new( 'main::handler', $sigset, &POSIX::SA_NOCLDSTOP );
.Ve
This \f(CWPOSIX::SigAction\fR object should be used with the \f(CWPOSIX::sigaction()\fR
function.
.Sh "\s-1POSIX::\s0SigSet"
.Ip "new" 8
Create a new SigSet object.  This object will be destroyed automatically
when it is no longer needed.  Arguments may be supplied to initialize the
set.
.Sp
Create an empty set.
.Sp
.Vb 1
\&        $sigset = POSIX::SigSet->new;
.Ve
Create a set with \s-1SIGUSR1\s0.
.Sp
.Vb 1
\&        $sigset = POSIX::SigSet->new( &POSIX::SIGUSR1 );
.Ve
.Ip "addset" 8
Add a signal to a SigSet object.
.Sp
.Vb 1
\&        $sigset->addset( &POSIX::SIGUSR2 );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "delset" 8
Remove a signal from the SigSet object.
.Sp
.Vb 1
\&        $sigset->delset( &POSIX::SIGUSR2 );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "emptyset" 8
Initialize the SigSet object to be empty.
.Sp
.Vb 1
\&        $sigset->emptyset();
.Ve
Returns \f(CWundef\fR on failure.
.Ip "fillset" 8
Initialize the SigSet object to include all signals.
.Sp
.Vb 1
\&        $sigset->fillset();
.Ve
Returns \f(CWundef\fR on failure.
.Ip "ismember" 8
Tests the SigSet object to see if it contains a specific signal.
.Sp
.Vb 3
\&        if( $sigset->ismember( &POSIX::SIGUSR1 ) ){
\&                print "contains SIGUSR1\en";
\&        }
.Ve
.Sh "\s-1POSIX::\s0Termios"
.Ip "new" 8
Create a new Termios object.  This object will be destroyed automatically
when it is no longer needed.
.Sp
.Vb 1
\&        $termios = POSIX::Termios->new;
.Ve
.Ip "getattr" 8
Get terminal control attributes.
.Sp
Obtain the attributes for stdin.
.Sp
.Vb 1
\&        $termios->getattr()
.Ve
Obtain the attributes for stdout.
.Sp
.Vb 1
\&        $termios->getattr( 1 )
.Ve
Returns \f(CWundef\fR on failure.
.Ip "getcc" 8
Retrieve a value from the c_cc field of a termios object.  The c_cc field is
an array so an index must be specified.
.Sp
.Vb 1
\&        $c_cc[1] = $termios->getcc(1);
.Ve
.Ip "getcflag" 8
Retrieve the c_cflag field of a termios object.
.Sp
.Vb 1
\&        $c_cflag = $termios->getcflag;
.Ve
.Ip "getiflag" 8
Retrieve the c_iflag field of a termios object.
.Sp
.Vb 1
\&        $c_iflag = $termios->getiflag;
.Ve
.Ip "getispeed" 8
Retrieve the input baud rate.
.Sp
.Vb 1
\&        $ispeed = $termios->getispeed;
.Ve
.Ip "getlflag" 8
Retrieve the c_lflag field of a termios object.
.Sp
.Vb 1
\&        $c_lflag = $termios->getlflag;
.Ve
.Ip "getoflag" 8
Retrieve the c_oflag field of a termios object.
.Sp
.Vb 1
\&        $c_oflag = $termios->getoflag;
.Ve
.Ip "getospeed" 8
Retrieve the output baud rate.
.Sp
.Vb 1
\&        $ospeed = $termios->getospeed;
.Ve
.Ip "setattr" 8
Set terminal control attributes.
.Sp
Set attributes immediately for stdout.
.Sp
.Vb 1
\&        $termios->setattr( 1, &POSIX::TCSANOW );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "setcc" 8
Set a value in the c_cc field of a termios object.  The c_cc field is an
array so an index must be specified.
.Sp
.Vb 1
\&        $termios->setcc( &POSIX::VEOF, 1 );
.Ve
.Ip "setcflag" 8
Set the c_cflag field of a termios object.
.Sp
.Vb 1
\&        $termios->setcflag( &POSIX::CLOCAL );
.Ve
.Ip "setiflag" 8
Set the c_iflag field of a termios object.
.Sp
.Vb 1
\&        $termios->setiflag( &POSIX::BRKINT );
.Ve
.Ip "setispeed" 8
Set the input baud rate.
.Sp
.Vb 1
\&        $termios->setispeed( &POSIX::B9600 );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "setlflag" 8
Set the c_lflag field of a termios object.
.Sp
.Vb 1
\&        $termios->setlflag( &POSIX::ECHO );
.Ve
.Ip "setoflag" 8
Set the c_oflag field of a termios object.
.Sp
.Vb 1
\&        $termios->setoflag( &POSIX::OPOST );
.Ve
.Ip "setospeed" 8
Set the output baud rate.
.Sp
.Vb 1
\&        $termios->setospeed( &POSIX::B9600 );
.Ve
Returns \f(CWundef\fR on failure.
.Ip "Baud rate values" 8
B38400 B75 B200 B134 B300 B1800 B150 B0 B19200 B1200 B9600 B600 B4800 B50 B2400 B110
.Ip "Terminal interface values" 8
\s-1TCSADRAIN\s0 \s-1TCSANOW\s0 \s-1TCOON\s0 \s-1TCIOFLUSH\s0 \s-1TCOFLUSH\s0 \s-1TCION\s0 \s-1TCIFLUSH\s0 \s-1TCSAFLUSH\s0 \s-1TCIOFF\s0 \s-1TCOOFF\s0
.Ip "c_cc field values" 8
\s-1VEOF\s0 \s-1VEOL\s0 \s-1VERASE\s0 \s-1VINTR\s0 \s-1VKILL\s0 \s-1VQUIT\s0 \s-1VSUSP\s0 \s-1VSTART\s0 \s-1VSTOP\s0 \s-1VMIN\s0 \s-1VTIME\s0 \s-1NCCS\s0
.Ip "c_cflag field values" 8
\s-1CLOCAL\s0 \s-1CREAD\s0 \s-1CSIZE\s0 \s-1CS5\s0 \s-1CS6\s0 \s-1CS7\s0 \s-1CS8\s0 \s-1CSTOPB\s0 \s-1HUPCL\s0 \s-1PARENB\s0 \s-1PARODD\s0
.Ip "c_iflag field values" 8
\s-1BRKINT\s0 \s-1ICRNL\s0 \s-1IGNBRK\s0 \s-1IGNCR\s0 \s-1IGNPAR\s0 \s-1INLCR\s0 \s-1INPCK\s0 \s-1ISTRIP\s0 \s-1IXOFF\s0 \s-1IXON\s0 \s-1PARMRK\s0
.Ip "c_lflag field values" 8
\s-1ECHO\s0 \s-1ECHOE\s0 \s-1ECHOK\s0 \s-1ECHONL\s0 \s-1ICANON\s0 \s-1IEXTEN\s0 \s-1ISIG\s0 \s-1NOFLSH\s0 \s-1TOSTOP\s0
.Ip "c_oflag field values" 8
\s-1OPOST\s0
.SH "PATHNAME CONSTANTS"
.Ip "Constants" 8
_PC_CHOWN_RESTRICTED _PC_LINK_MAX _PC_MAX_CANON _PC_MAX_INPUT _PC_NAME_MAX _PC_NO_TRUNC _PC_PATH_MAX _PC_PIPE_BUF _PC_VDISABLE
.SH "POSIX CONSTANTS"
.Ip "Constants" 8
_POSIX_ARG_MAX _POSIX_CHILD_MAX _POSIX_CHOWN_RESTRICTED _POSIX_JOB_CONTROL _POSIX_LINK_MAX _POSIX_MAX_CANON _POSIX_MAX_INPUT _POSIX_NAME_MAX _POSIX_NGROUPS_MAX _POSIX_NO_TRUNC _POSIX_OPEN_MAX _POSIX_PATH_MAX _POSIX_PIPE_BUF _POSIX_SAVED_IDS _POSIX_SSIZE_MAX _POSIX_STREAM_MAX _POSIX_TZNAME_MAX _POSIX_VDISABLE _POSIX_VERSION
.SH "SYSTEM CONFIGURATION"
.Ip "Constants" 8
_SC_ARG_MAX _SC_CHILD_MAX _SC_CLK_TCK _SC_JOB_CONTROL _SC_NGROUPS_MAX _SC_OPEN_MAX _SC_SAVED_IDS _SC_STREAM_MAX _SC_TZNAME_MAX _SC_VERSION
.SH "ERRNO"
.Ip "Constants" 8
E2BIG \s-1EACCES\s0 \s-1EADDRINUSE\s0 \s-1EADDRNOTAVAIL\s0 \s-1EAFNOSUPPORT\s0 \s-1EAGAIN\s0 \s-1EALREADY\s0 \s-1EBADF\s0
\s-1EBUSY\s0 \s-1ECHILD\s0 \s-1ECONNABORTED\s0 \s-1ECONNREFUSED\s0 \s-1ECONNRESET\s0 \s-1EDEADLK\s0 \s-1EDESTADDRREQ\s0
\s-1EDOM\s0 \s-1EDQUOT\s0 \s-1EEXIST\s0 \s-1EFAULT\s0 \s-1EFBIG\s0 \s-1EHOSTDOWN\s0 \s-1EHOSTUNREACH\s0 \s-1EINPROGRESS\s0 \s-1EINTR\s0
\s-1EINVAL\s0 \s-1EIO\s0 \s-1EISCONN\s0 \s-1EISDIR\s0 \s-1ELOOP\s0 \s-1EMFILE\s0 \s-1EMLINK\s0 \s-1EMSGSIZE\s0 \s-1ENAMETOOLONG\s0
\s-1ENETDOWN\s0 \s-1ENETRESET\s0 \s-1ENETUNREACH\s0 \s-1ENFILE\s0 \s-1ENOBUFS\s0 \s-1ENODEV\s0 \s-1ENOENT\s0 \s-1ENOEXEC\s0
\s-1ENOLCK\s0 \s-1ENOMEM\s0 \s-1ENOPROTOOPT\s0 \s-1ENOSPC\s0 \s-1ENOSYS\s0 \s-1ENOTBLK\s0 \s-1ENOTCONN\s0 \s-1ENOTDIR\s0
\s-1ENOTEMPTY\s0 \s-1ENOTSOCK\s0 \s-1ENOTTY\s0 \s-1ENXIO\s0 \s-1EOPNOTSUPP\s0 \s-1EPERM\s0 \s-1EPFNOSUPPORT\s0 \s-1EPIPE\s0
\s-1EPROCLIM\s0 \s-1EPROTONOSUPPORT\s0 \s-1EPROTOTYPE\s0 \s-1ERANGE\s0 \s-1EREMOTE\s0 \s-1ERESTART\s0 \s-1EROFS\s0
\s-1ESHUTDOWN\s0 \s-1ESOCKTNOSUPPORT\s0 \s-1ESPIPE\s0 \s-1ESRCH\s0 \s-1ESTALE\s0 \s-1ETIMEDOUT\s0 \s-1ETOOMANYREFS\s0
\s-1ETXTBSY\s0 \s-1EUSERS\s0 \s-1EWOULDBLOCK\s0 \s-1EXDEV\s0
.SH "FCNTL"
.Ip "Constants" 8
\s-1FD_CLOEXEC\s0 F_DUPFD F_GETFD F_GETFL F_GETLK F_OK F_RDLCK F_SETFD F_SETFL F_SETLK F_SETLKW F_UNLCK F_WRLCK O_ACCMODE O_APPEND O_CREAT O_EXCL O_NOCTTY O_NONBLOCK O_RDONLY O_RDWR O_TRUNC O_WRONLY
.SH "FLOAT"
.Ip "Constants" 8
\s-1DBL_DIG\s0 \s-1DBL_EPSILON\s0 \s-1DBL_MANT_DIG\s0 \s-1DBL_MAX\s0 \s-1DBL_MAX_10_EXP\s0 \s-1DBL_MAX_EXP\s0 \s-1DBL_MIN\s0 \s-1DBL_MIN_10_EXP\s0 \s-1DBL_MIN_EXP\s0 \s-1FLT_DIG\s0 \s-1FLT_EPSILON\s0 \s-1FLT_MANT_DIG\s0 \s-1FLT_MAX\s0 \s-1FLT_MAX_10_EXP\s0 \s-1FLT_MAX_EXP\s0 \s-1FLT_MIN\s0 \s-1FLT_MIN_10_EXP\s0 \s-1FLT_MIN_EXP\s0 \s-1FLT_RADIX\s0 \s-1FLT_ROUNDS\s0 \s-1LDBL_DIG\s0 \s-1LDBL_EPSILON\s0 \s-1LDBL_MANT_DIG\s0 \s-1LDBL_MAX\s0 \s-1LDBL_MAX_10_EXP\s0 \s-1LDBL_MAX_EXP\s0 \s-1LDBL_MIN\s0 \s-1LDBL_MIN_10_EXP\s0 \s-1LDBL_MIN_EXP\s0
.SH "LIMITS"
.Ip "Constants" 8
\s-1ARG_MAX\s0 \s-1CHAR_BIT\s0 \s-1CHAR_MAX\s0 \s-1CHAR_MIN\s0 \s-1CHILD_MAX\s0 \s-1INT_MAX\s0 \s-1INT_MIN\s0 \s-1LINK_MAX\s0 \s-1LONG_MAX\s0 \s-1LONG_MIN\s0 \s-1MAX_CANON\s0 \s-1MAX_INPUT\s0 \s-1MB_LEN_MAX\s0 \s-1NAME_MAX\s0 \s-1NGROUPS_MAX\s0 \s-1OPEN_MAX\s0 \s-1PATH_MAX\s0 \s-1PIPE_BUF\s0 \s-1SCHAR_MAX\s0 \s-1SCHAR_MIN\s0 \s-1SHRT_MAX\s0 \s-1SHRT_MIN\s0 \s-1SSIZE_MAX\s0 \s-1STREAM_MAX\s0 \s-1TZNAME_MAX\s0 \s-1UCHAR_MAX\s0 \s-1UINT_MAX\s0 \s-1ULONG_MAX\s0 \s-1USHRT_MAX\s0
.SH "LOCALE"
.Ip "Constants" 8
\s-1LC_ALL\s0 \s-1LC_COLLATE\s0 \s-1LC_CTYPE\s0 \s-1LC_MONETARY\s0 \s-1LC_NUMERIC\s0 \s-1LC_TIME\s0
.SH "MATH"
.Ip "Constants" 8
\s-1HUGE_VAL\s0
.SH "SIGNAL"
.Ip "Constants" 8
\s-1SA_NOCLDSTOP\s0 \s-1SA_NOCLDWAIT\s0 \s-1SA_NODEFER\s0 \s-1SA_ONSTACK\s0 \s-1SA_RESETHAND\s0 \s-1SA_RESTART\s0
\s-1SA_SIGINFO\s0 \s-1SIGABRT\s0 \s-1SIGALRM\s0 \s-1SIGCHLD\s0 \s-1SIGCONT\s0 \s-1SIGFPE\s0 \s-1SIGHUP\s0 \s-1SIGILL\s0 \s-1SIGINT\s0
\s-1SIGKILL\s0 \s-1SIGPIPE\s0 \s-1SIGQUIT\s0 \s-1SIGSEGV\s0 \s-1SIGSTOP\s0 \s-1SIGTERM\s0 \s-1SIGTSTP\s0 \s-1SIGTTIN\s0 \s-1SIGTTOU\s0
\s-1SIGUSR1\s0 \s-1SIGUSR2\s0 \s-1SIG_BLOCK\s0 \s-1SIG_DFL\s0 \s-1SIG_ERR\s0 \s-1SIG_IGN\s0 \s-1SIG_SETMASK\s0
\s-1SIG_UNBLOCK\s0
.SH "STAT"
.Ip "Constants" 8
S_IRGRP S_IROTH S_IRUSR S_IRWXG S_IRWXO S_IRWXU S_ISGID S_ISUID S_IWGRP S_IWOTH S_IWUSR S_IXGRP S_IXOTH S_IXUSR
.Ip "Macros" 8
S_ISBLK S_ISCHR S_ISDIR S_ISFIFO S_ISREG
.SH "STDLIB"
.Ip "Constants" 8
\s-1EXIT_FAILURE\s0 \s-1EXIT_SUCCESS\s0 \s-1MB_CUR_MAX\s0 \s-1RAND_MAX\s0
.SH "STDIO"
.Ip "Constants" 8
\s-1BUFSIZ\s0 \s-1EOF\s0 \s-1FILENAME_MAX\s0 L_ctermid L_cuserid L_tmpname \s-1TMP_MAX\s0
.SH "TIME"
.Ip "Constants" 8
\s-1CLK_TCK\s0 \s-1CLOCKS_PER_SEC\s0
.SH "UNISTD"
.Ip "Constants" 8
R_OK \s-1SEEK_CUR\s0 \s-1SEEK_END\s0 \s-1SEEK_SET\s0 \s-1STDIN_FILENO\s0 \s-1STDOUT_FILENO\s0 \s-1STRERR_FILENO\s0 W_OK X_OK
.SH "WAIT"
.Ip "Constants" 8
\s-1WNOHANG\s0 \s-1WUNTRACED\s0
.Ip "Macros" 8
\s-1WIFEXITED\s0 \s-1WEXITSTATUS\s0 \s-1WIFSIGNALED\s0 \s-1WTERMSIG\s0 \s-1WIFSTOPPED\s0 \s-1WSTOPSIG\s0
.SH "CREATION"
This document generated by ./mkposixman.PL version 19960129.

.rn }` ''
.IX Title "POSIX 3"
.IX Name "POSIX - Perl interface to IEEE Std 1003.1"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "NOTE"

.IX Header "CAVEATS"

.IX Header "FUNCTIONS"

.IX Item "_exit"

.IX Item "abort"

.IX Item "abs"

.IX Item "access"

.IX Item "acos"

.IX Item "alarm"

.IX Item "asctime"

.IX Item "asin"

.IX Item "assert"

.IX Item "atan"

.IX Item "atan2"

.IX Item "atexit"

.IX Item "atof"

.IX Item "atoi"

.IX Item "atol"

.IX Item "bsearch"

.IX Item "calloc"

.IX Item "ceil"

.IX Item "chdir"

.IX Item "chmod"

.IX Item "chown"

.IX Item "clearerr"

.IX Item "clock"

.IX Item "close"

.IX Item "closedir"

.IX Item "cos"

.IX Item "cosh"

.IX Item "creat"

.IX Item "ctermid"

.IX Item "ctime"

.IX Item "cuserid"

.IX Item "difftime"

.IX Item "div"

.IX Item "dup"

.IX Item "dup2"

.IX Item "errno"

.IX Item "execl"

.IX Item "execle"

.IX Item "execlp"

.IX Item "execv"

.IX Item "execve"

.IX Item "execvp"

.IX Item "exit"

.IX Item "exp"

.IX Item "fabs"

.IX Item "fclose"

.IX Item "fcntl"

.IX Item "fdopen"

.IX Item "feof"

.IX Item "ferror"

.IX Item "fflush"

.IX Item "fgetc"

.IX Item "fgetpos"

.IX Item "fgets"

.IX Item "fileno"

.IX Item "floor"

.IX Item "fmod"

.IX Item "fopen"

.IX Item "fork"

.IX Item "fpathconf"

.IX Item "fprintf"

.IX Item "fputc"

.IX Item "fputs"

.IX Item "fread"

.IX Item "free"

.IX Item "freopen"

.IX Item "frexp"

.IX Item "fscanf"

.IX Item "fseek"

.IX Item "fsetpos"

.IX Item "fstat"

.IX Item "ftell"

.IX Item "fwrite"

.IX Item "getc"

.IX Item "getchar"

.IX Item "getcwd"

.IX Item "getegid"

.IX Item "getenv"

.IX Item "geteuid"

.IX Item "getgid"

.IX Item "getgrgid"

.IX Item "getgrnam"

.IX Item "getgroups"

.IX Item "getlogin"

.IX Item "getpgrp"

.IX Item "getpid"

.IX Item "getppid"

.IX Item "getpwnam"

.IX Item "getpwuid"

.IX Item "gets"

.IX Item "getuid"

.IX Item "gmtime"

.IX Item "isalnum"

.IX Item "isalpha"

.IX Item "isatty"

.IX Item "iscntrl"

.IX Item "isdigit"

.IX Item "isgraph"

.IX Item "islower"

.IX Item "isprint"

.IX Item "ispunct"

.IX Item "isspace"

.IX Item "isupper"

.IX Item "isxdigit"

.IX Item "kill"

.IX Item "labs"

.IX Item "ldexp"

.IX Item "ldiv"

.IX Item "link"

.IX Item "localeconv"

.IX Item "localtime"

.IX Item "log"

.IX Item "log10"

.IX Item "longjmp"

.IX Item "lseek"

.IX Item "malloc"

.IX Item "mblen"

.IX Item "mbstowcs"

.IX Item "mbtowc"

.IX Item "memchr"

.IX Item "memcmp"

.IX Item "memcpy"

.IX Item "memmove"

.IX Item "memset"

.IX Item "mkdir"

.IX Item "mkfifo"

.IX Item "mktime"

.IX Item "modf"

.IX Item "nice"

.IX Item "offsetof"

.IX Item "open"

.IX Item "opendir"

.IX Item "pathconf"

.IX Item "pause"

.IX Item "perror"

.IX Item "pipe"

.IX Item "pow"

.IX Item "printf"

.IX Item "putc"

.IX Item "putchar"

.IX Item "puts"

.IX Item "qsort"

.IX Item "raise"

.IX Item "rand"

.IX Item "read"

.IX Item "readdir"

.IX Item "realloc"

.IX Item "remove"

.IX Item "rename"

.IX Item "rewind"

.IX Item "rewinddir"

.IX Item "rmdir"

.IX Item "scanf"

.IX Item "setgid"

.IX Item "setjmp"

.IX Item "setlocale"

.IX Item "setpgid"

.IX Item "setsid"

.IX Item "setuid"

.IX Item "sigaction"

.IX Item "siglongjmp"

.IX Item "sigpending"

.IX Item "sigprocmask"

.IX Item "sigsetjmp"

.IX Item "sigsuspend"

.IX Item "sin"

.IX Item "sinh"

.IX Item "sleep"

.IX Item "sprintf"

.IX Item "sqrt"

.IX Item "srand"

.IX Item "sscanf"

.IX Item "stat"

.IX Item "strcat"

.IX Item "strchr"

.IX Item "strcmp"

.IX Item "strcoll"

.IX Item "strcpy"

.IX Item "strcspn"

.IX Item "strerror"

.IX Item "strftime"

.IX Item "strlen"

.IX Item "strncat"

.IX Item "strncmp"

.IX Item "strncpy"

.IX Item "stroul"

.IX Item "strpbrk"

.IX Item "strrchr"

.IX Item "strspn"

.IX Item "strstr"

.IX Item "strtod"

.IX Item "strtok"

.IX Item "strtol"

.IX Item "strtoul"

.IX Item "strxfrm"

.IX Item "sysconf"

.IX Item "system"

.IX Item "tan"

.IX Item "tanh"

.IX Item "tcdrain"

.IX Item "tcflow"

.IX Item "tcflush"

.IX Item "tcgetpgrp"

.IX Item "tcsendbreak"

.IX Item "tcsetpgrp"

.IX Item "time"

.IX Item "times"

.IX Item "tmpfile"

.IX Item "tmpnam"

.IX Item "tolower"

.IX Item "toupper"

.IX Item "ttyname"

.IX Item "tzname"

.IX Item "tzset"

.IX Item "umask"

.IX Item "uname"

.IX Item "ungetc"

.IX Item "unlink"

.IX Item "utime"

.IX Item "vfprintf"

.IX Item "vprintf"

.IX Item "vsprintf"

.IX Item "wait"

.IX Item "waitpid"

.IX Item "wcstombs"

.IX Item "wctomb"

.IX Item "write"

.IX Header "CLASSES"

.IX Subsection "\s-1POSIX::\s0SigAction"

.IX Item "new"

.IX Subsection "\s-1POSIX::\s0SigSet"

.IX Item "new"

.IX Item "addset"

.IX Item "delset"

.IX Item "emptyset"

.IX Item "fillset"

.IX Item "ismember"

.IX Subsection "\s-1POSIX::\s0Termios"

.IX Item "new"

.IX Item "getattr"

.IX Item "getcc"

.IX Item "getcflag"

.IX Item "getiflag"

.IX Item "getispeed"

.IX Item "getlflag"

.IX Item "getoflag"

.IX Item "getospeed"

.IX Item "setattr"

.IX Item "setcc"

.IX Item "setcflag"

.IX Item "setiflag"

.IX Item "setispeed"

.IX Item "setlflag"

.IX Item "setoflag"

.IX Item "setospeed"

.IX Item "Baud rate values"

.IX Item "Terminal interface values"

.IX Item "c_cc field values"

.IX Item "c_cflag field values"

.IX Item "c_iflag field values"

.IX Item "c_lflag field values"

.IX Item "c_oflag field values"

.IX Header "PATHNAME CONSTANTS"

.IX Item "Constants"

.IX Header "POSIX CONSTANTS"

.IX Item "Constants"

.IX Header "SYSTEM CONFIGURATION"

.IX Item "Constants"

.IX Header "ERRNO"

.IX Item "Constants"

.IX Header "FCNTL"

.IX Item "Constants"

.IX Header "FLOAT"

.IX Item "Constants"

.IX Header "LIMITS"

.IX Item "Constants"

.IX Header "LOCALE"

.IX Item "Constants"

.IX Header "MATH"

.IX Item "Constants"

.IX Header "SIGNAL"

.IX Item "Constants"

.IX Header "STAT"

.IX Item "Constants"

.IX Item "Macros"

.IX Header "STDLIB"

.IX Item "Constants"

.IX Header "STDIO"

.IX Item "Constants"

.IX Header "TIME"

.IX Item "Constants"

.IX Header "UNISTD"

.IX Item "Constants"

.IX Header "WAIT"

.IX Item "Constants"

.IX Item "Macros"

.IX Header "CREATION"

