.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH Term::ReadLine 3 "perl 5.005, patch 53" "13/Jul/98" "Perl Programmers Reference Guide"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
Term::ReadLine \- Perl interface to various \f(CWreadline\fR packages. If
no real package is found, substitutes stubs instead of basic functions.
.SH "SYNOPSIS"
.PP
.Vb 10
\&  use Term::ReadLine;
\&  $term = new Term::ReadLine 'Simple Perl calc';
\&  $prompt = "Enter your arithmetic expression: ";
\&  $OUT = $term->OUT || STDOUT;
\&  while ( defined ($_ = $term->readline($prompt)) ) {
\&    $res = eval($_), "\en";
\&    warn $@ if $@;
\&    print $OUT $res, "\en" unless $@;
\&    $term->addhistory($_) if /\eS/;
\&  }
.Ve
.SH "DESCRIPTION"
This package is just a front end to some other packages. At the moment
this description is written, the only such package is Term-ReadLine,
available on CPAN near you. The real target of this stub package is to
set up a common interface to whatever Readline emerges with time.
.SH "Minimal set of supported functions"
All the supported functions should be called as methods, i.e., either as 
.PP
.Vb 1
\&  $term = new Term::ReadLine 'name';
.Ve
or as 
.PP
.Vb 1
\&  $term->addhistory('row');
.Ve
where \f(CW$term\fR is a return value of Term::ReadLine->Init.
.Ip "\f(CWReadLine\fR" 12
returns the actual package that executes the commands. Among possible
values are \f(CWTerm::ReadLine::Gnu\fR, \f(CWTerm::ReadLine::Perl\fR,
\f(CWTerm::ReadLine::Stub Exporter\fR.
.Ip "\f(CWnew\fR" 12
returns the handle for subsequent calls to following
functions. Argument is the name of the application. Optionally can be
followed by two arguments for \f(CWIN\fR and \f(CWOUT\fR filehandles. These
arguments should be globs.
.Ip "\f(CWreadline\fR" 12
gets an input line, \fIpossibly\fR with actual \f(CWreadline\fR
support. Trailing newline is removed. Returns \f(CWundef\fR on \f(CWEOF\fR.
.Ip "\f(CWaddhistory\fR" 12
adds the line to the history of input, from where it can be used if
the actual \f(CWreadline\fR is present.
.Ip "\f(CWIN\fR, $\f(CWOUT\fR" 12
return the filehandles for input and output or \f(CWundef\fR if \f(CWreadline\fR
input and output cannot be used for Perl.
.Ip "\f(CWMinLine\fR" 12
If argument is specified, it is an advice on minimal size of line to
be included into history.  \f(CWundef\fR means do not include anything into
history. Returns the old value.
.Ip "\f(CWfindConsole\fR" 12
returns an array with two strings that give most appropriate names for
files for input and output using conventions \f(CW"<$in"\fR, \f(CW">out"\fR.
.Ip "Attribs" 12
returns a reference to a hash which describes internal configuration
of the package. Names of keys in this hash conform to standard
conventions with the leading \f(CWrl_\fR stripped.
.Ip "\f(CWFeatures\fR" 12
Returns a reference to a hash with keys being features present in
current implementation. Several optional features are used in the
minimal interface: \f(CWappname\fR should be present if the first argument
to \f(CWnew\fR is recognized, and \f(CWminline\fR should be present if
\f(CWMinLine\fR method is not dummy.  \f(CWautohistory\fR should be present if
lines are put into history automatically (maybe subject to
\f(CWMinLine\fR), and \f(CWaddhistory\fR if \f(CWaddhistory\fR method is not dummy.
.Sp
If \f(CWFeatures\fR method reports a feature \f(CWattribs\fR as present, the
method \f(CWAttribs\fR is not dummy.
.SH "Additional supported functions"
Actually \f(CWTerm::ReadLine\fR can use some other package, that will
support reacher set of commands.
.PP
All these commands are callable via method interface and have names
which conform to standard conventions with the leading \f(CWrl_\fR stripped.
.PP
The stub package included with the perl distribution allows some
additional methods: 
.Ip "\f(CWtkRunning\fR" 12
makes Tk event loop run when waiting for user input (i.e., during
\f(CWreadline\fR method).
.Ip "\f(CWornaments\fR" 12
makes the command line stand out by using termcap data.  The argument
to \f(CWornaments\fR should be 0, 1, or a string of a form
\f(CW"aa,bb,cc,dd"\fR.  Four components of this string should be names of
\fIterminal capacities\fR, first two will be issued to make the prompt
standout, last two to make the input line standout.
.Ip "\f(CWnewTTY\fR" 12
takes two arguments which are input filehandle and output filehandle.
Switches to use these filehandles.
.PP
One can check whether the currently loaded ReadLine package supports
these methods by checking for corresponding \f(CWFeatures\fR.
.SH "EXPORTS"
None
.SH "ENVIRONMENT"
The envrironment variable \f(CWPERL_RL\fR governs which ReadLine clone is
loaded. If the value is false, a dummy interface is used. If the value
is true, it should be tail of the name of the package to use, such as
\f(CWPerl\fR or \f(CWGnu\fR.  
.PP
As a special case, if the value of this variable is space-separated,
the tail might be used to disable the ornaments by setting the tail to
be \f(CWo=0\fR or \f(CWornaments=0\fR.  The head should be as described above, say
.PP
If the variable is not set, or if the head of space-separated list is
empty, the best available package is loaded.
.PP
.Vb 2
\&  export "PERL_RL=Perl o=0"     # Use Perl ReadLine without ornaments
\&  export "PERL_RL= o=0"         # Use best available ReadLine without ornaments
.Ve
(Note that processing of \f(CWPERL_RL\fR for ornaments is in the discretion of the 
particular used \f(CWTerm::ReadLine::*\fR package).

.rn }` ''
.IX Title "Term::ReadLine 3"
.IX Name "Term::ReadLine - Perl interface to various C<readline> packages. If
no real package is found, substitutes stubs instead of basic functions."

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "Minimal set of supported functions"

.IX Item "\f(CWReadLine\fR"

.IX Item "\f(CWnew\fR"

.IX Item "\f(CWreadline\fR"

.IX Item "\f(CWaddhistory\fR"

.IX Item "\f(CWIN\fR, $\f(CWOUT\fR"

.IX Item "\f(CWMinLine\fR"

.IX Item "\f(CWfindConsole\fR"

.IX Item "Attribs"

.IX Item "\f(CWFeatures\fR"

.IX Header "Additional supported functions"

.IX Item "\f(CWtkRunning\fR"

.IX Item "\f(CWornaments\fR"

.IX Item "\f(CWnewTTY\fR"

.IX Header "EXPORTS"

.IX Header "ENVIRONMENT"

