.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH ELEMENT 1 "perl 5.007, patch 00" "31/Jan/100" "User Contributed Perl Documentation"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
XML::DOM::Element \- An XML element node in XML::DOM
.SH "DESCRIPTION"
XML::DOM::Element extends the \fIXML::DOM::Node\fR manpage.
.PP
By far the vast majority of objects (apart from text) that authors
encounter when traversing a document are Element nodes. Assume the
following XML document:
.PP
.Vb 4
\&     <elementExample id="demo">
\&       <subelement1/>
\&       <subelement2><subsubelement/></subelement2>
\&     </elementExample>
.Ve
When represented using DOM, the top node is an Element node for
\*(L"elementExample\*(R", which contains two child Element nodes, one for
\*(L"subelement1\*(R" and one for \*(L"subelement2\*(R". \*(L"subelement1\*(R" contains no
child nodes.
.PP
Elements may have attributes associated with them; since the Element
interface inherits from Node, the generic Node interface method
getAttributes may be used to retrieve the set of all attributes for an
element. There are methods on the Element interface to retrieve either
an Attr object by name or an attribute value by name. In XML, where an
attribute value may contain entity references, an Attr object should be
retrieved to examine the possibly fairly complex sub-tree representing
the attribute value. On the other hand, in HTML, where all attributes
have simple string values, methods to directly access an attribute
value can safely be used as a convenience.
.Sh "\s-1METHODS\s0"
.Ip "getTagName" 4
The name of the element. For example, in:
.Sp
.Vb 3
\&               <elementExample id="demo">
\&                       ...
\&               </elementExample>
.Ve
tagName has the value \*(L"elementExample\*(R". Note that this is
case-preserving in \s-1XML\s0, as are all of the operations of the
\s-1DOM\s0.
.Ip "getAttribute (name)" 4
Retrieves an attribute value by name.
.Sp
Return Value: The Attr value as a string, or the empty string if that
attribute does not have a specified or default value.
.Ip "setAttribute (name, value)" 4
Adds a new attribute. If an attribute with that name is
already present in the element, its value is changed to be
that of the value parameter. This value is a simple string,
it is not parsed as it is being set. So any markup (such as
syntax to be recognized as an entity reference) is treated as
literal text, and needs to be appropriately escaped by the
implementation when it is written out. In order to assign an
attribute value that contains entity references, the user
must create an Attr node plus any Text and EntityReference
nodes, build the appropriate subtree, and use
setAttributeNode to assign it as the value of an attribute.
.Sp
DOMExceptions:
.Ip "\(bu \s-1INVALID_CHARACTER_ERR\s0" 8
Raised if the specified name contains an invalid character.
.Ip "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0" 8
Raised if this node is readonly.
.Ip "removeAttribute (name)" 4
Removes an attribute by name. If the removed attribute has a
default value it is immediately replaced.
.Sp
DOMExceptions:
.Ip "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0" 8
Raised if this node is readonly.
.Ip "getAttributeNode" 4
Retrieves an Attr node by name.
.Sp
Return Value: The Attr node with the specified attribute name or undef
if there is no such attribute.
.Ip "setAttributeNode (attr)" 4
Adds a new attribute. If an attribute with that name is
already present in the element, it is replaced by the new one.
.Sp
Return Value: If the newAttr attribute replaces an existing attribute
with the same name, the previously existing Attr node is
returned, otherwise undef is returned.
.Sp
DOMExceptions:
.Ip "\(bu \s-1WRONG_DOCUMENT_ERR\s0" 8
Raised if newAttr was created from a different document than the one that created
the element.
.Ip "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0" 8
Raised if this node is readonly.
.Ip "\(bu \s-1INUSE_ATTRIBUTE_ERR\s0" 8
Raised if newAttr is already an attribute of another Element object. The \s-1DOM\s0
user must explicitly clone Attr nodes to re-use them in other elements.
.Ip "removeAttributeNode (oldAttr)" 4
Removes the specified attribute. If the removed Attr has a default value it is
immediately replaced. If the Attr already is the default value, nothing happens
and nothing is returned.
.Sp
Parameters:
 \fIoldAttr\fR  The Attr node to remove from the attribute list. 
.Sp
Return Value: The Attr node that was removed.
.Sp
DOMExceptions:
.Ip "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0" 8
Raised if this node is readonly.
.Ip "\(bu \s-1NOT_FOUND_ERR\s0" 8
Raised if oldAttr is not an attribute of the element.
.Sh "Additional methods not in the \s-1DOM\s0 Spec"
.Ip "setTagName (newTagName)" 8
Sets the tag name of the Element. Note that this method is not portable
between \s-1DOM\s0 implementations.
.Sp
DOMExceptions:
.Ip "\(bu \s-1INVALID_CHARACTER_ERR\s0" 12
Raised if the specified name contains an invalid character.
.Ip "check ($checker)" 8
Uses the specified the \fI\s-1XML::\s0Checker\fR manpage to validate the document.
\s-1NOTE\s0: an \s-1XML::\s0Checker must be supplied. The checker can be created in
different ways, e.g. when parsing a document with \s-1XML::DOM::\s0ValParser,
or with \fI\s-1XML::DOM::\s0Document::createChecker()\fR.
See the \fI\s-1XML::\s0Checker\fR manpage for more info.

.rn }` ''
.IX Title "ELEMENT 1"
.IX Name "XML::DOM::Element - An XML element node in XML::DOM"

.IX Header "NAME"

.IX Header "DESCRIPTION"

.IX Subsection "\s-1METHODS\s0"

.IX Item "getTagName"

.IX Item "getAttribute (name)"

.IX Item "setAttribute (name, value)"

.IX Item "\(bu \s-1INVALID_CHARACTER_ERR\s0"

.IX Item "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0"

.IX Item "removeAttribute (name)"

.IX Item "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0"

.IX Item "getAttributeNode"

.IX Item "setAttributeNode (attr)"

.IX Item "\(bu \s-1WRONG_DOCUMENT_ERR\s0"

.IX Item "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0"

.IX Item "\(bu \s-1INUSE_ATTRIBUTE_ERR\s0"

.IX Item "removeAttributeNode (oldAttr)"

.IX Item "\(bu \s-1NO_MODIFICATION_ALLOWED_ERR\s0"

.IX Item "\(bu \s-1NOT_FOUND_ERR\s0"

.IX Subsection "Additional methods not in the \s-1DOM\s0 Spec"

.IX Item "setTagName (newTagName)"

.IX Item "\(bu \s-1INVALID_CHARACTER_ERR\s0"

.IX Item "check ($checker)"

